/** English copy for the owner dashboard. */
export const DASHBOARD_EN = {
  venue: "Venue",
  venues: "Venues",
  menu: "Catalog",
  menus: "Catalogs",
  qrCodes: "QR codes",
  subscription: "Subscription",
  logout: "Log out",
  calls: "Calls",
  settings: "Settings",
  account: "Account",
  accountEmail: "Login email",
  changePassword: {
    title: "Change password",
    current: "Current password",
    new: "New password (min 8)",
    confirm: "Confirm new password",
    submit: "Save password",
    saving: "Saving…",
    success: "Password updated.",
  },
  addVenue: "Add venue",
  editCatalog: "Edit catalog",
  livePreview: "Live preview",
  importPdf: "Import from PDF",
  importPdfPro: "PDF import (Pro only)",
  loadingCatalog: "Loading catalog...",
  importWizard: {
    hint:
      "Upload a catalog PDF — we analyze it automatically (digital + OCR for images). Review results before saving.",
    processSteps: [
      "Scan — quick preview in your browser (covers/logos are skipped automatically).",
      "Analyze — server reads text from digital pages; scanned pages use OCR if needed.",
      "Structure — categories and items are detected from the text.",
      "Review — edit the draft, then save to your catalog.",
    ] as string[],
    analyzeButton: "Analyze & preview",
    processingTitle: "Analyzing catalog PDF",
    pipeline: {
      scan: "Scanning PDF",
      extract: "Analyzing pages",
      ocr: "Image OCR",
      parse: "Categories & items",
      done: "Done",
    },
    loadingScanFile: (file: string, page: number, total: number) =>
      `${file} — page ${page}/${total}`,
    loadingImport: "Importing to catalog...",
    advancedTitle: "Advanced — page selection",
    advancedHint:
      "Covers/logos are skipped automatically. Change which pages are analyzed if something is missing.",
    pageKind: {
      digital: "Digital",
      scan: "OCR",
      cover: "Cover",
    },
    skipCoverFirst: "Cover / logo — skipped automatically",
    skipCoverLast: "Last page — likely back cover",
    skipLowText: "Little or no text",
    skipBanner: "First page — banner/logo",
    skipScan: "Image/scan — OCR",
    selectMenuPages: "Menu only",
    selectAll: "All",
    deselectAll: "None",
    reanalyze: "Re-analyze",
    ocrUsed: (n: number) => (n === 1 ? "1 page via OCR" : `${n} pages via OCR`),
    badge: "PDF IMPORT",
    phaseUpload: "Upload PDF",
    phaseReview: "Review & import",
    needVenueTitle: "You need a venue first",
    selectCatalogAndPdf: "Select a catalog and at least one PDF.",
    noMenuPagesScanDetail: "No menu pages found",
    noMenuPages:
      "No menu pages found. Open Advanced and select pages manually.",
    extractDetail: "Digital + OCR…",
    parseFailed: "Analysis failed. Try again or a smaller PDF.",
    previewPagesFirst: (btn: string) =>
      `Press «${btn}» first for page preview — or run analysis again.`,
    pageStats: (selected: number, digital: number, ocr: number, cover: number) =>
      `${selected} selected · ${digital} digital · ${ocr} OCR · ${cover} cover`,
    pageAlt: (page: number) => `Page ${page}`,
    pageNumber: (page: number, total: number) => `Pg. ${page}/${total}`,
    pdfFilesTitle: "PDF files (up to 10)",
    pdfFilesHint:
      "Digital PDF and scanned images (OCR). Covers/logos are skipped automatically.",
    dropzoneTitle: "Choose or drag PDF here",
    dropzoneHint: "Max 10MB per file",
    reviewSummary: (categories: number, itemsSelected: string) =>
      `${categories} categories · ${itemsSelected} selected`,
    reviewMeta: (files: number, withPrice: number, without: number) =>
      `From ${files} PDF · ${withPrice} with price · ${without} without price`,
    newAnalysis: "New analysis",
    afterImportHint:
      "After import, open the catalog to add photos, prices and availability.",
    importButton: (itemsSelected: string) => `Import ${itemsSelected}`,
    manualEditLink: "← Manual catalog editing",
    tableColItemGr: "Item (GR)",
    tableColEn: "EN",
    tableColPrice: "Price €",
    tableColNotes: "Notes",
    selectMinOneItem: (one: string) => `Select at least one ${one}.`,
  },
  previewCatalog: "Preview",
  newCatalogPlaceholder: "New catalog (e.g. Pool Bar)",
  addCatalog: "+ Catalog",
  deleteCatalog: "Delete catalog",
  deleteCatalogHasData: "You cannot delete a catalog that has categories or items.",
  deleteCatalogLast: "At least one catalog must remain for this venue.",
  deleteCatalogConfirm: (name: string) =>
    `Delete catalog «${name}»?\n\nAre you sure? This cannot be undone.`,
  roleLabels: {
    ADMIN: "Administrator",
    MANAGER: "Manager",
  } as Record<string, string>,
  planLabels: {
    TRIAL: "Free trial",
    BASIC: "Basic",
    PRO: "Pro",
    ENTERPRISE: "Enterprise",
  } as Record<string, string>,
  billing: {
    checkoutFailed: "Checkout could not start. Please try again.",
    cancelled: "Payment was cancelled. You were not charged.",
    confirming: "Confirming your payment...",
    confirmFailed: "Confirmation failed. If you were charged, email info@b-os.gr.",
    activated: "Subscription activated. Thank you!",
    activatedDev: "Plan activated (dev mode).",
    inactiveTitle: "Active subscription required",
    inactiveGeneric:
      "Your subscription is not active. Choose a plan so customers can keep viewing your QR menu.",
    canceledInactive:
      "Your subscription was canceled. Choose a plan again — your catalog is saved.",
    staffNoCheckout: "Only an admin or manager can change the plan.",
    currentPlan: "Current plan",
    statusLabel: "Status",
    trialUntil: "Trial until",
    periodUntil: "Current period until",
    perMonth: "/month",
    currentPlanBtn: "Current plan",
    checkoutLoading: "Redirecting...",
    networkError: "Network error",
    enterpriseFallback: "Custom domain, white-label and priority support.",
    contactUs: "Contact us at",
    selectPlan: (name: string) => `Choose ${name}`,
    upgradeTo: (name: string) => `Upgrade to ${name}`,
    downgradeTo: (name: string) => `Downgrade to ${name}`,
  },
  trial: {
    expired:
      "Your free trial has ended. Choose a plan to continue — customers no longer see your menu.",
    endingSoon: (days: number) =>
      days === 1
        ? "Your free trial ends tomorrow. Choose a plan so your menu stays online."
        : `Your free trial ends in ${days} days. Choose a plan when you're ready.`,
    bannerHealthy: (days: number, date: string) =>
      `Free trial — ${days} ${days === 1 ? "day" : "days"} left (until ${date})`,
    bannerMid: (days: number, date: string) =>
      `Trial in progress — ${days} ${days === 1 ? "day" : "days"} left (until ${date})`,
    bannerEnding: (days: number, date: string) =>
      `Trial ending soon — ${days} ${days === 1 ? "day" : "days"} (until ${date})`,
    bannerLastDay: "Your trial ends tomorrow — keep your menu online",
    setupHint: "Complete: venue → catalog → QR.",
    choosePlan: "View plans",
    upgradeNow: "Upgrade now",
    welcomeBadge: "Trial started",
    welcomeTitle: "Welcome to MenuOS",
    welcomeEnds: (days: number, date: string) =>
      `You have ${days} days free trial — ends ${date}. No card required.`,
    welcomeEmailHint: "We sent you an email with next steps. You'll get a reminder before it ends.",
    limits: "Trial: 1 venue, 1 catalog, up to 50 items. Upgrade anytime.",
    limitsNear: (count: number) =>
      `You have ${count}/50 items on trial. Need more? View the plans.`,
    limitsNearCta: "View plans",
    endsOn: "Trial until",
  },
  upgrade: {
    whyHere: "Why am I here?",
    pdfImport:
      "PDF menu import is available on the Pro plan. Upload a PDF and fill your catalog fast — without typing every item.",
    pdfImportCta: "See Pro plan",
  },
  welcome:
    "Welcome to MenuOS! Follow the guide below: set up your venue, add items to the catalog, then generate QR codes for your tables.",
  venueCreated:
    "Venue created! Now add categories and items — or import from PDF if you have Pro.",
  catalogEntry: {
    label: "Items",
    one: "item",
    many: "items",
    count: (n: number) => `${n} ${n === 1 ? "item" : "items"}`,
    add: "Add item",
    new: "New item",
    save: "Save item",
    deleteConfirm: "Delete this item?\n\nAre you sure? This cannot be undone.",
    editTitle: "Edit item",
    deleteTitle: "Delete item",
    empty: "No items yet — add the first one.",
    categoryHasEntries:
      "You cannot delete a category that has items. Delete all items first.",
    categoryDeleteHint: "Delete all items in this category first",
    notFound: "Item not found.",
    invalidData: "Invalid item data.",
    deactivated: "Item deactivated.",
    updated: "Item updated.",
    deleted: "Item deleted.",
    added: (name: string) => `Item «${name}» added to the catalog.`,
  },
  waiter: {
    shareTitle: "Link for the waiter's phone",
    shareDescription:
      "Copy and send the link (e.g. via WhatsApp). On the phone: open the page and tap Enable for notifications — no login or password.",
    sharePerDevice: "Notifications are per device — each waiter opens their own link.",
    rotateTitle: "Change access password",
    rotateDescription:
      "If the link leaked or staff changed, generate a new password. The old link stops working — send the new one to staff.",
    rotateConfirm:
      "Change the password? The current link will stop working and waiters will need the new one.",
    rotateButton: "New password",
    rotating: "Changing...",
    rotateFailed: "Failed to change password.",
    rotateSuccess: "Password changed. Send the new link to staff.",
    copyLink: "Copy link",
    copied: "Copied!",
    newItems: "New items",
    needVenueFirst: "Create a venue first to receive calls from customers.",
    managerViewBadge: "View: entire venue",
    staffViewBadge: (name: string, stations: string) => `View: ${name} · ${stations}`,
    monitorTabAll: "Map",
    monitorTabCalls: "Calls",
    monitorTabPass: "Pass",
    passFilterAll: "All",
    emptyCallsTab: "No active calls right now.",
    emptyPassTab: "No active pass notifications.",
    pendingCount: (n: number) => `${n} pending`,
    refreshHint: "Refreshes every 5 sec.",
    loadFailed: "Could not load calls. Refresh the page or open the link from the dashboard again.",
    sessionExpired: "Session expired — open the waiter link from the dashboard again.",
    emptyTitle: "No active calls",
    emptyDesc:
      "When a customer places an order, calls the waiter or requests the bill from the QR menu, it will appear here.",
    goButton: "On my way",
    completeButton: "Complete",
    orderTotal: "Total",
    callStatus: {
      PENDING: "Pending",
      ACKNOWLEDGED: "In progress",
      COMPLETED: "Completed",
      CANCELED: "Canceled",
    },
    callType: {
      WAITER: "Waiter call",
      BILL: "Bill",
      ORDER: "Order",
    },
    passSection: "Department pass",
    passEmpty: "No active pass notifications.",
    passCount: (n: number) => `${n} pass`,
    passPickedUp: "Picked up",
    passDelivered: "Delivered",
    passStatus: {
      READY: "Ready",
      PICKED_UP: "Picked up",
      DELIVERED: "Delivered",
    },
    passStation: {
      kitchen: "Kitchen",
      bar: "Bar",
      cold: "Cold",
      dessert: "Dessert",
    },
    tableGridTitle: "Spot map",
    tableStateLabels: {
      idle: "Quiet",
      guest_call: "Guest call",
      kitchen_ready: "Kitchen ready",
      bar_ready: "Bar ready",
      both: "Multiple",
    },
  },
  push: {
    title: "Notifications on this device",
    checking: "Checking notifications...",
    description:
      "Get notified when a waiter call or order arrives — even if the page is closed.",
    subscribed: "Notifications are enabled on this device.",
    denied: "Notifications were blocked by the browser. Change it in your phone settings.",
    enable: "Enable",
    disable: "Disable",
    enableSuccess: "Success — notifications are enabled on this device.",
    enableFailed: "Failed. Try again or open the link in Chrome/Safari.",
    unsupported:
      "This browser (e.g. Messenger, Instagram, WhatsApp) does not support push notifications. Open the link in Chrome (Android) or Safari (iPhone).",
    disabledServer: "Push notifications are not configured on the server — contact support.",
    inAppBrowser:
      "It looks like you opened the link inside Messenger or another app. For push: tap ⋮ → Open in Chrome or send the link to yourself and open it there.",
    iosHint:
      "iPhone: Open in Safari (not Messenger). Tap Enable → Allow notifications. For best results: Add to Home Screen.",
    androidHint:
      "Android: Open in Chrome (not Messenger). Tap Enable and allow notifications when prompted.",
    pageOpenHint:
      "While the page is open, you'll hear sounds and see calls automatically — even without push enabled.",
  },
  photos: {
    label: "Photo (optional)",
    logoLabel: "Venue logo",
    logoHint: "Shown on the QR menu next to the name. Square or round PNG/JPG — ideally 200×200 px.",
    logoSaveHint: "After upload, tap Save settings for it to appear on the menu.",
    uploadButton: "Upload from phone/computer",
    uploading: "Uploading...",
    uploadHint: "JPG or PNG up to 5 MB — optimized automatically for the menu.",
    uploadFailed: "Upload failed.",
    urlPlaceholder: "or paste photo URL",
    urlOptional: "or paste photo URL",
    urlOnlyHint: "Without a photo it appears as a clean row on the menu.",
    remove: "Remove",
  },
  layout: {
    tagline: "Menu management",
    welcome: "Welcome",
    subscriptionPrefix: "Subscription",
  },
  nav: {
    overview: "Overview",
    waiter: "Screens",
    history: "History",
    qrShort: "QR",
    callsShort: "Screens",
  },
  pages: {
    menus: {
      title: "Catalog",
      description: "Add categories and items — multiple languages are supported on the QR menu.",
    },
    import: {
      title: "Import from PDF",
      description:
        "Upload a PDF menu — review results before saving to the catalog.",
      backToCatalog: "← Back to catalog",
    },
    qr: {
      title: "QR Codes",
      description:
        "Download or preview QR for each spot. Configure tables in Settings → Tables.",
      configureSpotsLink: "Configure tables →",
      configureSpotsEmpty: "No spots yet. Set them up in Settings → Tables.",
      needVenueTitle: "You need a venue first",
      needVenueDesc: "Create a venue and add items before generating QR codes.",
      emptyCatalogTitle: "Catalog is empty",
      emptyCatalogBeforeLink: "Add items to the",
      catalogLink: "catalog",
      emptyCatalogAfterLink: "before sharing QR codes.",
      emptyCatalogAfterLinkCustomers: "before sharing QR codes with customers.",
      settingsTitle: "QR settings",
      settingsDesc:
        "Each QR opens the online catalog. Add a table or room number — so you know where calls come from.",
      tableLabel: "Table (optional)",
      roomLabel: "Room (optional)",
      defaultLangLabel: "Default QR language",
      generating: "Generating...",
      updateQr: "Update QR",
      downloadPng: "Download PNG",
      openCatalog: "Open catalog",
      generatedSuccess: "QR created! Download or print it.",
      spotsTitle: "Tables, rooms & sunbeds",
      spotsDesc:
        "Add each spot once. Each QR binds the number — the waiter sees exactly where calls come from.",
      spotTypeLabel: "Type",
      bulkTitle: "Bulk add",
      bulkDesc:
        "Add as many tables, rooms or sunbeds as you need — no plan limit. Up to 200 spots at a time (repeat with a new range for more). Optional prefix for zones (e.g. Patio-, Floor-).",
      prefixLabel: "Prefix (optional)",
      fromLabel: "From",
      toLabel: "To",
      bulkAdding: "Adding...",
      bulkAddAll: "Add all",
      spotNameLabel: "Number / name",
      spotPlaceholderRoom: "204 or vip-1",
      spotPlaceholderSunbed: "A12 or beach-3",
      spotPlaceholderTable: "12 or patio-1",
      addSpot: "Add",
      yourSpots: (count: number) => (count > 0 ? `Your spots (${count})` : "Your spots"),
      loadingSpots: "Loading...",
      emptySpots: "No spots yet. Add one or use bulk add (e.g. 1–120).",
      saveSpot: "Save",
      cancelEdit: "Cancel",
      editSpot: "Edit",
      deleteSpotLabel: "Delete",
      deleteSpotConfirm: (name: string) =>
        `Delete spot «${name}»?\n\nIf you already printed the QR, it will stop working. This cannot be undone.`,
      renameQrWarning: "Renaming changes the QR URL — reprint the QR if needed.",
      invalidRange: "Enter a valid range from 1 to 999 (e.g. from 1 to 120).",
      bulkLimit: "Maximum 200 spots at a time. For more, run a second batch (e.g. 201–400).",
      invalidPrefix: (hint: string) => `Invalid prefix. ${hint}`,
      labelHint: "Letters, numbers, hyphen and underscore only (e.g. 12, patio-1).",
      previewSpot: "Preview",
      showQr: "Show QR",
      hideQr: "Hide",
      loadingQr: "Loading QR…",
      spotTypes: {
        TABLE: "Table",
        ROOM: "Room",
        SUNBED: "Sunbed",
      } as Record<string, string>,
    },
    waiter: {
      title: "Screens",
      description:
        "Live spot map, calls and pass — updates automatically. Personal staff links are set in Settings → Personnel.",
      setupLink: "Settings → Personnel",
    },
    billing: {
      title: "Subscription",
      description: "Manage your MenuOS subscription. Payments are processed securely online.",
    },
    history: {
      title: "History",
      description:
        "Completed pass deliveries — time from ready to delivered, filterable by spot, department and waiter.",
      daysLabel: "Period",
      days7: "7 days",
      days30: "30 days",
      days90: "90 days",
      filterSpot: "Spot",
      filterStation: "Department",
      filterStaff: "Waiter",
      filterAll: "All",
      loading: "Loading...",
      empty: "No deliveries match these filters.",
      failed: "Could not load history. Try again.",
      colSpot: "Spot",
      colStation: "Department",
      colMessage: "Comment",
      colReady: "Ready",
      colDuration: "Duration",
      colStaff: "Waiter",
      colDelivered: "Delivered",
    },
    settings: {
      title: "Settings",
      description: "Account, staff, departments and table board.",
      tabs: {
        general: "General",
        personnel: "Personnel",
        kitchen: "Kitchen",
        bar: "Bar",
        tables: "Tables",
        services: "Services",
      },
      demoBadge: "Sample — UI preview",
      personnel: {
        title: "Personnel",
        description:
          "Each member gets a personal waiter link for their phone or tablet. Department tags filter which pass alerts they see.",
        addTitle: "New member",
        addStaff: "Add",
        saving: "Saving...",
        colName: "Name",
        colRole: "Role",
        colStations: "Departments",
        colLink: "Link",
        colActions: "",
        copyLink: "Copy link",
        copied: "Copied!",
        rotateLink: "New link",
        rotateConfirm: (name: string) =>
          `New link for “${name}”? The old one will stop working.`,
        sharedLinkTitle: "Shared link (whole team)",
        sharedLinkOptional: "optional",
        sharedLinkHint: "Backup — everyone sees all calls and pass alerts. Prefer a personal link per staff member.",
        namePlaceholder: "e.g. Maria P.",
        rolePlaceholder: "e.g. Waiter",
        loading: "Loading...",
        empty: "No staff added yet.",
        deleteConfirm: (name: string) => `Delete “${name}”?`,
        edit: "Edit",
        delete: "Delete",
        saveEdit: "Save",
        stationLabels: {
          services: "Services",
          kitchen: "Kitchen",
          bar: "Bar",
          cold: "Cold",
          dessert: "Dessert",
          all: "All",
        },
      },
      kitchen: {
        title: "Kitchen",
        description: "Chef screen — sends “pass ready” to waiters.",
        screenLink: "Kitchen screen link",
        screenHint: "Open on a kitchen tablet — no dashboard login.",
        sampleTable: "Table",
        sampleComment: "Comment (e.g. you forgot the ice)",
        sampleCommentPlaceholder: "you forgot the ice",
        sampleSend: "Ready at pass",
        openScreen: "Open screen",
        copyScreenLink: "Copy link",
      },
      kitchenTab: {
        title: "Kitchen screens",
        description:
          "Each screen opens on a tablet — no login. The chef taps “Ready” and waiters get notified.",
        steps:
          "Open the screen on the kitchen tablet\nCopy the link or tap “Open screen”\nFor a second kitchen/zone: add a new screen (e.g. Beach)",
      },
      bar: {
        title: "Bar",
        description: "Bar screen — notify waiters when drinks are ready.",
        screenLink: "Bar screen link",
        screenHint: "Quick actions for a bar tablet.",
        sampleSend: "Drink ready",
        openScreen: "Open screen",
        copyScreenLink: "Copy link",
      },
      barTab: {
        title: "Bar & dessert screens",
        description: "Same flow as kitchen — tablet at the bar or dessert pass, no login.",
        steps:
          "Open the screen on the bar tablet\nFor a second bar (e.g. beach): add a new screen\nDesserts can have their own screen",
      },
      cold: {
        title: "Cold kitchen",
        description: "Salads and cold starters — separate screen if you use one.",
        screenLink: "Cold kitchen screen link",
        screenHint: "Tablet at cold prep — no dashboard login.",
        openScreen: "Open screen",
        copyScreenLink: "Copy link",
      },
      dessert: {
        title: "Dessert",
        description: "Notify waiters when dessert is ready.",
        screenLink: "Dessert screen link",
        screenHint: "Tablet at dessert pass or near the bar.",
        openScreen: "Open screen",
        copyScreenLink: "Copy link",
      },
      rotateScreenButton: "New screen code",
      rotatingScreen: "Rotating...",
      rotateScreenConfirm: "Rotate the screen code? The current link will stop working.",
      rotateScreenFailed: "Could not rotate screen code.",
      multiScreenHint:
        "You can add multiple screens per department (e.g. beach bar and main bar) — each with its own link.",
      loadingScreens: "Loading screens…",
      screensEmpty: "No screens yet — add one below.",
      showLink: "Show link",
      hideLink: "Hide link",
      allTablesZone: "All tables / sunbeds / rooms",
      addScreenFor: (dept: string) => `New screen — ${dept}`,
      addScreenTitle: "Add screen",
      addScreenHint: "A name to tell them apart (e.g. Beach, Main room).",
      screenNameLabel: "Screen name",
      screenNamePlaceholder: "e.g. Beach",
      screenSpotPrefixLabel: "Zone (optional)",
      screenSpotPrefixPlaceholder: "e.g. Beach",
      screenSpotPrefixHint:
        "Empty = all tables, sunbeds and rooms. «Σαλόνι» = numeric tables only (1, 2, 3…). Any other prefix = only matching tables (e.g. Beach-1). Sunbeds/rooms need an empty prefix.",
      screenSpotPrefixHintShort:
        "Empty = all spots. «Σαλόνι» = numeric tables only. «Beach» = Beach-1, Beach-2… only",
      screenSpotPrefixActive: (prefix: string) => `Tables only: ${prefix}-*`,
      addScreenButton: "Add",
      addingScreen: "Adding…",
      addScreenFailed: "Could not add screen.",
      deleteScreen: "Delete",
      deleteScreenConfirm: (name: string) =>
        `Delete screen «${name}»?\n\nIts link will stop working.`,
      deleteScreenFailed: "Could not delete screen.",
      renameScreen: "Rename",
      saveScreen: "Save",
      savingScreen: "Saving…",
      cancelScreenEdit: "Cancel",
      renameScreenFailed: "Could not rename screen.",
      screenNameTaken: "A screen with this name already exists.",
      tables: {
        title: "Tables",
        description: "Configure tables, rooms and sunbeds. Download QR codes from the QR codes page.",
        gridPreview: "Spot map colors",
        gridHint: "Each color on the waiter board shows what is happening at that table.",
        qrLink: "Download QR codes →",
        yourVenueSpots: (name: string, count: number) => `${name} — ${count} spots`,
      },
      services: {
        title: "Services",
        description: "Waiter link, push alerts and live pass — guest calls plus department messages.",
        passTitle: "Live pass",
        passHint: "Stays visible until the waiter taps “Delivered”. The spot map updates live on the waiter panel.",
        livePanelLink: "Open live screens →",
        historyLink: "Delivery history →",
        staffLinksHint: "Waiter links: Settings → Personnel (one link per staff member).",
        minutesAgo: (n: number) => `${n} min ago`,
        tableLabel: (n: string) => `Table ${n}`,
        historyTitle: "Pass history",
        historyHint: "Completed deliveries — time from “ready” to “delivered”.",
        historyDaysLabel: "Period",
        historyDays7: "7 days",
        historyDays30: "30 days",
        historyDays90: "90 days",
        historyLoading: "Loading...",
        historyEmpty: "No deliveries in this period.",
        historyFailed: "Could not load history. Try again.",
        historyColSpot: "Spot",
        historyColStation: "Department",
        historyColMessage: "Comment",
        historyColReady: "Ready",
        historyColDuration: "Duration",
      },
      nameLabel: "Name",
      roleLabel: "Role",
      save: "Save settings",
      saving: "Saving...",
      appearanceTitle: "Catalog appearance",
      appearanceDesc: "Logo, colors and details customers see on the QR menu.",
      venueNameLabel: "Venue name",
      descriptionLabel: "Description",
      primaryColor: "Primary color",
      secondaryColor: "Secondary",
      needVenueFirst: "Create a venue first to configure colors and appearance.",
    },
    newVenue: {
      title: "New venue",
      description: "Your restaurant, bar or hotel. The first catalog will be created automatically.",
      nameLabel: "Venue name *",
      descriptionLabel: "Description (optional)",
      submit: "Create venue",
      submitting: "Creating...",
    },
  },
  onboarding: {
    guideLabel: "Getting started",
    stepTitle: (step: number) => `Step ${step} of 3 — build your catalog`,
    subtitle: "In under an hour you can have a QR menu on your tables.",
    completed: (n: number) => `${n}/3 complete`,
    done: "Done",
    pending: "Pending",
    previewIntro: "See how it looks to customers:",
    openCatalog: "Open catalog",
    steps: {
      venue: {
        title: "Set up your venue",
        desc: "Your restaurant, bar or hotel — e.g. «Marine Hotel» or «George's Taverna».",
      },
      menu: {
        title: "Add items to the catalog",
        descWithCategory: "Add items manually or import from PDF if you have Pro.",
        descWithoutCategory:
          "Create categories (Salads, Mains, Drinks...) and add prices and photos.",
      },
      qr: {
        title: "Generate QR codes for tables",
        desc: "Download QR codes, print them or use stands. Customers scan and see your catalog.",
      },
    },
  },
  overview: {
    titleFallback: "Overview",
    addFirstVenue: "Add your first",
    addToCatalog: "Add to catalog",
    quickActions: "Quick actions",
    quickStartEmpty: "Start by adding categories and items — then generate QR codes for your tables.",
    quickStartReady: "Your catalog is online! Generate QR codes or view customer calls.",
    callsWaiterSuffix: "waiter",
    renewalUntil: "Renews until",
    planField: "Plan",
    catalogOne: "catalog",
    catalogMany: "catalogs",
    passToday: "Pass alerts today",
    passTodayHint: "From kitchen / bar screens",
    passAvgDelivery: "Avg pickup time",
    passAvgDeliveryHint: "Ready → delivered, last 7 days",
    passAvgNone: "—",
    passAvgMinutes: (n: number) => `${n} min`,
    planSummary: (plan: string, venueN: number, venueWord: string, menuN: number, menuWord: string, items: string) =>
      `Plan: ${plan} · ${venueN} ${venueWord} · ${menuN} ${menuWord} · ${items}`,
  },
  menuEditor: {
    noVenueTitle: "You don't have a venue yet",
    noVenueDesc:
      "Create your venue (restaurant, bar or hotel) first, then add items to the catalog.",
    categoryNew: "New category",
    categoryHint: "Greek only — EN / DE / FR are auto-generated for the QR menu",
    addCategory: "Add category",
    addingCategory: "Adding...",
    categoryLabel: "Category",
    renameCategory: "Rename category",
    deleteEmptyCategory: "Delete empty category",
    deleteCategoryConfirm: "Delete this category?\n\nAre you sure? This cannot be undone.",
    invalidPrice: "Enter a valid price (e.g. 4.50).",
    categoryNameRequired: "Enter a category name.",
    loadingSubtitle: "Loading categories and items",
    editPrice: "Change price",
    qrBadge: "Badge on QR menu",
    active: "Active",
    inactive: "Inactive",
    remove: "Remove",
    saving: "Saving...",
    emptyCategories: "No categories yet. Add the first one above to get started.",
    autoTranslateHint: "Greek only — EN / DE / FR are auto-generated for the QR menu",
    qrExtrasTitle: "Customer options",
    qrExtrasHint:
      "Customers choose these on the QR menu. Optionally add an extra charge (e.g. +€1.50).",
    qrExtrasCount: (n: number) => `${n} QR options`,
    noBadge: "No badge",
    extraChargePlaceholder: "Extra charge (optional)",
    addExtraOption: "Add option",
    cancel: "Cancel",
  },
  flash: {
    close: "Close",
    genericError: "Something went wrong.",
    success: "Success!",
    codes: {
      subscription_inactive: "Your subscription is not active. Upgrade to continue.",
      trial_expired: "Your trial period has ended.",
      unauthorized: "Please sign in again.",
      forbidden: "You don't have permission.",
      venue_limit: "You've reached your plan's venue limit. See plans on Subscription.",
      menu_limit: "You've reached your plan's catalog limit.",
      item_limit: "You've reached your plan's item limit.",
      not_found: "Not found.",
      enterprise_contact: "Contact us for Enterprise pricing.",
      stripe_not_configured: "Payments are not available.",
      rate_limited: "Too many attempts. Try again later.",
      bad_request: "Invalid request.",
      invalid_input: "Invalid data.",
      password_mismatch: "New password and confirmation do not match.",
      password_same: "New password must differ from the current one.",
      invalid_password: "New password must be at least 8 characters.",
      wrong_password: "Current password is incorrect.",
      slug_exists: "This URL slug already exists. Try another venue name.",
    } as Record<string, string>,
  },
  meta: {
    appSuffix: "MenuOS",
    overview: "Overview",
    menus: "Catalog",
    import: "Import from PDF",
    qr: "QR Codes",
    waiter: "Screens",
    history: "History",
    billing: "Subscription",
    settings: "Settings",
    newVenue: "New venue",
  },
  api: {
    badRequest: "Invalid request.",
    invalidData: "Invalid data.",
    menuNotFound: "Catalog not found.",
    venueNotFound: "Venue not found.",
    categoryNotFound: "Category not found.",
    fillNameAndPrice: "Enter name and price.",
    fillCategoryNameGr: "Enter category name (Greek).",
    invalidCategoryName: "Invalid category name.",
    categoryAdded: (name: string) => `Category «${name}» added.`,
    categoryRenamed: (name: string) => `Category renamed to «${name}».`,
    categoryUpdated: "Category updated.",
    categoryDeleted: "Category deleted.",
    menuDeleted: "Catalog deleted.",
    venueSaved: "Settings saved.",
    venueCreated: "Venue created! Now add categories and items.",
    menuCreated: "Catalog created.",
    venueIdRequired: "Venue ID is required.",
    invalidMenuData: "Invalid catalog data.",
    slugExists: "This URL slug already exists. Try another venue name.",
    defaultMenuName: "Main catalog",
    spotAdded: "Spot added.",
    spotExists: "Spot already exists.",
    spotsBulkAdded: (n: number) => `Added ${n} spots.`,
    import: {
      invalidDraft: "Check categories, names and prices before importing.",
      selectMenu: "Select a catalog.",
      selectAtLeastOne: (one: string) => `Select at least one ${one}.`,
      parseFound: (items: string, categories: number) =>
        `Found ${items} in ${categories} categories. Review before importing.`,
      parseEmpty: (many: string) => `No ${many} found — try another PDF or add manually.`,
      parseFailed: "Could not read PDF. Try again or add the catalog manually.",
      applySuccess: (items: string, categories: number) =>
        `Imported ${items} into ${categories} categories. Edit photos and prices in the catalog.`,
    },
    pdf: {
      noFiles: "Select at least one PDF.",
      tooMany: (max: number) => `Maximum ${max} PDFs at a time.`,
      notPdf: (name: string) => `«${name}» is not a PDF.`,
      tooLarge: (name: string) => `«${name}» is too large (max 10MB).`,
      readFailed: (name: string) =>
        `Could not read «${name}». The file may be locked or corrupted.`,
      noText: (name: string, pageHint: string, ocrHint: string) =>
        `«${name}» did not yield recognizable text${pageHint}.${ocrHint}`,
      ocrNoText: " OCR found no text — try other pages or manual entry.",
      ocrNotConfigured: " Set OCR_SPACE_API_KEY on the server for scanned PDFs.",
      noPagesSelectedOcr:
        "No text on selected pages. Try Advanced → page selection.",
      noPagesSelectedNoOcr: "No digital text found. Configure OCR_SPACE_API_KEY for scanned PDFs.",
      pagesHint: (pages: number[]) => ` (pages ${pages.join(", ")})`,
    },
  },
  subscriptionStatus: {
    TRIALING: "Trial",
    ACTIVE: "Active",
    PAST_DUE: "Payment overdue",
    CANCELED: "Canceled",
    trialActive: "Active trial",
    trialExpired: "Expired",
    expiresOn: (date: string) => `Expires ${date}`,
    renewsOn: (date: string) => `Renews ${date}`,
    expiredOn: (date: string) => `Expired ${date}`,
  },
} as const;
