/** Ανθρώπινα ελληνικά για το panel διαχείρισης — χωρίς τεχνικούς όρους. */
export const DASHBOARD_EL = {
  venue: "Κατάστημα",
  venues: "Καταστήματα",
  menu: "Κατάλογος",
  menus: "Κατάλογοι",
  qrCodes: "QR codes",
  subscription: "Συνδρομή",
  logout: "Αποσύνδεση",
  calls: "Κλήσεις",
  settings: "Ρυθμίσεις",
  account: "Λογαριασμός",
  accountEmail: "Email σύνδεσης",
  changePassword: {
    title: "Αλλαγή κωδικού",
    current: "Τρέχων κωδικός",
    new: "Νέος κωδικός (min 8)",
    confirm: "Επιβεβαίωση νέου κωδικού",
    submit: "Αποθήκευση κωδικού",
    saving: "Αποθήκευση…",
    success: "Ο κωδικός άλλαξε.",
  },
  addVenue: "Προσθήκη καταστήματος",
  editCatalog: "Επεξεργασία καταλόγου",
  livePreview: "Δες πώς φαίνεται",
  importPdf: "Εισαγωγή από PDF",
  importPdfPro: "Εισαγωγή PDF (μόνο Pro)",
  loadingCatalog: "Φόρτωση καταλόγου...",
  importWizard: {
    hint:
      "Ανέβασε PDF καταλόγου — αναλύουμε αυτόματα (digital + OCR για εικόνες). Θα δεις αναφορά με κατηγορίες, είδη και προβλήματα πριν την εισαγωγή.",
    processSteps: [
      "Σάρωση — γρήγορη προεπισκόπηση στον browser (cover/logo παραλείπονται αυτόματα).",
      "Ανάλυση — ο server διαβάζει κείμενο από digital σελίδες· σαρωμένες σελίδες περνούν OCR αν χρειάζεται.",
      "Αναφορά — βλέπεις πόσες κατηγορίες/είδη βρέθηκαν και τι χρειάζεται διόρθωση.",
      "Έλεγχος — επεξεργάσου, ξετίκαρα ό,τι δεν θέλεις, και εισήγαγε στον κατάλογο.",
    ] as string[],
    analyzeButton: "Ανάλυση & προεπισκόπηση",
    processingTitle: "Ανάλυση PDF καταλόγου",
    pipeline: {
      scan: "Σάρωση PDF",
      extract: "Ανάλυση σελίδων",
      ocr: "OCR εικόνων",
      parse: "Κατηγορίες & είδη",
      done: "Έτοιμο",
    },
    loadingScanFile: (file: string, page: number, total: number) =>
      `${file} — σελίδα ${page}/${total}`,
    loadingImport: "Εισαγωγή στον κατάλογο...",
    advancedTitle: "Προχωρημένα — επιλογή σελίδων",
    advancedHint:
      "Cover/logo παραλείπονται αυτόματα. Άλλαξε ποιες σελίδες μπαίνουν στην ανάλυση αν κάτι λείπει.",
    pageKind: {
      digital: "Digital",
      scan: "OCR",
      cover: "Cover",
    },
    skipCoverFirst: "Cover / logo — παραλείπεται αυτόματα",
    skipCoverLast: "Τελευταία σελίδα — πιθανό back cover",
    skipLowText: "Λίγο ή καθόλου κείμενο",
    skipBanner: "Πρώτη σελίδα — banner/logo",
    skipScan: "Εικόνα/σάρωση — OCR",
    selectMenuPages: "Μόνο μενού",
    selectAll: "Όλες",
    deselectAll: "Καμία",
    reanalyze: "Ξανά ανάλυση",
    ocrUsed: (n: number) =>
      n === 1 ? "1 σελίδα μέσω OCR" : `${n} σελίδες μέσω OCR`,
    badge: "IMPORT ΑΠΟ PDF",
    phaseUpload: "Ανέβασμα PDF",
    phaseReview: "Αναφορά & έλεγχος πριν την εισαγωγή",
    needVenueTitle: "Χρειάζεσαι κατάστημα πρώτα",
    selectCatalogAndPdf: "Επίλεξε κατάλογο και τουλάχιστον ένα PDF.",
    activeCatalogTitle: "Στόχος εισαγωγής",
    activeCatalogHint:
      "Ο ίδιος κατάλογος με τη σελίδα Κατάλογοι — ό,τι εισάγεις από PDF θα μπει εδώ.",
    importTargetConfirm: (name: string) => `Τα είδη θα εισαχθούν στον κατάλογο «${name}».`,
    changeCatalogConfirm: (name: string) =>
      `Αλλαγή στόχου σε «${name}»;\n\nΤα είδη του PDF θα εισαχθούν στον νέο κατάλογο — όχι στον προηγούμενο.`,
    noMenuPagesScanDetail: "Δεν βρέθηκαν σελίδες μενού",
    noMenuPages: "Δεν βρέθηκαν σελίδες μενού. Άνοιξε «Προχωρημένα» και επίλεξε σελίδες χειροκίνητα.",
    extractDetail: "Digital + OCR…",
    parseFailed: "Αποτυχία ανάλυσης. Δοκίμασε ξανά ή μικρότερο PDF.",
    previewPagesFirst: (btn: string) =>
      `Πάτα «${btn}» πρώτα για preview σελίδων — ή ξανατρέξε ανάλυση.`,
    pageStats: (selected: number, digital: number, ocr: number, cover: number) =>
      `${selected} επιλεγμένες · ${digital} digital · ${ocr} OCR · ${cover} cover`,
    pageAlt: (page: number) => `Σελίδα ${page}`,
    pageNumber: (page: number, total: number) => `Σελ. ${page}/${total}`,
    pdfFilesTitle: "PDF αρχεία (έως 10)",
    pdfFilesHint:
      "Digital PDF και σαρωμένες εικόνες (OCR). Cover/logo παραλείπονται αυτόματα.",
    dropzoneTitle: "Επίλεξε ή σύρε PDF εδώ",
    dropzoneHint: "Max 10MB ανά αρχείο",
    reviewSummary: (categories: number, itemsSelected: string) =>
      `${categories} κατηγορίες · ${itemsSelected} επιλεγμένα`,
    reviewMeta: (files: number, withPrice: number, without: number) =>
      `Από ${files} PDF · ${withPrice} τιμές · ${without} χωρίς τιμή`,
    newAnalysis: "Νέα ανάλυση",
    afterImportHint:
      "Μετά την εισαγωγή, άνοιξε τον κατάλογο για φωτο, τιμές και διαθεσιμότητα.",
    importButton: (itemsSelected: string) => `Εισαγωγή ${itemsSelected}`,
    manualEditLink: "← Χειροκίνητη επεξεργασία καταλόγου",
    tableColItemGr: "Είδος (GR)",
    tableColEn: "EN",
    tableColPrice: "Τιμή €",
    tableColNotes: "Σημειώσεις",
    selectMinOneItem: (one: string) => `Επίλεξε τουλάχιστον ένα ${one}.`,
    report: {
      title: "Αποτελέσματα ανάλυσης",
      subtitle: "Έλεγξε τι βρήκαμε στο PDF πριν μπουν στον κατάλογο",
      statCategories: "Κατηγορίες",
      statCategoriesSub: (withItems: number, empty: number) =>
        `${withItems} με είδη · ${empty} κενές`,
      statItems: "Είδη",
      statItemsSub: (selected: number) => `${selected} επιλεγμένα για εισαγωγή`,
      statPrices: "Με τιμή",
      statPricesSub: (without: number) =>
        without > 0 ? `${without} χωρίς τιμή — συμπλήρωσέ τες` : "Όλα έχουν τιμή",
      statReady: "Έτοιμο;",
      statReadyYes: "Ναι",
      statReadyNo: "Όχι ακόμα",
      issuesTitle: "Προβλήματα & σημειώσεις",
      issuesNone: "Δεν βρήκαμε σοβαρά προβλήματα — έλεγξε ονόματα και τιμές πριν την εισαγωγή.",
      ocrBadge: (n: number) => (n === 1 ? "1 σελίδα OCR" : `${n} σελίδες OCR`),
      extractionPath: {
        digital: "Digital PDF",
        ocr: "OCR (σάρωση)",
        hybrid: "Hybrid (digital + OCR)",
        vision: "Vision AI",
      },
      visionUsedBadge: (n: number) =>
        n === 1 ? "1 σελίδα Vision AI" : `${n} σελίδες Vision AI`,
      visionHint:
        "Το layout φαίνεται πολύπλοκο — έλεγξε προσεκτικά. Βάλε GEMINI_API_KEY για αυτόματη ανάλυση εικόνας.",
      nextStepsTitle: "Τι κάνεις τώρα",
      nextSteps: [
        "Ξετικίνα κατηγορίες ή είδη που δεν θέλεις να μπουν.",
        "Διόρθωσε ονόματα και τιμές στα πεδία — ιδίως όσα είναι κίτρινα.",
        "Όταν είσαι σίγουρος, πάτα «Εισαγωγή στον κατάλογο».",
      ] as string[],
      issueNoItems: "Δεν βρέθηκαν είδη στο PDF.",
      issueNoItemsHint:
        "Δοκίμασε άλλες σελίδες στα Προχωρημένα ή άλλο PDF. Σε σαρωμένα μενού χρειάζεται OCR.",
      issueNoPrice: (n: number) =>
        n === 1 ? "1 είδος χωρίς τιμή." : `${n} είδη χωρίς τιμή.`,
      issueNoPriceHint: "Βάλε τιμή ή άφησέ το €0 — μπορείς να το αλλάξεις μετά στον κατάλογο.",
      issueEmptyCategories: (n: number) =>
        n === 1 ? "1 κενή κατηγορία (χωρίς είδη)." : `${n} κενές κατηγορίες.`,
      issueEmptyCategoriesHint: "Δεν θα εισαχθούν — κρύβονται από προεπιλογή.",
      issueDuplicateCategories: (n: number) =>
        n === 1
          ? "1 κατηγορία με πιθανά διπλότυπα."
          : `${n} κατηγορίες με πιθανά διπλότυπα.`,
      issueItemWarnings: (n: number) =>
        n === 1 ? "1 είδος χρειάζεται έλεγχο." : `${n} είδη χρειάζονται έλεγχο.`,
      issueItemWarningsHint: "Δες τη στήλη «Σημειώσεις» — κίτρινα πεδία τιμής ή σύντομα ονόματα.",
      issueNothingSelected: "Δεν έχεις επιλέξει κανένα είδος.",
      issueNothingSelectedHint: "Τσέκαρε τουλάχιστον ένα είδος ή κατηγορία για εισαγωγή.",
      issueOcr: "Το PDF είναι σαρωμένη εικόνα — χρησιμοποιήθηκε OCR.",
      issueOcrHint:
        "Μπορεί να λείπουν ή να είναι λάθος ονόματα/τιμές. Έλεγξε προσεκτικά πριν την εισαγωγή.",
    },
    editor: {
      toolbarTitle: "Επεξεργασία προσχεδίου",
      toolbarHint:
        "Κάθε μπλοκ είναι μια κατηγορία. Κάτω από αυτή βλέπεις τα είδη με όνομα και τιμή — όπως στο PDF, χωρίς αυτόματη μετάφραση.",
      searchPlaceholder: "Αναζήτηση είδους ή κατηγορίας…",
      hideEmpty: "Κρύψε κενές κατηγορίες",
      showIssuesOnly: "Μόνο με θέματα",
      selectAll: "Επιλογή όλων",
      deselectAll: "Αποεπιλογή όλων",
      expandAll: "Άνοιγμα όλων",
      collapseAll: "Κλείσιμο όλων",
      categoryLabel: "Κατηγορία",
      categoryEnLabel: "Κατηγορία στα αγγλικά (μόνο αν υπάρχει στο PDF)",
      uncategorizedHint:
        "Αυτά τα είδη δεν μπήκαν σε ξεχωριστή κατηγορία από το PDF. Μπορείς να τα εισαγάγεις έτσι και να τα μετακινήσεις αργότερα στον κατάλογο.",
      emptyCategory: "Καμία είδος σε αυτή την κατηγορία",
      itemsCount: (selected: number, total: number) => `${selected}/${total} επιλεγμένα`,
      noResults: "Δεν βρέθηκαν κατηγορίες με αυτά τα κριτήρια.",
      itemNameLabel: "Όνομα είδους",
      itemNameEnLabel: "Όνομα στα αγγλικά (μόνο αν υπάρχει στο PDF)",
      addEnglish: "+ Προσθήκη αγγλικών",
      priceLabel: "Τιμή",
      issueBadge: "Έλεγχος",
      includeCategory: "Συμπερίληψη κατηγορίας στην εισαγωγή",
      includeItem: "Συμπερίληψη είδους στην εισαγωγή",
    },
    importConfirmTitle: "Έτοιμος για εισαγωγή",
    importConfirmHint: (categories: number, items: string) =>
      `Θα προστεθούν ${categories} κατηγορίες και ${items} στον κατάλογο που επέλεξες.`,
  },
  previewCatalog: "Προεπισκόπηση",
  newCatalogPlaceholder: "Νέος κατάλογος (π.χ. Pool Bar)",
  addCatalog: "+ Κατάλογος",
  deleteCatalog: "Διαγραφή καταλόγου",
  deleteCatalogHasData: "Δεν μπορείς να διαγράψεις κατάλογο που έχει κατηγορίες ή είδη.",
  deleteCatalogLast: "Πρέπει να υπάρχει τουλάχιστον ένας κατάλογος στο κατάστημα.",
  deleteCatalogConfirm: (name: string) =>
    `Διαγραφή του καταλόγου «${name}»;\n\nΕίσαι σίγουρος; Η ενέργεια δεν αναιρείται.`,
  deleteAllCatalogs: "Διαγραφή όλων των καταλόγων",
  deleteAllCatalogsConfirm: (stats: { menus: number; categories: number; items: number }) => {
    const lines = [
      "ΠΡΟΣΟΧΗ — μόνιμη διαγραφή",
      "",
      "Θα διαγραφούν ΟΛΟΙ οι κατάλογοι αυτού του καταστήματος:",
      `• ${stats.menus} ${stats.menus === 1 ? "κατάλογος" : "κατάλογοι"}`,
    ];
    if (stats.categories > 0) {
      lines.push(
        `• ${stats.categories} ${stats.categories === 1 ? "κατηγορία" : "κατηγορίες"}`,
      );
    }
    if (stats.items > 0) {
      lines.push(`• ${stats.items} ${stats.items === 1 ? "είδος" : "είδη"}`);
    }
    lines.push(
      "",
      "Δεν μπορούμε να τα επαναφέρουμε — χάνονται οριστικά.",
      "",
      "Θα μείνει ένας κενός κατάλογος για να ξεκινήσεις από την αρχή.",
      "",
      "Συνέχεια;",
    );
    return lines.join("\n");
  },
  roleLabels: {
    ADMIN: "Διαχειριστής",
    MANAGER: "Υπεύθυνος",
  } as Record<string, string>,
  planLabels: {
    TRIAL: "Δωρεάν δοκιμή",
    BASIC: "Basic",
    PRO: "Pro",
    ENTERPRISE: "Enterprise",
  } as Record<string, string>,
  billing: {
    checkoutFailed: "Δεν ξεκίνησε η πληρωμή. Δοκίμασε ξανά.",
    cancelled: "Η πληρωμή ακυρώθηκε. Δεν χρεώθηκε τίποτα.",
    confirming: "Επιβεβαιώνουμε την πληρωμή σου...",
    confirmFailed: "Η επιβεβαίωση απέτυχε. Αν χρεωθήκες, στείλε email στο info@qrmenus.info.",
    activated: "Η συνδρομή ενεργοποιήθηκε. Ευχαριστούμε!",
    activatedDev: "Το πλάνο ενεργοποιήθηκε (δοκιμαστική λειτουργία).",
    inactiveTitle: "Χρειάζεται ενεργή συνδρομή",
    inactiveGeneric:
      "Η συνδρομή σου δεν είναι ενεργή. Διάλεξε πλάνο για να συνεχίσουν οι πελάτες σου να βλέπουν τον QR κατάλογο.",
    canceledInactive:
      "Η συνδρομή σου ακυρώθηκε. Διάλεξε ξανά πλάνο — ο κατάλογός σου είναι αποθηκευμένος.",
    staffNoCheckout: "Μόνο διαχειριστής ή υπεύθυνος μπορεί να αλλάξει πλάνο.",
    currentPlan: "Τρέχον πλάνο",
    statusLabel: "Κατάσταση",
    trialUntil: "Δοκιμή έως",
    periodUntil: "Τρέχουσα περίοδος έως",
    perMonth: "/μήνα",
    currentPlanBtn: "Τρέχον πλάνο",
    checkoutLoading: "Μετάβαση...",
    networkError: "Σφάλμα δικτύου",
    enterpriseFallback:
      "Custom domain, white-label και προτεραιότητα υποστήριξης.",
    contactUs: "Γράψε μας στο",
    selectPlan: (name: string) => `Επιλογή ${name}`,
    upgradeTo: (name: string) => `Αναβάθμιση σε ${name}`,
    downgradeTo: (name: string) => `Υποβάθμιση σε ${name}`,
  },
  trial: {
    expired:
      "Η δωρεάν δοκιμή σου έληξε. Διάλεξε πλάνο για να συνεχίσεις — οι πελάτες σου δεν βλέπουν πλέον το menu.",
    endingSoon: (days: number) =>
      days === 1
        ? "Η δωρεάν δοκιμή σου λήγει αύριο. Διάλεξε πλάνο για να μην σταματήσει το menu."
        : `Η δωρεάν δοκιμή σου λήγει σε ${days} μέρες. Διάλεξε πλάνο όταν είσαι έτοιμος.`,
    bannerHealthy: (days: number, date: string) =>
      `Δωρεάν δοκιμή — ${days} ${days === 1 ? "μέρα" : "μέρες"} απομένουν (έως ${date})`,
    bannerMid: (days: number, date: string) =>
      `Μέσα στη δοκιμή σου — ${days} ${days === 1 ? "μέρα" : "μέρες"} απομένουν (έως ${date})`,
    bannerEnding: (days: number, date: string) =>
      `Η δοκιμή λήγει σύντομα — ${days} ${days === 1 ? "μέρα" : "μέρες"} (έως ${date})`,
    bannerLastDay: "Η δοκιμή σου λήγει αύριο — κράτησε το menu online",
    setupHint: "Ολοκλήρωσε: κατάστημα → κατάλογος → QR.",
    choosePlan: "Δες τα πλάνα",
    upgradeNow: "Αναβάθμιση τώρα",
    welcomeBadge: "Ξεκίνημα δοκιμής",
    welcomeTitle: "Καλώς ήρθες στο MenuOS",
    welcomeEnds: (days: number, date: string) =>
      `Έχεις ${days} ημέρες δωρεάν δοκιμή — λήγει ${date}. Χωρίς κάρτα.`,
    welcomeEmailHint: "Σου στείλαμε email με τα βήματα. Θα λάβεις υπενθύμιση πριν τη λήξη.",
    limits:
      "Στη δοκιμή: 1 κατάστημα, 1 κατάλογος, μέχρι 50 είδη. Μπορείς να αναβαθμιστείς όποτε θες.",
    limitsNear: (count: number) =>
      `Έχεις ${count}/50 είδη στη δοκιμή. Αν χρειάζεσαι περισσότερα, δες τα πλάνα.`,
    limitsNearCta: "Δες τα πλάνα",
    endsOn: "Δοκιμή έως",
  },
  upgrade: {
    whyHere: "Γιατί είμαι εδώ;",
    pdfImport:
      "Η εισαγωγή menu από PDF είναι διαθέσιμη στο πλάνο Pro. Ανέβασε PDF και γεμίζεις τον κατάλογο γρήγορα — χωρίς να πληκτρολογείς κάθε είδος.",
    pdfImportCta: "Δες το πλάνο Pro",
  },
  welcome:
    "Καλώς ήρθες στο MenuOS! Ακολούθησε τον οδηγό παρακάτω: πρώτα φτιάξε το κατάστημά σου, μετά βάλε είδη στον κατάλογο και τέλος βγάλε QR για τα τραπέζια.",
  venueCreated:
    "Το κατάστημα δημιουργήθηκε! Τώρα πρόσθεσε κατηγορίες και είδη — ή κάνε εισαγωγή από PDF αν έχεις Pro.",
  /** Γενικός όρος καταλόγου — φαγητά, ποτά, κ.λπ. (όχι μόνο «πιάτα»). */
  catalogEntry: {
    label: "Είδη",
    one: "είδος",
    many: "είδη",
    count: (n: number) => `${n} ${n === 1 ? "είδος" : "είδη"}`,
    add: "Προσθήκη είδους",
    new: "Νέο είδος",
    save: "Αποθήκευση είδους",
    deleteConfirm: "Διαγραφή του είδους;\n\nΕίσαι σίγουρος; Η ενέργεια δεν αναιρείται.",
    editTitle: "Επεξεργασία είδους",
    deleteTitle: "Διαγραφή είδους",
    empty: "Δεν υπάρχουν είδη — πρόσθεσε το πρώτο.",
    categoryHasEntries:
      "Δεν μπορείς να διαγράψεις κατηγορία που έχει είδη. Διέγραψε πρώτα όλα τα είδη.",
    categoryDeleteHint: "Διέγραψε πρώτα όλα τα είδη της κατηγορίας",
    notFound: "Το είδος δεν βρέθηκε.",
    invalidData: "Μη έγκυρα δεδομένα είδους.",
    deactivated: "Το είδος απενεργοποιήθηκε.",
    updated: "Το είδος ενημερώθηκε.",
    deleted: "Το είδος διαγράφηκε.",
    added: (name: string) => `Το είδος «${name}» προστέθηκε στον κατάλογο.`,
  },
  waiter: {
    shareTitle: "Link για το κινητό του σερβιτόρου",
    shareDescription:
      "Αντέγραψε και στείλε το link (π.χ. με WhatsApp). Στο κινητό: άνοιξε τη σελίδα και πάτα «Ενεργοποίηση» για ειδοποιήσεις — χωρίς σύνδεση ή κωδικό.",
    sharePerDevice: "Οι ειδοποιήσεις είναι ανά συσκευή — κάθε σερβιτόρος ανοίγει το δικό του link.",
    rotateTitle: "Αλλαγή κωδικού πρόσβασης",
    rotateDescription:
      "Αν το link διέρρευσε ή άλλαξε προσωπικό, δημιούργησε νέο κωδικό. Το παλιό link σταματά να λειτουργεί — στείλε το νέο στους σερβιτόρους.",
    rotateConfirm:
      "Να αλλάξει ο κωδικός; Το τρέχον link θα σταματήσει να λειτουργεί και οι σερβιτόροι θα χρειαστούν το νέο.",
    rotateButton: "Νέος κωδικός",
    rotating: "Αλλαγή...",
    rotateFailed: "Αποτυχία αλλαγής κωδικού.",
    rotateSuccess: "Ο κωδικός άλλαξε. Στείλε το νέο link στο προσωπικό.",
    viewLink: "Προβολή",
    copyLink: "Αντιγραφή link",
    copied: "Αντιγράφηκε!",
    newItems: "Νέα είδη",
    needVenueFirst: "Φτιάξε πρώτα κατάστημα για να λαμβάνεις κλήσεις από πελάτες.",
    managerViewBadge: "Προβολή: όλο το κατάστημα",
    staffViewBadge: (name: string, stations: string) => `Προβολή: ${name} · ${stations}`,
    monitorTabAll: "Χάρτης",
    monitorTabCalls: "Κλήσεις",
    monitorTabPass: "Πάσο",
    passFilterAll: "Όλα",
    zoneFilterAll: "Όλες οι ζώνες",
    zonePickHeading: "Διάλεξε ζώνη",
    emptyCallsTab: "Καμία ενεργή κλήση αυτή τη στιγμή.",
    emptyPassTab: "Καμία ενεργή ειδοποίηση πάσου.",
    emptyFilteredView: "Καμία ενεργή κίνηση με αυτά τα φίλτρα.",
    emptyZoneView: "Καμία θέση ή κίνηση σε αυτή τη ζώνη αυτή τη στιγμή.",
    pendingCount: (n: number) => `${n} σε αναμονή`,
    refreshHint: "Ανανέωση κάθε 5 δευτ.",
    loadFailed: "Δεν φορτώθηκαν οι κλήσεις. Κάνε refresh ή άνοιξε ξανά το link από το dashboard.",
    sessionExpired: "Έληξε η σύνδεση — άνοιξε ξανά το link σερβιτόρου από το dashboard.",
    emptyTitle: "Καμία ενεργή κλήση",
    emptyDesc:
      "Όταν πελάτης στείλει παραγγελία, καλέσει σερβιτόρο ή ζητήσει λογαριασμό από το QR menu, θα εμφανιστεί εδώ.",
    emptySpotsActiveHint:
      "Δεν έχουν ρυθμιστεί θέσεις — οι ενεργές κλήσεις εμφανίζονται παρακάτω. Ρύθμισε τραπέζια/δωμάτια από Ρυθμίσεις → Θέσεις.",
    unmappedSpotBadge: "Χωρίς ρύθμιση",
    goButton: "Αποδοχή",
    completeButton: "Έτοιμο",
    orderTotal: "Σύνολο",
    callStatus: {
      PENDING: "Σε αναμονή",
      ACKNOWLEDGED: "Σε εξέλιξη",
      COMPLETED: "Ολοκληρώθηκε",
      CANCELED: "Ακυρώθηκε",
    },
    callType: {
      WAITER: "Κλήση σερβιτόρου",
      BILL: "Λογαριασμός",
      ORDER: "Παραγγελία",
    },
    passSection: "Πάσα τμημάτων",
    passEmpty: "Καμία ενεργή ειδοποίηση πάσου.",
    passCount: (n: number) => `${n} πάσο`,
    passPickedUp: "OK",
    passDelivered: "Έτοιμο",
    passStatus: {
      READY: "Έτοιμο",
      PICKED_UP: "Σε εξέλιξη",
      DELIVERED: "Έτοιμο",
    },
    passStation: {
      kitchen: "Κουζίνα",
      bar: "Μπαρ",
      cold: "Κρύα",
      dessert: "Γλυκά",
    },
    passReadyLabel: {
      kitchen: "Έτοιμο — κουζίνα",
      bar: "Έτοιμο — μπαρ",
      cold: "Έτοιμο — κρύα",
      dessert: "Έτοιμο — γλυκά",
    },
    tableGridTitle: "Χάρτης θέσεων",
    tableGridLegendHint: "Η κατάσταση εμφανίζεται πάνω σε κάθε κάρτα.",
    tableStateLabels: {
      idle: "Ήσυχο",
      guest_call: "Κλήση πελάτη",
      kitchen_ready: "Έτοιμο — κουζίνα",
      cold_ready: "Έτοιμο — κρύα",
      bar_ready: "Έτοιμο — μπαρ",
      both: "Πολλαπλά",
    },
  },
  push: {
    title: "Ειδοποιήσεις σε αυτή τη συσκευή",
    checking: "Έλεγχος ειδοποιήσεων...",
    description:
      "Λάβε ειδοποίηση όταν έρχεται κλήση σερβιτόρου ή παραγγελία — ακόμα κι αν η σελίδα είναι κλειστή.",
    subscribed: "Οι ειδοποιήσεις είναι ενεργές σε αυτή τη συσκευή.",
    denied: "Οι ειδοποιήσεις αποκλείστηκαν από το browser. Άλλαξέ το από τις ρυθμίσεις του κινητού.",
    enable: "Ενεργοποίηση",
    disable: "Απενεργοποίηση",
    enableSuccess: "Επιτυχία — οι ειδοποιήσεις είναι ενεργές σε αυτή τη συσκευή.",
    enableFailed: "Αποτυχία. Δοκίμασε ξανά ή άνοιξε το link σε Chrome/Safari.",
    unsupported:
      "Αυτό το browser (π.χ. Messenger, Instagram, WhatsApp) δεν υποστηρίζει push ειδοποιήσεις. Άνοιξε το link σε Chrome (Android) ή Safari (iPhone).",
    disabledServer: "Οι push ειδοποιήσεις δεν είναι ρυθμισμένες στον server — επικοινώνησε με την υποστήριξη.",
    inAppBrowser:
      "Φαίνεται ότι άνοιξες το link μέσα σε Messenger ή άλλη εφαρμογή. Για push: πάτα ⋮ → «Άνοιγμα στο Chrome» ή στείλε το link στον εαυτό σου και άνοιξέ το εκεί.",
    iosHint:
      "iPhone: Άνοιξε σε Safari (όχι Messenger). Πάτα «Ενεργοποίηση» → Επίτρεψε ειδοποιήσεις. Για καλύτερα αποτελέσματα: Προσθήκη στην Αρχική οθόνη.",
    androidHint:
      "Android: Άνοιξε σε Chrome (όχι Messenger). Πάτα «Ενεργοποίηση» και επέτρεψε ειδοποιήσεις όταν το ζητήσει.",
    pageOpenHint:
      "Όσο η σελίδα είναι ανοιχτή, θα ακούς ήχο και θα βλέπεις κλήσεις αυτόματα — ακόμα κι αν δεν ενεργοποιήσεις push.",
    managerHint:
      "Λαμβάνεις push για κλήσεις και πάσο σε όλα τα καταστήματα της επιχείρησης σε αυτή τη συσκευή.",
  },
  photos: {
    label: "Φωτογραφία (προαιρετικό)",
    logoLabel: "Logo καταστήματος",
    logoHint: "Εμφανίζεται στο QR menu δίπλα στο όνομα. Τετράγωνο ή στρογγυλό PNG/JPG — ιδανικά 200×200 px.",
    logoSaveHint: "Μετά το upload, πάτα «Αποθήκευση ρυθμίσεων» για να εμφανιστεί στο menu.",
    uploadButton: "Ανέβασμα από κινητό/υπολογιστή",
    uploading: "Ανέβασμα...",
    uploadHint: "JPG ή PNG έως 5 MB — βελτιστοποιείται αυτόματα για το menu.",
    uploadFailed: "Αποτυχία ανεβάσματος.",
    urlPlaceholder: "ή επικόλλησε link φωτογραφίας",
    urlOptional: "ή επικόλλησε link φωτογραφίας",
    urlOnlyHint: "Χωρίς φωτό εμφανίζεται ως καθαρή γραμμή στο menu.",
    remove: "Αφαίρεση",
  },
  layout: {
    tagline: "Διαχείριση menu",
    welcome: "Καλώς ήρθες",
    subscriptionPrefix: "Συνδρομή",
  },
  nav: {
    overview: "Επισκόπηση",
    waiter: "Οθόνες",
    history: "Ιστορικό",
    qrShort: "QR",
    callsShort: "Οθόνες",
  },
  pages: {
    menus: {
      title: "Κατάλογος",
      description:
        "Πρόσθεσε κατηγορίες και είδη — υποστηρίζονται πολλαπλές γλώσσες στο QR menu.",
    },
    import: {
      title: "Εισαγωγή από PDF",
      description:
        "Ανέβασε PDF menu — ελέγχεις τα αποτελέσματα πριν τα αποθηκεύσεις στον κατάλογο.",
      backToCatalog: "← Πίσω στον κατάλογο",
    },
    qr: {
      title: "QR Codes",
      description:
        "Κατέβασε ή δες QR για κάθε θέση. Τα τραπέζια ρυθμίζονται από Ρυθμίσεις → Ταμπλό.",
      configureSpotsLink: "Ρύθμιση τραπεζιών →",
      configureSpotsEmpty: "Δεν έχεις ακόμα θέσεις. Ρύθμισέ τες από Ρυθμίσεις → Ταμπλό.",
      needVenueTitle: "Χρειάζεσαι πρώτα κατάστημα",
      needVenueDesc: "Φτιάξε κατάστημα και πρόσθεσε είδη πριν βγάλεις QR.",
      emptyCatalogTitle: "Ο κατάλογος είναι άδειος",
      emptyCatalogBeforeLink: "Πρόσθεσε είδη στον",
      catalogLink: "κατάλογο",
      emptyCatalogAfterLink: "πριν μοιράσεις QR.",
      emptyCatalogAfterLinkCustomers: "πριν μοιράσεις QR στους πελάτες.",
      settingsTitle: "Ρυθμίσεις QR",
      settingsDesc:
        "Κάθε QR ανοίγει τον online κατάλογο. Βάλε αριθμό τραπεζιού ή δωματίου — έτσι ξέρεις από πού σε καλούν.",
      tableLabel: "Τραπέζι (προαιρετικό)",
      roomLabel: "Δωμάτιο (προαιρετικό)",
      defaultLangLabel: "Προεπιλεγμένη γλώσσα QR",
      generating: "Δημιουργία...",
      updateQr: "Ενημέρωση QR",
      downloadPng: "Κατέβασμα PNG",
      openCatalog: "Άνοιγμα καταλόγου",
      generatedSuccess: "Το QR δημιουργήθηκε! Κατέβασέ το ή εκτύπωσέ το.",
      spotsTitle: "Τραπέζια, δωμάτια & ξαπλώστρες",
      spotsDesc:
        "Πρόσθεσε κάθε θέση μία φορά. Κάθε QR «δένει» τον αριθμό — ο σερβιτόρος βλέπει ακριβώς από πού καλούν.",
      spotTypeLabel: "Τύπος",
      bulkTitle: "Μαζική προσθήκη",
      bulkDesc:
        "Όσα τραπέζια, δωμάτια ή ξαπλώστρες χρειάζεσαι — χωρίς όριο πλάνου. Έως 200 θέσεις κάθε φορά (για περισσότερες, επανάλαβε με νέο εύρος). Προαιρετικό πρόθεμα για ζώνες (π.χ. Αυλή-, Όροφος-).",
      prefixLabel: "Πρόθεμα (προαιρετικό)",
      fromLabel: "Από",
      toLabel: "Έως",
      bulkAdding: "Προσθήκη...",
      bulkAddAll: "Προσθήκη όλων",
      spotNameLabel: "Αριθμός / όνομα",
      spotPlaceholderRoom: "204 ή vip-1",
      spotPlaceholderSunbed: "A12 ή paralia-3",
      spotPlaceholderTable: "12 ή Αυλή-1",
      addSpot: "Προσθήκη",
      yourSpots: (count: number) => (count > 0 ? `Οι θέσεις σου (${count})` : "Οι θέσεις σου"),
      loadingSpots: "Φόρτωση...",
      emptySpots: "Δεν έχεις ακόμα θέσεις. Πρόσθεσε μία θέση ή κάνε μαζική προσθήκη (π.χ. 1–120).",
      saveSpot: "Αποθήκευση",
      cancelEdit: "Άκυρο",
      editSpot: "Επεξεργασία",
      deleteSpotLabel: "Διαγραφή",
      deleteSpotConfirm: (name: string) =>
        `Διαγραφή της θέσης «${name}»;\n\nΑν έχεις ήδη τυπώσει QR, δεν θα λειτουργεί πλέον. Η ενέργεια δεν αναιρείται.`,
      renameQrWarning:
        "Αλλάζοντας το όνομα, αλλάζει και το URL του QR — ξανατύπωσε QR αν χρειάζεται.",
      invalidRange: "Βάλε έγκυρο εύρος από 1 έως 999 (π.χ. από 1 έως 120).",
      bulkLimit: "Μέγιστο 200 θέσεις ανά φορά. Για περισσότερες, κάνε δεύτερη προσθήκη (π.χ. 201–400).",
      invalidPrefix: (hint: string) => `Άκυρο πρόθεμα. ${hint}`,
      labelHint: "Μόνο γράμματα, αριθμοί, παύλα και κάτω παύλα (π.χ. 12, Αυλή-1).",
      previewSpot: "Προεπισκόπηση",
      showQr: "Προβολή QR",
      hideQr: "Κλείσιμο",
      loadingQr: "Φόρτωση QR…",
      spotTypes: {
        TABLE: "Τραπέζι",
        ROOM: "Δωμάτιο",
        SUNBED: "Ξαπλώστρα",
      } as Record<string, string>,
    },
    waiter: {
      title: "Οθόνες",
      description:
        "Live χάρτης θέσεων, κλήσεις και πάσο — ενημερώνεται αυτόματα. Τα links ρυθμίζονται από Ρυθμίσεις → Services.",
      setupLink: "Ρυθμίσεις → Services",
    },
    billing: {
      title: "Συνδρομή",
      description: "Διαχείριση συνδρομής MenuOS. Οι πληρωμές γίνονται με ασφάλεια online.",
    },
    history: {
      title: "Ιστορικό",
      description:
        "Παραδόσεις πάσου που ολοκληρώθηκαν — χρόνος από «έτοιμο» μέχρι «παρέδωσα», ανά θέση, τμήμα και σερβιτόρο.",
      daysLabel: "Περίοδος",
      days7: "7 ημέρες",
      days30: "30 ημέρες",
      days90: "90 ημέρες",
      filterSpot: "Θέση",
      filterStation: "Τμήμα",
      filterStaff: "Σερβιτόρος",
      filterAll: "Όλα",
      loading: "Φόρτωση...",
      empty: "Δεν υπάρχουν παραδόσεις με αυτά τα φίλτρα.",
      failed: "Δεν φορτώθηκε το ιστορικό. Δοκίμασε ξανά.",
      colSpot: "Θέση",
      colStation: "Τμήμα",
      colMessage: "Σχόλιο",
      colReady: "Έτοιμο",
      colDuration: "Διάρκεια",
      colStaff: "Σερβιτόρος",
      colDelivered: "Παρέδωσε",
    },
    settings: {
      title: "Ρυθμίσεις",
      description: "Λογαριασμός, προσωπικό, τμήματα και ταμπλό.",
      tabs: {
        general: "Γενικά",
        services: "Services",
        kitchen: "Κουζίνα",
        bar: "Μπαρ",
        tables: "Ταμπλό",
      },
      demoBadge: "Δείγμα — για δοκιμές UI",
      personnel: {
        title: "Services",
        description:
          "Κάθε μέλος έχει δικό του link σερβιτόρου — μοιράστε το στο κινητό/tablet του. Τα τμήματα φιλτράρουν ποιες ειδοποιήσεις πάσου βλέπει.",
        addTitle: "Νέο μέλος",
        addStaff: "Προσθήκη",
        listTitle: "Ομάδα",
        editTitle: "Επεξεργασία μέλους",
        cancelEdit: "Άκυρο",
        stationsHint: "Ποιες ειδοποιήσεις βλέπει στο κινητό/tablet — Services = κλήσεις πελάτη + όλα τα πάσο.",
        saving: "Αποθήκευση...",
        colName: "Όνομα",
        colRole: "Ρόλος",
        colStations: "Τμήματα",
        colLink: "Σύνδεσμος σερβιτόρου",
        colLinkHint: "Στείλτε το στο κινητό του — άνοιγμα χωρίς login.",
        colActions: "",
        viewLink: "Προβολή",
        copyLink: "Αντιγραφή",
        copied: "Αντιγράφηκε!",
        rotateLink: "Νέο link",
        rotateConfirm: (name: string) =>
          `Νέο link για «${name}»; Το παλιό θα σταματήσει να λειτουργεί.`,
        sharedLinkTitle: "Κοινό link (όλο το προσωπικό)",
        sharedLinkOptional: "προαιρετικό",
        sharedLinkHint: "Backup — όλοι βλέπουν όλες τις κλήσεις και τα πάσο. Προτιμήστε προσωπικό link ανά άτομο.",
        namePlaceholder: "π.χ. Μαρία Π.",
        rolePlaceholder: "π.χ. Σερβιτόρος",
        loading: "Φόρτωση...",
        empty: "Δεν έχεις προσθέσει προσωπικό ακόμα.",
        deleteConfirm: (name: string) =>
          `Διαγραφή του «${name}»;\n\nΤο προσωπικό link θα σταματήσει. Η ενέργεια δεν αναιρείται.`,
        deleteTitle: "Διαγραφή προσωπικού",
        edit: "Επεξεργασία",
        delete: "Διαγραφή",
        saveEdit: "Αποθήκευση",
        stationLabels: {
          services: "Services",
          kitchen: "Κουζίνα",
          bar: "Μπαρ",
          cold: "Κρύα",
          dessert: "Γλυκά",
          all: "Όλα",
        },
      },
      kitchen: {
        title: "Κουζίνα",
        description: "Οθόνη για τον μάγειρα — στέλνει «έλα πάσο» στον σερβιτόρο.",
        screenLink: "Link οθόνης κουζίνας",
        screenHint: "Άνοιξε σε tablet στην κουζίνα — χωρίς login dashboard.",
        sampleTable: "Τραπέζι",
        sampleComment: "Σχόλιο (π.χ. ξέχασες τον πάγο)",
        sampleCommentPlaceholder: "ξέχασες τον πάγο",
        sampleSend: "Έτοιμο στο πάσο",
        openScreen: "Άνοιγμα οθόνης",
        copyScreenLink: "Αντιγραφή link",
      },
      kitchenTab: {
        title: "Οθόνες κουζίνας",
        description:
          "Κάθε οθόνη ανοίγει σε tablet — χωρίς login. Ο μάγειρας πατά «Έτοιμο» και ειδοποιείται ο σερβιτόρος.",
        steps:
          "Άνοιξε την οθόνη στο tablet της κουζίνας\nΑντιγράψε το link ή πάτα «Άνοιγμα οθόνης»\nΓια 2η κουζίνα/ζώνη: πρόσθεσε νέα οθόνη με όνομα (π.χ. Παραλία)",
      },
      bar: {
        title: "Μπαρ",
        description: "Οθόνη για το μπαρ — ειδοποίηση σερβιτόρου όταν είναι έτοιμο το ποτό.",
        screenLink: "Link οθόνης μπαρ",
        screenHint: "Γρήγορες ενέργειες για tablet στο μπαρ.",
        sampleSend: "Έτοιμο το ποτό",
        openScreen: "Άνοιγμα οθόνης",
        copyScreenLink: "Αντιγραφή link",
      },
      barTab: {
        title: "Οθόνες μπαρ & γλυκών",
        description:
          "Ίδια λογική με την κουζίνα — tablet στο μπαρ ή στο πάσο γλυκών, χωρίς login.",
        steps:
          "Άνοιξε την οθόνη στο tablet του μπαρ\nΓια 2ο μπαρ (π.χ. παραλία): πρόσθεσε νέα οθόνη\nΤα γλυκά μπορούν να έχουν ξεχωριστή οθόνη",
      },
      cold: {
        title: "Κρύα κουζίνα",
        description: "Σαλάτες και ορεκτικά κρύα — ξεχωριστή οθόνη αν τη χρησιμοποιείτε.",
        screenLink: "Link οθόνης κρύας",
        screenHint: "Tablet στην κρύα κουζίνα — χωρίς login dashboard.",
        openScreen: "Άνοιγμα οθόνης",
        copyScreenLink: "Αντιγραφή link",
      },
      dessert: {
        title: "Γλυκά",
        description: "Ειδοποίηση σερβιτόρου όταν είναι έτοιμο το επιδόρπιο.",
        screenLink: "Link οθόνης γλυκών",
        screenHint: "Tablet στο πάσο γλυκών ή δίπλα στο μπαρ.",
        openScreen: "Άνοιγμα οθόνης",
        copyScreenLink: "Αντιγραφή link",
      },
      rotateScreenButton: "Νέος κωδικός οθόνης",
      rotatingScreen: "Αλλαγή...",
      rotateScreenConfirm:
        "Να αλλάξει ο κωδικός; Το τρέχον link θα σταματήσει να λειτουργεί.",
      rotateScreenFailed: "Αποτυχία αλλαγής κωδικού οθόνης.",
      multiScreenHint:
        "Μπορείς να έχεις πολλές οθόνες ανά τμήμα (π.χ. μπαρ παραλίας και μπαρ καταστήματος) — κάθε μία με δικό της link.",
      loadingScreens: "Φόρτωση οθονών…",
      screensEmpty: "Δεν υπάρχουν οθόνες ακόμα — πρόσθεσε μία παρακάτω.",
      showLink: "Δες link",
      hideLink: "Κρύψε link",
      allTablesZone: "Όλα τα τραπέζια / ξαπλώστρες / δωμάτια",
      addScreenFor: (dept: string) => `Νέα οθόνη — ${dept}`,
      addScreenTitle: "Προσθήκη οθόνης",
      addScreenHint: "Όνομα για να ξεχωρίζει (π.χ. Παραλία, Σαλόνι).",
      screenNameLabel: "Όνομα οθόνης",
      screenNamePlaceholder: "π.χ. Παραλία",
      screenSpotPrefixLabel: "Ζώνη (προαιρετικό)",
      screenSpotPrefixPlaceholder: "π.χ. Αυλή",
      screenSpotPrefixHint:
        "Κενό = όλα τα τραπέζια, ξαπλώστρες και δωμάτια. «Σαλόνι» = μόνο αριθμητικά (1, 2, 3…). Άλλο πρόθεμα = μόνο τραπέζια με αυτό το prefix (π.χ. Αυλή-1).",
      screenSpotPrefixHintShort:
        "Άδειο πεδίο = όλα. «Σαλόνι» = μόνο αριθμητικά τραπέζια. «Αυλή» = μόνο Αυλή-1, Αυλή-2…",
      screenSpotPrefixActive: (prefix: string) => `Μόνο τραπέζια: ${prefix}-*`,
      addScreenButton: "Προσθήκη",
      addingScreen: "Προσθήκη…",
      addScreenFailed: "Αποτυχία προσθήκης οθόνης.",
      deleteScreen: "Διαγραφή",
      deleteScreenTitle: "Διαγραφή οθόνης",
      deleteScreenConfirm: (name: string) =>
        `Διαγραφή της οθόνης «${name}»;\n\nΤο link θα σταματήσει να λειτουργεί. Η ενέργεια δεν αναιρείται.`,
      deleteScreenFailed: "Αποτυχία διαγραφής οθόνης.",
      renameScreen: "Μετονομασία",
      saveScreen: "Αποθήκευση",
      savingScreen: "Αποθήκευση…",
      cancelScreenEdit: "Άκυρο",
      renameScreenFailed: "Αποτυχία μετονομασίας.",
      screenNameTaken: "Υπάρχει ήδη οθόνη με αυτό το όνομα.",
      tables: {
        title: "Ταμπλό",
        description: "Ρύθμισε τραπέζια, δωμάτια και ξαπλώστρες. Τα QR κατεβαίνουν από τη σελίδα QR codes.",
        gridPreview: "Χρώματα χάρτη θέσεων",
        gridHint: "Κάθε χρώμα στο ταμπλό σερβιτόρου δείχνει τι συμβαίνει στο τραπέζι.",
        qrLink: "Λήψη QR codes →",
        yourVenueSpots: (name: string, count: number) => `${name} — ${count} θέσεις`,
      },
      services: {
        title: "Υπηρεσίες",
        description: "Link σερβιτόρου, push ειδοποιήσεις και live πάσα — κλήσεις πελάτη + μηνύματα τμημάτων.",
        pushSectionTitle: "Push ειδοποιήσεις",
        pushHint:
          "Ενεργοποίησε push σε αυτή τη συσκευή (π.χ. tablet manager). Ισχύει για όλα τα καταστήματα της επιχείρησης — Chrome/Safari, όχι Messenger ή Instagram.",
        staffPushHint:
          "Κάθε σερβιτόρος ενεργοποιεί push στο δικό του κινητό — ανοίγει το προσωπικό link και πατά «Ενεργοποίηση».",
        passTitle: "Live πάσα",
        passHint: "Μένει μέχρι ο σερβιτόρος πατήσει «Έτοιμο». Ο χάρτης θέσεων ενημερώνεται live.",
        livePanelLink: "Άνοιγμα live οθονών →",
        historyLink: "Ιστορικό παραδόσεων →",
        staffLinksHint: "Links σερβιτόρων: Ρυθμίσεις → Services (ένα link ανά άτομο).",
        minutesAgo: (n: number) => `πριν ${n} λεπ.`,
        tableLabel: (n: string) => `Τραπέζι ${n}`,
        historyTitle: "Ιστορικό πάσου",
        historyHint: "Παραδόσεις που ολοκληρώθηκαν — χρόνος από «έτοιμο» μέχρι «παρέδωσα».",
        historyDaysLabel: "Περίοδος",
        historyDays7: "7 ημέρες",
        historyDays30: "30 ημέρες",
        historyDays90: "90 ημέρες",
        historyLoading: "Φόρτωση...",
        historyEmpty: "Δεν υπάρχουν παραδόσεις σε αυτή την περίοδο.",
        historyFailed: "Δεν φορτώθηκε το ιστορικό. Δοκίμασε ξανά.",
        historyColSpot: "Θέση",
        historyColStation: "Τμήμα",
        historyColMessage: "Σχόλιο",
        historyColReady: "Έτοιμο",
        historyColDuration: "Διάρκεια",
      },
      nameLabel: "Όνομα",
      roleLabel: "Ρόλος",
      save: "Αποθήκευση ρυθμίσεων",
      saving: "Αποθήκευση...",
      appearanceTitle: "Εμφάνιση καταλόγου",
      appearanceDesc: "Logo, χρώματα και στοιχεία που βλέπουν οι πελάτες από το QR.",
      venueNameLabel: "Όνομα καταστήματος",
      descriptionLabel: "Περιγραφή",
      primaryColor: "Κύριο χρώμα",
      secondaryColor: "Δευτερεύον",
      needVenueFirst: "Φτιάξε πρώτα κατάστημα για να ρυθμίσεις χρώματα και εμφάνιση.",
    },
    newVenue: {
      title: "Νέο κατάστημα",
      description: "Το εστιατόριο, bar ή ξενοδοχείο σου. Θα δημιουργηθεί αυτόματα ο πρώτος κατάλογος.",
      nameLabel: "Όνομα καταστήματος *",
      descriptionLabel: "Περιγραφή (προαιρετικό)",
      submit: "Δημιουργία καταστήματος",
      submitting: "Δημιουργία...",
    },
  },
  onboarding: {
    guideLabel: "Οδηγός εκκίνησης",
    stepTitle: (step: number) => `Βήμα ${step} από 3 — φτιάξε τον κατάλογο σου`,
    subtitle: "Σε λιγότερο από μία ώρα μπορείς να έχεις QR menu στα τραπέζια σου.",
    completed: (n: number) => `${n}/3 ολοκληρωμένα`,
    done: "Έτοιμο",
    pending: "Σε αναμονή",
    previewIntro: "Δες πώς φαίνεται στους πελάτες:",
    openCatalog: "Άνοιγμα καταλόγου",
    steps: {
      venue: {
        title: "Φτιάξε το κατάστημά σου",
        desc: "Το εστιατόριο, το bar ή το ξενοδοχείο σου — π.χ. «Marine Hotel» ή «Ταβέρνα του Γιώργου».",
      },
      menu: {
        title: "Βάλε είδη στον κατάλογο",
        descWithCategory: "Πρόσθεσε είδη χειροκίνητα ή κάνε εισαγωγή από PDF αν έχεις Pro.",
        descWithoutCategory:
          "Φτιάξε κατηγορίες (Σαλάτες, Κυρίαρκα, Ποτά...) και βάλε τιμές και φωτογραφίες.",
      },
      qr: {
        title: "Βγάλε QR για τα τραπέζια",
        desc: "Κατέβασε QR codes, τύπωσέ τα ή βάλτα σε stand. Οι πελάτες σκανάρουν και βλέπουν τον κατάλογο.",
      },
    },
  },
  overview: {
    titleFallback: "Επισκόπηση",
    heroEyebrow: "Επισκόπηση",
    metricsTitle: "Στατιστικά",
    addFirstVenue: "Πρόσθεσε το πρώτο",
    addToCatalog: "Πρόσθεσε στον κατάλογο",
    quickActions: "Γρήγορες ενέργειες",
    actionVenue: "Ρύθμισε το κατάστημά σου",
    actionCatalog: "Είδη, τιμές & κατηγορίες",
    actionQr: "QR για τραπέζια & δωμάτια",
    actionScreens: "Κλήσεις πελάτη & live πάσο",
    actionPreview: "Όπως το βλέπει ο πελάτης",
    actionHistory: "Ιστορικό παραδόσεων πάσου",
    actionBilling: "Πλάνο & συνδρομή",
    quickStartEmpty:
      "Ξεκίνα προσθέτοντας κατηγορίες και είδη — μετά βγάλε QR για τα τραπέζια σου.",
    quickStartReady: "Ο κατάλογος σου είναι online! Βγάλε QR ή δες τις κλήσεις από πελάτες.",
    callsWaiterSuffix: "σερβιτόρου",
    renewalUntil: "Ανανέωση έως",
    planField: "Πλάνο",
    catalogOne: "κατάλογος",
    catalogMany: "κατάλογοι",
    passToday: "Πάσο σήμερα",
    passTodayHint: "Ειδοποιήσεις από κουζίνα/μπαρ",
    passAvgDelivery: "Μέσος χρόνος παραλαβής",
    passAvgDeliveryHint: "Έτοιμο → παραδόθηκε, τελευταίες 7 ημέρες",
    passAvgNone: "—",
    passAvgMinutes: (n: number) => `${n} λεπ.`,
    planSummary: (plan: string, venueN: number, venueWord: string, menuN: number, menuWord: string, items: string) =>
      `Πλάνο: ${plan} · ${venueN} ${venueWord} · ${menuN} ${menuWord} · ${items}`,
  },
  menuEditor: {
    noVenueTitle: "Δεν έχεις ακόμα κατάστημα",
    noVenueDesc:
      "Πρώτα φτιάξε το κατάστημά σου (εστιατόριο, bar ή ξενοδοχείο) και μετά πρόσθεσε είδη στον κατάλογο.",
    categoryNew: "Νέα κατηγορία",
    categoryHint: "Μόνο ελληνικά — EN / DE / FR δημιουργούνται αυτόματα για το QR menu",
    addCategory: "Προσθήκη κατηγορίας",
    addingCategory: "Προσθήκη...",
    categoryLabel: "Κατηγορία",
    renameCategory: "Μετονομασία κατηγορίας",
    deleteEmptyCategory: "Διαγραφή κενής κατηγορίας",
    deleteCategoryConfirm: "Διαγραφή της κατηγορίας;\n\nΕίσαι σίγουρος; Η ενέργεια δεν αναιρείται.",
    invalidPrice: "Βάλε έγκυρη τιμή (π.χ. 4.50).",
    categoryNameRequired: "Βάλε όνομα κατηγορίας.",
    loadingSubtitle: "Φόρτωση κατηγοριών και ειδών",
    syncCatalogHint: "Ίδια επιλογή και στην εισαγωγή PDF — τα είδη εμφανίζονται εδώ.",
    editPrice: "Αλλαγή τιμής",
    qrBadge: "Ετικέτα στο QR menu",
    active: "Ενεργό",
    inactive: "Ανενεργό",
    remove: "Αφαίρεση",
    saving: "Αποθήκευση...",
    emptyCategories: "Δεν υπάρχουν κατηγορίες. Πρόσθεσε την πρώτη παραπάνω για να ξεκινήσεις.",
    autoTranslateHint: "Μόνο ελληνικά — EN / DE / FR δημιουργούνται αυτόματα για το QR menu",
    qrExtrasTitle: "Επιλογές πελάτη",
    qrExtrasHint:
      "Ο πελάτης τις επιλέγει στο QR menu. Προαιρετικά βάλε extra χρέωση (π.χ. +€1,50).",
    qrExtrasCount: (n: number) => `${n} επιλογές QR`,
    noBadge: "Χωρίς ετικέτα",
    extraChargePlaceholder: "Extra χρέωση (προαιρετικό)",
    addExtraOption: "Προσθήκη επιλογής",
    cancel: "Ακύρωση",
  },
  flash: {
    close: "Κλείσιμο",
    genericError: "Κάτι πήγε στραβά.",
    success: "Επιτυχία!",
    codes: {
      subscription_inactive: "Η συνδρομή σου δεν είναι ενεργή. Αναβάθμισε για να συνεχίσεις.",
      trial_expired: "Η δοκιμαστική περίοδος έληξε.",
      unauthorized: "Συνδέσου ξανά.",
      forbidden: "Δεν έχεις δικαίωμα.",
      venue_limit: "Έφτασες το όριο καταστημάτων του πλάνου σου. Δες τα πλάνα στη Συνδρομή.",
      menu_limit: "Έφτασες το όριο καταλόγων του πλάνου σου.",
      item_limit: "Έφτασες το όριο ειδών του πλάνου σου.",
      not_found: "Δεν βρέθηκε.",
      enterprise_contact: "Επικοινώνησε μαζί μας για Enterprise τιμολόγηση.",
      stripe_not_configured: "Το σύστημα πληρωμών δεν είναι διαθέσιμο.",
      rate_limited: "Πολλές προσπάθειες. Δοκίμασε αργότερα.",
      bad_request: "Λάθος αίτημα.",
      invalid_input: "Μη έγκυρα στοιχεία.",
      password_mismatch: "Ο νέος κωδικός και η επιβεβαίωση δεν ταιριάζουν.",
      password_same: "Ο νέος κωδικός πρέπει να διαφέρει από τον τρέχοντα.",
      invalid_password: "Ο νέος κωδικός πρέπει να έχει τουλάχιστον 8 χαρακτήρες.",
      wrong_password: "Ο τρέχων κωδικός είναι λάθος.",
      slug_exists: "Το slug υπάρχει ήδη. Δοκίμασε άλλο όνομα.",
    } as Record<string, string>,
  },
  meta: {
    appSuffix: "MenuOS",
    overview: "Επισκόπηση",
    menus: "Κατάλογος",
    import: "Εισαγωγή από PDF",
    qr: "QR Codes",
    waiter: "Οθόνες",
    history: "Ιστορικό",
    billing: "Συνδρομή",
    settings: "Ρυθμίσεις",
    newVenue: "Νέο κατάστημα",
  },
  api: {
    badRequest: "Λάθος αίτημα.",
    invalidData: "Μη έγκυρα στοιχεία.",
    menuNotFound: "Ο κατάλογος δεν βρέθηκε.",
    venueNotFound: "Το κατάστημα δεν βρέθηκε.",
    categoryNotFound: "Η κατηγορία δεν βρέθηκε.",
    fillNameAndPrice: "Συμπλήρωσε όνομα και τιμή.",
    fillCategoryNameGr: "Συμπλήρωσε όνομα κατηγορίας (Ελληνικά).",
    invalidCategoryName: "Μη έγκυρο όνομα κατηγορίας.",
    categoryAdded: (name: string) => `Η κατηγορία «${name}» προστέθηκε.`,
    categoryRenamed: (name: string) => `Η κατηγορία μετονομάστηκε σε «${name}».`,
    categoryUpdated: "Η κατηγορία ενημερώθηκε.",
    categoryDeleted: "Η κατηγορία διαγράφηκε.",
    menuDeleted: "Ο κατάλογος διαγράφηκε.",
    allMenusDeleted: (stats: { menus: number; items: number }) =>
      stats.items > 0
        ? `Διαγράφηκαν ${stats.menus} κατάλογοι και ${stats.items} είδη. Έμεινε ένας κενός κατάλογος.`
        : `Διαγράφηκαν ${stats.menus} κατάλογοι. Έμεινε ένας κενός κατάλογος.`,
    venueSaved: "Οι ρυθμίσεις αποθηκεύτηκαν.",
    venueCreated: "Το κατάστημα δημιουργήθηκε! Πρόσθεσε τώρα κατηγορίες και είδη.",
    menuCreated: "Ο κατάλογος δημιουργήθηκε.",
    venueIdRequired: "Απαιτείται venueId.",
    invalidMenuData: "Μη έγκυρα στοιχεία καταλόγου.",
    slugExists: "Το slug υπάρχει ήδη. Δοκίμασε άλλο όνομα.",
    defaultMenuName: "Κύριος κατάλογος",
    spotAdded: "Η θέση προστέθηκε.",
    spotExists: "Η θέση υπάρχει ήδη.",
    spotsBulkAdded: (n: number) => `Προστέθηκαν ${n} θέσεις.`,
    import: {
      invalidDraft: "Έλεγξε κατηγορίες, ονόματα και τιμές πριν την εισαγωγή.",
      selectMenu: "Επίλεξε κατάλογο.",
      selectAtLeastOne: (one: string) => `Επίλεξε τουλάχιστον ένα ${one}.`,
      parseFound: (items: string, categories: number) =>
        `Βρέθηκαν ${items} σε ${categories} κατηγορίες. Έλεγξέ τα πριν την εισαγωγή.`,
      parseEmpty: (many: string) => `Δεν βρέθηκαν ${many} — δοκίμασε άλλο PDF ή πρόσθεσε χειροκίνητα.`,
      parseFailed: "Αποτυχία ανάγνωσης PDF. Δοκίμασε ξανά ή πρόσθεσε τον κατάλογο χειροκίνητα.",
      applySuccess: (items: string, categories: number) =>
        `Εισήχθησαν ${items} σε ${categories} κατηγορίες. Μπορείς να τα επεξεργαστείς (φωτο, τιμές) από τον κατάλογο.`,
    },
    pdf: {
      noFiles: "Επίλεξε τουλάχιστον ένα PDF.",
      tooMany: (max: number) => `Μέγιστο ${max} PDF ανά φορά.`,
      notPdf: (name: string) => `Το «${name}» δεν είναι PDF.`,
      tooLarge: (name: string) => `Το «${name}» είναι πολύ μεγάλο (max 10MB).`,
      readFailed: (name: string) =>
        `Αδυναμία ανάγνωσης «${name}». Το αρχείο μπορεί να είναι κλειδωμένο ή κατεστραμμένο.`,
      noText: (name: string, pageHint: string, ocrHint: string) =>
        `Το «${name}» δεν έδωσε αναγνωρίσιμο κείμενο${pageHint}.${ocrHint}`,
      ocrNoText: " Το OCR δεν βρήκε κείμενο — δοκίμασε άλλες σελίδες ή χειροκίνητη εισαγωγή.",
      ocrNotConfigured: " Βάλε OCR_SPACE_API_KEY στο server για σαρωμένα PDF.",
      noPagesSelectedOcr:
        "Δεν βρέθηκε κείμενο στις επιλεγμένες σελίδες. Δοκίμασε «Προχωρημένα → Επιλογή σελίδων».",
      noPagesSelectedNoOcr: "Δεν βρέθηκε digital κείμενο. Ρύθμισε OCR_SPACE_API_KEY για σαρωμένα PDF.",
      pagesHint: (pages: number[]) => ` (σελίδες ${pages.join(", ")})`,
    },
  },
  subscriptionStatus: {
    TRIALING: "Δοκιμή",
    ACTIVE: "Ενεργή",
    PAST_DUE: "Καθυστέρηση πληρωμής",
    CANCELED: "Ακυρωμένη",
    trialActive: "Ενεργή δοκιμή",
    trialExpired: "Ληγμένη",
    expiresOn: (date: string) => `Λήγει ${date}`,
    renewsOn: (date: string) => `Ανανέωση ${date}`,
    expiredOn: (date: string) => `Έληξε ${date}`,
  },
} as const;

export function planLabel(planId: string): string {
  return DASHBOARD_EL.planLabels[planId] ?? planId;
}

export function roleLabel(role: string): string {
  return DASHBOARD_EL.roleLabels[role] ?? role;
}
