/** Ανθρώπινα ελληνικά για το panel διαχείρισης — χωρίς τεχνικούς όρους. */
export const DASHBOARD_EL = {
  venue: "Κατάστημα",
  venues: "Καταστήματα",
  menu: "Κατάλογος",
  menus: "Κατάλογοι",
  qrCodes: "QR codes",
  subscription: "Συνδρομή",
  logout: "Αποσύνδεση",
  calls: "Κλήσεις",
  settings: "Ρυθμίσεις",
  account: "Λογαριασμός",
  accountEmail: "Email σύνδεσης",
  changePassword: {
    title: "Αλλαγή κωδικού",
    current: "Τρέχων κωδικός",
    new: "Νέος κωδικός (min 8)",
    confirm: "Επιβεβαίωση νέου κωδικού",
    submit: "Αποθήκευση κωδικού",
    saving: "Αποθήκευση…",
    success: "Ο κωδικός άλλαξε.",
  },
  addVenue: "Προσθήκη καταστήματος",
  confirmDialog: {
    close: "Κλείσιμο",
    cancel: "Ακύρωση",
    confirmDelete: "Διαγραφή",
    confirmContinue: "Συνέχεια",
  },
  editCatalog: "Επεξεργασία καταλόγου",
  livePreview: "Δες πώς φαίνεται",
  importPdf: "Εισαγωγή από PDF",
  importPdfButton: "Εισαγωγή PDF",
  importPdfPro: "Εισαγωγή PDF (μόνο Pro)",
  loadingCatalog: "Φόρτωση καταλόγου...",
  importWizard: {
    hint: "Ανέβασε PDF καταλόγου — digital + OCR. Βλέπεις αναφορά πριν την εισαγωγή.",
    hintWithGemini:
      "Ανέβασε PDF — OCR, layout και μετάφραση με Gemini AI. Έλεγχος πριν την εισαγωγή.",
    geminiBadge: "Με Gemini AI",
    geminiPoweredSubtitle: "Layout, OCR και ελληνικά ονόματα με Gemini AI",
    geminiProcessingDetail: "Gemini AI: layout, OCR & μετάφραση…",
    geminiStepDone: "Ολοκληρώθηκε",
    analyzeButtonAi: "Ανάλυση με Gemini AI",
    processingTitleGemini: "Ανάλυση με Gemini AI",
    processingTimerSeconds: (n: number) => `${n} δευτ.`,
    processingTimerMinutes: (m: number, s: number) => `${m}:${String(s).padStart(2, "0")}`,
    processingTimerHint: "Συνήθως 30–90 δευτ. · μεγάλα PDF έως 3 λεπτά",
    processingLongWaitHint:
      "Ακόμα δουλεύει — μεγάλο ή σαρωμένο PDF. Μην κλείσεις τη σελίδα.",
    processingActivity: {
      scan: [
        "Άνοιγμα PDF…",
        "Σάρωση σελίδων…",
        "Παράλειψη cover & logo…",
        "Εντοπισμός σελίδων μενού…",
      ],
      extract: [
        "Ανάγνωση κειμένου…",
        "Αναγνώριση στηλών & τιμών…",
        "OCR σε σαρωμένες σελίδες…",
        "Έλεγχος layout καταλόγου…",
      ],
      extractGemini: [
        "Gemini AI: ανάγνωση layout…",
        "OCR & ψηφιακό κείμενο…",
        "Εντοπισμός πιάτων & τιμών…",
        "Έλεγχος δομής σελίδας…",
      ],
      ai: [
        "Μετάφραση ονομάτων στα ελληνικά…",
        "Έλεγχος λatin-only ονομάτων…",
        "Gemini AI: κατηγορίες & περιγραφές…",
        "Τελικός έλεγχος μετάφρασης…",
      ],
      parse: [
        "Ομαδοποίηση κατηγοριών…",
        "Έλεγχος τιμών & νομισμάτων…",
        "Έλεγχος διπλότυπων…",
        "Σύνταξη προσχεδίου εισαγωγής…",
      ],
    } as Record<string, string[]>,
    processFlow: {
      scan: "Σάρωση",
      analyze: "Ανάλυση",
      report: "Αναφορά",
      review: "Έλεγχος",
    },
    analyzeButton: "Ανάλυση & προεπισκόπηση",
    processingTitle: "Ανάλυση PDF καταλόγου",
    processingTargetCatalog: (name: string) => `Στόχος: κατάλογος «${name}»`,
    processingTargetFull: (venue: string, catalog: string) =>
      `Στόχος: ${venue} · κατάλογος «${catalog}»`,
    pipeline: {
      scan: "Σάρωση PDF",
      extract: "Ανάλυση σελίδων",
      extractWithGemini: "OCR & Gemini AI",
      ai: "Gemini AI",
      ocr: "OCR εικόνων",
      parse: "Κατηγορίες & είδη",
      done: "Έτοιμο",
    },
    loadingScanFile: (file: string, page: number, total: number) =>
      `${file} — σελίδα ${page}/${total}`,
    loadingImport: "Εισαγωγή στον κατάλογο...",
    loadingImportInto: (name: string) => `Εισαγωγή στον κατάλογο «${name}»…`,
    advancedTitle: "Προχωρημένα — επιλογή σελίδων",
    advancedHint:
      "Cover/logo παραλείπονται αυτόματα. Άλλαξε ποιες σελίδες μπαίνουν στην ανάλυση αν κάτι λείπει.",
    pageKind: {
      digital: "Digital",
      scan: "OCR",
      cover: "Cover",
    },
    skipCoverFirst: "Cover / logo — παραλείπεται αυτόματα",
    skipCoverLast: "Τελευταία σελίδα — πιθανό back cover",
    skipLowText: "Λίγο ή καθόλου κείμενο",
    skipBanner: "Πρώτη σελίδα — banner/logo",
    skipScan: "Εικόνα/σάρωση — OCR",
    selectMenuPages: "Μόνο μενού",
    selectAll: "Όλες",
    deselectAll: "Καμία",
    reanalyze: "Ξανά ανάλυση",
    visionRetrying: "Ανάλυση με AI…",
    visionRetrySuccess: "Η ανάλυση με AI ολοκληρώθηκε — έλεγξε τα αποτελέσματα.",
    visionRetryNoImprovement:
      "Η AI ανάλυση δεν βελτίωσε το αποτέλεσμα — έλεγξε χειροκίνητα ή άλλες σελίδες.",
    visionRetryConfirm:
      "Η AI ανάλυση θα αντικαταστήσει το προσχέδιο (ονόματα, τιμές, επιλογές). Να συνεχίσω;",
    translateRetrying: "Μετάφραση στα ελληνικά…",
    translateSuccess: (n: number) =>
      n === 1
        ? "Μεταφράστηκε 1 όνομα στα ελληνικά — έλεγξε τα αποτελέσματα."
        : `Μεταφράστηκαν ${n} ονόματα στα ελληνικά — έλεγξε τα αποτελέσματα.`,
    translateConfirm:
      "Η AI θα μεταφράσει τα αγγλικά ονόματα σε ελληνικά (κατηγορίες και είδη). Να συνεχίσω;",
    ocrUsed: (n: number) =>
      n === 1 ? "1 σελίδα μέσω OCR" : `${n} σελίδες μέσω OCR`,
    badge: "IMPORT ΑΠΟ PDF",
    phaseUpload: "Ανέβασμα PDF",
    phaseReview: "Αναφορά & έλεγχος πριν την εισαγωγή",
    needVenueTitle: "Χρειάζεσαι κατάστημα πρώτα",
    selectCatalogAndPdf: "Επίλεξε κατάλογο και τουλάχιστον ένα PDF.",
    activeCatalogTitle: "Στόχος εισαγωγής",
    activeCatalogHint:
      "Ο ίδιος κατάλογος με τη σελίδα Κατάλογοι — ό,τι εισάγεις από PDF θα μπει εδώ.",
    importTargetConfirm: (name: string) => `Τα είδη θα εισαχθούν στον κατάλογο «${name}».`,
    changeCatalogConfirm: (name: string) =>
      `Αλλαγή στόχου σε «${name}»;\n\nΤα είδη του PDF θα εισαχθούν στον νέο κατάλογο — όχι στον προηγούμενο.`,
    noMenuPagesScanDetail: "Δεν βρέθηκαν σελίδες μενού",
    noMenuPages: "Δεν βρέθηκαν σελίδες μενού. Άνοιξε «Προχωρημένα» και επίλεξε σελίδες χειροκίνητα.",
    extractDetail: "Digital + OCR…",
    parseFailed: "Αποτυχία ανάλυσης. Δοκίμασε ξανά ή μικρότερο PDF.",
    previewPagesFirst: (btn: string) =>
      `Πάτα «${btn}» πρώτα για preview σελίδων — ή ξανατρέξε ανάλυση.`,
    pageStats: (selected: number, digital: number, ocr: number, cover: number) =>
      `${selected} επιλεγμένες · ${digital} digital · ${ocr} OCR · ${cover} cover`,
    pageAlt: (page: number) => `Σελίδα ${page}`,
    pageNumber: (page: number, total: number) => `Σελ. ${page}/${total}`,
    pdfFilesTitle: "PDF αρχεία (έως 10)",
    pdfFilesHint:
      "Digital PDF και σαρωμένες εικόνες (OCR). Cover/logo παραλείπονται αυτόματα.",
    dropzoneTitle: "Επίλεξε ή σύρε PDF εδώ",
    dropzoneHint: "Max 10MB ανά αρχείο",
    reviewSummary: (categories: number, itemsSelected: string) =>
      `${categories} κατηγορίες · ${itemsSelected} επιλεγμένα`,
    reviewMeta: (files: number, withPrice: number, without: number) =>
      `Από ${files} PDF · ${withPrice} τιμές · ${without} χωρίς τιμή`,
    newAnalysis: "Νέα ανάλυση",
    afterImportHint:
      "Μετά την εισαγωγή, άνοιξε τον κατάλογο για φωτο, τιμές και διαθεσιμότητα.",
    importButton: (itemsSelected: string) => `Εισαγωγή ${itemsSelected}`,
    manualEditLink: "← Χειροκίνητη επεξεργασία καταλόγου",
    tableColItemGr: "Είδος (GR)",
    tableColEn: "EN",
    tableColPrice: "Τιμή €",
    tableColNotes: "Σημειώσεις",
    selectMinOneItem: (one: string) => `Επίλεξε τουλάχιστον ένα ${one}.`,
    report: {
      title: "Αποτελέσματα ανάλυσης",
      subtitle: "Έλεγξε τι βρήκαμε στο PDF πριν μπουν στον κατάλογο",
      statCategories: "Κατηγορίες",
      statCategoriesSub: (withItems: number, empty: number) =>
        `${withItems} με είδη · ${empty} κενές`,
      statItems: "Είδη",
      statItemsSub: (selected: number) => `${selected} επιλεγμένα για εισαγωγή`,
      statPrices: "Με τιμή",
      statPricesSub: (without: number) =>
        without > 0 ? `${without} χωρίς τιμή — συμπλήρωσέ τες` : "Όλα έχουν τιμή",
      statReady: "Έτοιμο;",
      statReadyYes: "Ναι",
      statReadyNo: "Όχι ακόμα",
      issuesTitle: "Προβλήματα & σημειώσεις",
      issuesNone: "Δεν βρήκαμε σοβαρά προβλήματα — έλεγξε ονόματα και τιμές πριν την εισαγωγή.",
      ocrBadge: (n: number) => (n === 1 ? "1 σελίδα OCR" : `${n} σελίδες OCR`),
      extractionPath: {
        digital: "Digital PDF",
        ocr: "OCR (σάρωση)",
        hybrid: "Hybrid (digital + OCR)",
        vision: "Vision AI",
      },
      visionUsedBadge: (n: number) =>
        n === 1 ? "1 σελίδα Vision AI" : `${n} σελίδες Vision AI`,
      visionHint:
        "Το layout φαίνεται πολύπλοκο — έλεγξε προσεκτικά ή δοκίμασε «Ανάλυση με AI» για καλύτερη ανάγνωση.",
      visionHintUnavailable:
        "Το layout φαίνεται πολύπλοκο — έλεγξε προσεκτικά ονόματα και τιμές πριν την εισαγωγή.",
      visionRetryButton: "Ανάλυση με AI",
      visionRetrying: "Ανάλυση…",
      translateHint:
        "Τα ονόματα είναι στα αγγλικά — πάτα «Μετάφραση στα ελληνικά» για αυτόματη μετάφραση με AI.",
      translateHintUnavailable:
        "Τα ονόματα φαίνονται στα αγγλικά — συμπλήρωσε τα ελληνικά χειροκίνητα. Η αυτόματη μετάφραση AI δεν είναι ακόμα ενεργή.",
      translateButton: "Μετάφραση στα ελληνικά",
      translateRetrying: "Μετάφραση…",
      nextStepsTitle: "Τι κάνεις τώρα",
      nextSteps: [
        "Ξετικίνα κατηγορίες ή είδη που δεν θέλεις να μπουν.",
        "Διόρθωσε ονόματα και τιμές στα πεδία — ιδίως όσα είναι κίτρινα.",
        "Όταν είσαι σίγουρος, πάτα «Εισαγωγή στον κατάλογο».",
      ] as string[],
      issueNoItems: "Δεν βρέθηκαν είδη στο PDF.",
      issueNoItemsHint:
        "Δοκίμασε άλλες σελίδες στα Προχωρημένα ή άλλο PDF. Σε σαρωμένα μενού χρειάζεται OCR.",
      issueNoPrice: (n: number) =>
        n === 1 ? "1 είδος χωρίς τιμή." : `${n} είδη χωρίς τιμή.`,
      issueNoPriceHint: "Βάλε τιμή ή άφησέ το €0 — μπορείς να το αλλάξεις μετά στον κατάλογο.",
      issueEmptyCategories: (n: number) =>
        n === 1 ? "1 κενή κατηγορία (χωρίς είδη)." : `${n} κενές κατηγορίες.`,
      issueEmptyCategoriesHint: "Δεν θα εισαχθούν — κρύβονται από προεπιλογή.",
      issueDuplicateCategories: (n: number) =>
        n === 1
          ? "1 κατηγορία με πιθανά διπλότυπα."
          : `${n} κατηγορίες με πιθανά διπλότυπα.`,
      issueItemWarnings: (n: number) =>
        n === 1 ? "1 είδος χρειάζεται έλεγχο." : `${n} είδη χρειάζονται έλεγχο.`,
      issueItemWarningsHint: "Δες τη στήλη «Σημειώσεις» — κίτρινα πεδία τιμής ή σύντομα ονόματα.",
      issueNothingSelected: "Δεν έχεις επιλέξει κανένα είδος.",
      issueNothingSelectedHint: "Τσέκαρε τουλάχιστον ένα είδος ή κατηγορία για εισαγωγή.",
      issueOcr: "Το PDF είναι σαρωμένη εικόνα — χρησιμοποιήθηκε OCR.",
      issueOcrHint:
        "Μπορεί να λείπουν ή να είναι λάθος ονόματα/τιμές. Έλεγξε προσεκτικά πριν την εισαγωγή.",
    },
    editor: {
      toolbarTitle: "Επεξεργασία προσχεδίου",
      toolbarHint:
        "Κάθε μπλοκ είναι μια κατηγορία. Αν το PDF είναι στα αγγλικά, πάτα «Μετάφραση στα ελληνικά» πριν την εισαγωγή.",
      searchPlaceholder: "Αναζήτηση είδους ή κατηγορίας…",
      hideEmpty: "Κρύψε κενές κατηγορίες",
      showIssuesOnly: "Μόνο με θέματα",
      selectAll: "Επιλογή όλων",
      deselectAll: "Αποεπιλογή όλων",
      expandAll: "Άνοιγμα όλων",
      collapseAll: "Κλείσιμο όλων",
      categoryLabel: "Κατηγορία",
      categoryEnLabel: "Κατηγορία στα αγγλικά (μόνο αν υπάρχει στο PDF)",
      uncategorizedHint:
        "Αυτά τα είδη δεν μπήκαν σε ξεχωριστή κατηγορία από το PDF. Μπορείς να τα εισαγάγεις έτσι και να τα μετακινήσεις αργότερα στον κατάλογο.",
      emptyCategory: "Καμία είδος σε αυτή την κατηγορία",
      itemsCount: (selected: number, total: number) => `${selected}/${total} επιλεγμένα`,
      noResults: "Δεν βρέθηκαν κατηγορίες με αυτά τα κριτήρια.",
      itemNameLabel: "Όνομα είδους",
      itemNameEnLabel: "Όνομα στα αγγλικά (μόνο αν υπάρχει στο PDF)",
      addEnglish: "+ Προσθήκη αγγλικών",
      priceLabel: "Τιμή",
      issueBadge: "Έλεγχος",
      includeCategory: "Συμπερίληψη κατηγορίας στην εισαγωγή",
      includeItem: "Συμπερίληψη είδους στην εισαγωγή",
    },
    importConfirmTitle: "Έτοιμος για εισαγωγή",
    importConfirmHint: (categories: number, items: string) =>
      `Θα προστεθούν ${categories} κατηγορίες και ${items} στον κατάλογο που επέλεξες.`,
  },
  previewCatalog: "Προεπισκόπηση",
  newCatalogPlaceholder: "Νέος κατάλογος (π.χ. Pool Bar)",
  addCatalog: "+ Κατάλογος",
  deleteCatalog: "Διαγραφή καταλόγου",
  deleteCatalogHasData: "Δεν μπορείς να διαγράψεις κατάλογο που έχει κατηγορίες ή είδη.",
  deleteCatalogLast: "Πρέπει να υπάρχει τουλάχιστον ένας κατάλογος στο κατάστημα.",
  deleteCatalogConfirm: (name: string) => ({
    variant: "destructive" as const,
    title: `Διαγραφή καταλόγου «${name}»;`,
    note: "Η ενέργεια δεν αναιρείται.",
  }),
  deleteCatalogWithDataConfirm: (
    name: string,
    stats: { categories: number; items: number },
  ) => ({
    variant: "destructive" as const,
    eyebrow: "Προσοχή",
    title: "Μόνιμη διαγραφή",
    description: `Θα διαγραφεί ο κατάλογος «${name}»:`,
    bullets: [
      ...(stats.categories > 0
        ? [
            `${stats.categories} ${stats.categories === 1 ? "κατηγορία" : "κατηγορίες"}`,
          ]
        : []),
      ...(stats.items > 0
        ? [`${stats.items} ${stats.items === 1 ? "είδος" : "είδη"}`]
        : []),
    ],
    note: "Δεν μπορούμε να τα επαναφέρουμε — χάνονται οριστικά.",
  }),
  deleteAllCatalogs: "Διαγραφή όλων των καταλόγων",
  deleteAllCatalogsConfirm: (stats: { menus: number; categories: number; items: number }) => ({
    variant: "destructive" as const,
    eyebrow: "Προσοχή",
    title: "Μόνιμη διαγραφή",
    description: "Θα διαγραφούν όλοι οι κατάλογοι αυτού του καταστήματος:",
    bullets: [
      `${stats.menus} ${stats.menus === 1 ? "κατάλογος" : "κατάλογοι"}`,
      ...(stats.categories > 0
        ? [
            `${stats.categories} ${stats.categories === 1 ? "κατηγορία" : "κατηγορίες"}`,
          ]
        : []),
      ...(stats.items > 0
        ? [`${stats.items} ${stats.items === 1 ? "είδος" : "είδη"}`]
        : []),
    ],
    note: "Δεν μπορούμε να τα επαναφέρουμε — χάνονται οριστικά. Θα μείνει ένας κενός κατάλογος για να ξεκινήσεις από την αρχή.",
  }),
  roleLabels: {
    ADMIN: "Διαχειριστής",
    MANAGER: "Υπεύθυνος",
  } as Record<string, string>,
  planLabels: {
    TRIAL: "Δωρεάν δοκιμή",
    BASIC: "Basic",
    PRO: "Pro",
    ENTERPRISE: "Enterprise",
  } as Record<string, string>,
  billing: {
    checkoutFailed: "Δεν ξεκίνησε η πληρωμή. Δοκίμασε ξανά.",
    cancelled: "Η πληρωμή ακυρώθηκε. Δεν χρεώθηκε τίποτα.",
    confirming: "Επιβεβαιώνουμε την πληρωμή σου...",
    confirmFailed: "Η επιβεβαίωση απέτυχε. Αν χρεωθήκες, στείλε email στο info@qrmenus.info.",
    activated: "Η συνδρομή ενεργοποιήθηκε. Ευχαριστούμε!",
    activatedDev: "Το πλάνο ενεργοποιήθηκε (δοκιμαστική λειτουργία).",
    inactiveTitle: "Χρειάζεται ενεργή συνδρομή",
    inactiveGeneric:
      "Η συνδρομή σου δεν είναι ενεργή. Διάλεξε πλάνο για να συνεχίσουν οι πελάτες σου να βλέπουν τον QR κατάλογο.",
    canceledInactive:
      "Η συνδρομή σου ακυρώθηκε. Διάλεξε ξανά πλάνο — ο κατάλογός σου είναι αποθηκευμένος.",
    staffNoCheckout: "Μόνο διαχειριστής ή υπεύθυνος μπορεί να αλλάξει πλάνο.",
    currentPlan: "Τρέχον πλάνο",
    statusLabel: "Κατάσταση",
    trialUntil: "Δοκιμή έως",
    periodUntil: "Τρέχουσα περίοδος έως",
    perMonth: "/μήνα",
    currentPlanBtn: "Τρέχον πλάνο",
    checkoutLoading: "Μετάβαση...",
    networkError: "Σφάλμα δικτύου",
    enterpriseFallback:
      "Custom domain, white-label και προτεραιότητα υποστήριξης.",
    contactUs: "Γράψε μας στο",
    selectPlan: (name: string) => `Επιλογή ${name}`,
    upgradeTo: (name: string) => `Αναβάθμιση σε ${name}`,
    downgradeTo: (name: string) => `Υποβάθμιση σε ${name}`,
  },
  trial: {
    expired:
      "Έληξε η περίοδος παράτασης. Διάλεξε Basic ή Pro — ο κατάλογός σου είναι αποθηκευμένος και ξανανοίγει αμέσως.",
    endingSoon: (days: number) =>
      days === 1
        ? "Η δωρεάν δοκιμή σου λήγει αύριο. Μετά έχεις 7 μέρες παράτασης για να διαλέξεις πλάνο."
        : `Η δωρεάν δοκιμή σου λήγει σε ${days} μέρες. Μετά έχεις 7 μέρες παράτασης — χωρίς να κλείσει το menu.`,
    bannerHealthy: (days: number, date: string) =>
      `Δωρεάν δοκιμή — ${days} ${days === 1 ? "μέρα" : "μέρες"} απομένουν (έως ${date})`,
    bannerMid: (days: number, date: string) =>
      `Μέσα στη δοκιμή σου — ${days} ${days === 1 ? "μέρα" : "μέρες"} απομένουν (έως ${date})`,
    bannerEnding: (days: number, date: string) =>
      `Η δοκιμή λήγει σύντομα — ${days} ${days === 1 ? "μέρα" : "μέρες"} (έως ${date})`,
    bannerLastDay: "Η δοκιμή σου λήγει αύριο — μετά ακολουθούν 7 μέρες παράτασης",
    bannerGrace: (days: number, date: string) =>
      `Η δοκιμή έληξε — ${days} ${days === 1 ? "μέρα" : "μέρες"} παράτασης (έως ${date})`,
    bannerGraceLastDay: "Τελευταία μέρα παράτασης — διάλεξε πλάνο για να μείνει online το menu",
    graceHint:
      "Ο QR κατάλογος σου συνεχίζει κανονικά. Διάλεξε Basic (€9,99) ή Pro (€19,99) — χωρίς να χάσεις τα πιάτα σου.",
    graceChoosePlan: "Διάλεξε πλάνο",
    graceUntil: (date: string) => `Παράταση έως ${date}`,
    gracePromise: "Μετά τη λήξη της δοκιμής σου δίνουμε 7 μέρες παράτασης — το menu μένει online.",
    setupHint: "1. Κατάστημα · 2. Κατάλογος · 3. QR · 4. Έτοιμο",
    choosePlan: "Δες τα πλάνα",
    upgradeNow: "Αναβάθμιση τώρα",
    welcomeBadge: "Ξεκίνημα δοκιμής",
    welcomeTitle: "Καλώς ήρθες στο MenuOS",
    welcomeEnds: (days: number, date: string) =>
      `Έχεις ${days} ημέρες δωρεάν δοκιμή — λήγει ${date}. Χωρίς κάρτα.`,
    welcomeEmailHint: "Σου στείλαμε email με τα βήματα. Θα λάβεις υπενθύμιση πριν τη λήξη.",
    limits:
      "Στη δοκιμή: 1 κατάστημα, 1 κατάλογος, μέχρι 50 είδη. Μπορείς να αναβαθμιστείς όποτε θες.",
    limitsNear: (count: number) =>
      `Έχεις ${count}/50 είδη στη δοκιμή. Αν χρειάζεσαι περισσότερα, δες τα πλάνα.`,
    limitsNearCta: "Δες τα πλάνα",
    endsOn: "Δοκιμή έως",
  },
  planLimits: {
    seePlans: "Δες τα πλάνα",
    catalogTrial:
      "Στη δωρεάν δοκιμή επιτρέπεται 1 κατάλογος ανά κατάστημα. Για bar, pool κ.λπ. δες Basic ή Pro.",
    catalogBasic: (max: number) =>
      `Το πλάνο Basic επιτρέπει μέχρι ${max} καταλόγους ανά κατάστημα.`,
    catalogGeneric: (planName: string, max: number) =>
      `Το πλάνο ${planName} επιτρέπει μέχρι ${max} καταλόγους ανά κατάστημα.`,
    itemsTrial: "Έφτασες τα 50 είδη της δοκιμής. Αναβάθμισε για απεριόριστα πιάτα.",
    itemsNearTrial: (count: number, max: number) =>
      `Έχεις ${count}/${max} είδη στη δοκιμή — σύντομα θα φτάσεις το όριο.`,
    itemsNearGeneric: (count: number, max: number) =>
      `Έχεις ${count}/${max} είδη — σύντομα θα φτάσεις το όριο του πλάνου σου.`,
    itemsAtLimit: (max: number) => `Έφτασες το όριο των ${max} ειδών του πλάνου σου.`,
    venueTrial: "Στη δωρεάν δοκιμή επιτρέπεται 1 κατάστημα. Αναβάθμισε για περισσότερα.",
    venueAtLimit: (max: number) =>
      `Το πλάνο σου επιτρέπει μέχρι ${max} ${max === 1 ? "κατάστημα" : "καταστήματα"}.`,
  },
  upgrade: {
    pdfImport: {
      title: "Φέρ' το PDF στον κατάλογο σου",
      lead:
        "Στο Pro ανεβάζεις το έντυπο menu — κατηγορίες, είδη και τιμές γεμίζουν σχεδόν μόνα τους. Όταν το PDF είναι σκαν ή μπερδεμένο layout, μπαίνει Gemini AI. Πριν μπουν online, τα ελέγχεις εσύ.",
      geminiBadge: "Gemini AI",
      steps: [
        "Ανεβάζεις PDF — printed ή digital",
        "Gemini AI για σκαν & δύσκολες σελίδες",
        "Διορθώνεις και σώζεις — τίποτα χωρίς OK σου",
      ],
      cta: "Αναβάθμιση σε Pro",
    },
    live360: {
      title: "Live 360° — κουζίνα, bar, σερβιτόροι μαζί",
      lead:
        "Κλήσεις από QR, ζωντανές οθόνες και ιστορικό παραγγελιών τρέχουν στο Pro. Στη δοκιμή και στο Basic δεν είναι διαθέσιμα.",
      steps: [
        "Οι σερβιτόροι βλέπουν κλήσεις live",
        "Κουζίνα & bar από οθόνες Pass",
        "Ιστορικό για να ξέρεις τι έγινε κάθε βράδυ",
      ],
      cta: "Αναβάθμιση σε Pro",
    },
  },
  proFeature: {
    live360: {
      title: "Live 360° — μόνο Pro",
      description:
        "Οι οθόνες σερβιτόρου, το ιστορικό παραδόσεων και οι κλήσεις από QR λειτουργούν στο πλάνο Pro. Αναβάθμισε για να συντονίζεις κουζίνα, bar και σερβιτόρους live.",
      staffDescription:
        "Το Live 360° (οθόνες και κλήσεις) είναι διαθέσιμο μόνο στο πλάνο Pro. Ζήτησε από τον διαχειριστή του λογαριασμού να αναβαθμίσει.",
      proBadge: "Μόνο Pro",
      upgrade: "Αναβάθμιση σε Pro",
      back: "Πίσω στην επισκόπηση",
    },
  },
  welcome:
    "Καλώς ήρθες στο MenuOS! Ακολούθησε τον οδηγό παρακάτω: πρώτα φτιάξε το κατάστημά σου, μετά βάλε είδη στον κατάλογο και τέλος βγάλε QR για τα τραπέζια.",
  venueCreated:
    "Το κατάστημα δημιουργήθηκε! Τώρα πρόσθεσε κατηγορίες και είδη — ή κάνε εισαγωγή από PDF αν έχεις Pro.",
  /** Γενικός όρος καταλόγου — φαγητά, ποτά, κ.λπ. (όχι μόνο «πιάτα»). */
  catalogEntry: {
    label: "Είδη",
    one: "είδος",
    many: "είδη",
    count: (n: number) => `${n} ${n === 1 ? "είδος" : "είδη"}`,
    add: "Προσθήκη είδους",
    new: "Νέο είδος",
    save: "Αποθήκευση είδους",
    deleteConfirm: "Διαγραφή του είδους;\n\nΕίσαι σίγουρος; Η ενέργεια δεν αναιρείται.",
    editTitle: "Επεξεργασία είδους",
    deleteTitle: "Διαγραφή είδους",
    empty: "Δεν υπάρχουν είδη — πρόσθεσε το πρώτο.",
    categoryHasEntries:
      "Δεν μπορείς να διαγράψεις κατηγορία που έχει είδη. Διέγραψε πρώτα όλα τα είδη.",
    categoryDeleteHint: "Διέγραψε πρώτα όλα τα είδη της κατηγορίας",
    notFound: "Το είδος δεν βρέθηκε.",
    invalidData: "Μη έγκυρα δεδομένα είδους.",
    deactivated: "Το είδος απενεργοποιήθηκε.",
    updated: "Το είδος ενημερώθηκε.",
    deleted: "Το είδος διαγράφηκε.",
    added: (name: string) => `Το είδος «${name}» προστέθηκε στον κατάλογο.`,
  },
  waiter: {
    copied: "Αντιγράφηκε!",
    newItems: "Νέα είδη",
    needVenueFirst: "Φτιάξε πρώτα κατάστημα για να λαμβάνεις κλήσεις από πελάτες.",
    managerViewBadge: "Προβολή: όλο το κατάστημα",
    managerZoneViewBadge: (zone: string) => `Προβολή: ${zone}`,
    staffViewBadge: (name: string, zone: string | null, stations: string) =>
      zone
        ? `Προβολή: ${name} · ${zone} · ${stations}`
        : `Προβολή: ${name} · ${stations}`,
    assignedZoneHeading: "Ο χώρος σου",
    assignedZoneHint: "",
    zoneFilterAll: "Όλοι οι χώροι",
    zonePickHeading: "Διάλεξε χώρο",
    zoneSpotCount: (n: number) => (n === 1 ? "1 θέση" : `${n} θέσεις`),
    zoneActiveCount: (n: number) => (n === 1 ? "1 ενεργό" : `${n} ενεργά`),
    zoneMessageCount: (n: number) => (n === 1 ? "1 μήνυμα" : `${n} μηνύματα`),
    zonePendingBreakdown: (parts: string[]) =>
      parts.length > 0 ? `Σε αναμονή ανά χώρο: ${parts.join(" · ")}` : "",
    whereToGoHeading: (n: number) =>
      n === 1 ? "1 μήνυμα — πήγαινε εδώ:" : `${n} μηνύματα — πήγαινε εδώ:`,
    otherVenuePendingHint: (parts: string[]) =>
      parts.length > 0
        ? `Τα μηνύματα δεν είναι σε αυτό το κατάστημα — είναι εδώ: ${parts.join(" · ")}. Άλλαξε κατάστημα από το πεδίο πάνω δεξιά.`
        : "",
    otherVenuePendingPart: (name: string, n: number) => `${name} (${n})`,
    unmappedZoneLabel: (n: number) => (n === 1 ? "Άλλο (1)" : `Άλλο (${n})`),
    unmappedActiveHint: (n: number) =>
      n === 1
        ? "1 κλήση/μήνυμα χωρίς σαφή χώρο — δες «Όλοι οι χώροι» ή έλεγξε τον αριθμό τραπεζιού."
        : `${n} κλήσεις/μηνύματα χωρίς σαφή χώρο — δες «Όλοι οι χώροι» ή έλεγξε τους αριθμούς τραπεζιών.`,
    emptyZoneView: "Καμία θέση ή κίνηση σε αυτόν τον χώρο αυτή τη στιγμή.",
    pendingCount: (n: number) => `${n} σε αναμονή`,
    activeCount: (n: number) => (n === 1 ? "1 ενεργό" : `${n} ενεργά`),
    refreshHint: "Ανανέωση κάθε 5 δευτ.",
    shiftLock: {
      lockButton: "Κράτα ανοιχτή",
      unlockButton: "Ξεκλείδωμα",
      unlockButtonShort: "Ξεκλ.",
      promptTitle: "Βάρδια με κινητό",
      promptHint:
        "Πάτα για να μείνει ανοιχτή η οθόνη και το panel — οι ήχοι και οι κλήσεις δουλεύουν πιο σίγουρα. Όταν τελειώσεις, ξεκλείδωσε.",
      lockedTitle: "Οθόνη ενεργή",
      lockedHint: "Έτοιμο για κλήσεις.",
      fullscreenOn: "Πλήρης οθόνη",
      unsupported:
        "Άνοιξε το link από εικονίδιο στην αρχική (όχι απλό tab) για καλύτερη λειτουργία.",
    },
    staffSetup: {
      readinessLabel: "Έτοιμο για κουζίνα",
      installedLabel: "Αρχική",
      pushLabel: "Ειδοποιήσεις",
      voiceLabel: "Φωνή",
      voiceOff: "Ανενεργή",
      installButton: "Στην Αρχική",
      pushButton: "Ειδοποιήσεις",
      testButton: "Δοκιμή ήχου",
      testPlaying: "Ακούς...",
      iosInstallTitle: "Προσθήκη στην Αρχική",
      iosStep1: "Πάτα το κουμπί Κοινοποίηση (κάτω στη μέση).",
      iosStep2: "Διάλεξε «Προσθήκη στην Αρχική οθόνη».",
      iosStep3: "Άνοιξε από το εικονίδιο — θα ανοίξει αυτή η σελίδα σερβιτόρου, όχι η αρχική του site.",
      iosClose: "Κατάλαβα",
      inAppWarning: "Άνοιξε σε Chrome ή Safari — όχι από Messenger ή Instagram.",
      pushDenied: "Οι ειδοποιήσεις αποκλείστηκαν — άλλαξέ το από τις ρυθμίσεις του κινητού.",
      pushUnsupported: "Αυτό το browser δεν υποστηρίζει ειδοποιήσεις. Χρησιμοποίησε Chrome (Android) ή Safari (iPhone).",
      allReady: "Όλα έτοιμα — θα ακούς μήνυμα από την κουζίνα.",
      compactReadyLabel: "Έτοιμο",
      doneButton: "Έτοιμο — ξεκίνα",
      testAriaLabel: "Δοκιμή ήχου",
    },
    loadFailed: "Δεν φορτώθηκαν οι κλήσεις. Κάνε refresh ή άνοιξε ξανά το link από το dashboard.",
    sessionExpired: "Έληξε η σύνδεση — άνοιξε ξανά το link σερβιτόρου από το dashboard.",
    emptyTitle: "Καμία ενεργή κλήση",
    emptyDesc:
      "Όταν πελάτης στείλει παραγγελία, καλέσει σερβιτόρο ή ζητήσει λογαριασμό από το QR menu, θα εμφανιστεί εδώ.",
    emptySpotsActiveHint:
      "Δεν έχουν ρυθμιστεί θέσεις — οι ενεργές κλήσεις εμφανίζονται παρακάτω. Ρύθμισε τραπέζια/δωμάτια από Ρυθμίσεις → Θέσεις.",
    unmappedSpotBadge: "Χωρίς ρύθμιση",
    goButton: "Αποδοχή",
    completeButton: "Έτοιμο",
    orderTotal: "Σύνολο",
    callStatus: {
      PENDING: "Σε αναμονή",
      ACKNOWLEDGED: "Σε εξέλιξη",
      COMPLETED: "Ολοκληρώθηκε",
      CANCELED: "Ακυρώθηκε",
    },
    callType: {
      WAITER: "Κλήση σερβιτόρου",
      BILL: "Λογαριασμός",
      ORDER: "Παραγγελία",
    },
    passSection: "Πάσα τμημάτων",
    passEmpty: "Καμία ενεργή ειδοποίηση πάσου.",
    passCount: (n: number) => `${n} πάσο`,
    passNewMessage: "Νέο μήνυμα",
    passPickedUp: "Το είδα",
    passDelivered: "Έγινε",
    passStatus: {
      READY: "Έτοιμο",
      PICKED_UP: "Σε εξέλιξη",
      DELIVERED: "Έτοιμο",
    },
    passStation: {
      kitchen: "Κουζίνα",
      bar: "Μπαρ",
      cold: "Κρύα",
      dessert: "Γλυκά",
    },
    passReadyLabel: {
      kitchen: "Έτοιμο — κουζίνα",
      bar: "Έτοιμο — μπαρ",
      cold: "Έτοιμο — κρύα",
      dessert: "Έτοιμο — γλυκά",
    },
    tableGridTitle: "Χάρτης θέσεων",
    tableGridLegendHint: "Η κατάσταση εμφανίζεται πάνω σε κάθε κάρτα.",
    tableGridLegendAutoNote: "Τα μηνύματα ενημερώνονται αυτόματα — δεν χρειάζεται ρύθμιση.",
    tableStateLabels: {
      idle: "Ήσυχο",
      guest_call: "Κλήση πελάτη",
      kitchen_ready: "Έτοιμο — κουζίνα",
      cold_ready: "Έτοιμο — κρύα",
      bar_ready: "Έτοιμο — μπαρ",
      both: "Πολλαπλά",
    },
  },
  push: {
    title: "Ειδοποιήσεις σε αυτή τη συσκευή",
    checking: "Έλεγχος ειδοποιήσεων...",
    description:
      "Λάβε ειδοποίηση όταν έρχεται κλήση σερβιτόρου ή παραγγελία — ακόμα κι αν η σελίδα είναι κλειστή.",
    subscribed: "Οι ειδοποιήσεις είναι ενεργές σε αυτή τη συσκευή.",
    denied: "Οι ειδοποιήσεις αποκλείστηκαν από το browser. Άλλαξέ το από τις ρυθμίσεις του κινητού.",
    enable: "Ενεργοποίηση",
    disable: "Απενεργοποίηση",
    enableSuccess: "Επιτυχία — οι ειδοποιήσεις είναι ενεργές σε αυτή τη συσκευή.",
    enableFailed: "Αποτυχία. Δοκίμασε ξανά ή άνοιξε το link σε Chrome/Safari.",
    unsupported:
      "Αυτό το browser (π.χ. Messenger, Instagram, WhatsApp) δεν υποστηρίζει push ειδοποιήσεις. Άνοιξε το link σε Chrome (Android) ή Safari (iPhone).",
    disabledServer: "Οι push ειδοποιήσεις δεν είναι ρυθμισμένες στον server — επικοινώνησε με την υποστήριξη.",
    inAppBrowser:
      "Φαίνεται ότι άνοιξες το link μέσα σε Messenger ή άλλη εφαρμογή. Για push: πάτα ⋮ → «Άνοιγμα στο Chrome» ή στείλε το link στον εαυτό σου και άνοιξέ το εκεί.",
    iosHint:
      "iPhone: Άνοιξε σε Safari (όχι Messenger). Πάτα «Ενεργοποίηση» → Επίτρεψε ειδοποιήσεις. Για καλύτερα αποτελέσματα: Προσθήκη στην Αρχική οθόνη.",
    androidHint:
      "Android: Άνοιξε σε Chrome (όχι Messenger). Πάτα «Ενεργοποίηση» και επέτρεψε ειδοποιήσεις όταν το ζητήσει.",
    pageOpenHint:
      "Με ανοιχτή σελίδα βλέπεις κλήσεις live — χωρίς push.",
    compactInApp: "Άνοιξε σε Chrome/Safari — όχι από Messenger.",
    compactPrompt: "Push για ήχο όταν η οθόνη είναι κλειστή ή κλειδωμένη.",
    compactSubscribed: "Push ενεργό",
    iosBrowserUnsupported:
      "iPhone: Άνοιξε σε Safari → Προσθήκη στην Αρχική. Εκεί δουλεύουν push και φωνή. Το Chrome στο iPhone δεν υποστηρίζει push.",
    managerHint:
      "Λαμβάνεις push για κλήσεις και πάσο σε όλα τα καταστήματα της επιχείρησης σε αυτή τη συσκευή.",
  },
  cuisineType: {
    label: "Τύπος κουζίνας",
    hint: "Το βλέπει ο πελάτης στο QR menu — π.χ. Μεσογειακή, Gourmet, Ιταλική.",
    unsetOption: "Επίλεξε τύπο κουζίνας…",
    options: {
      MEDITERRANEAN: "Μεσογειακή",
      GREEK: "Ελληνική",
      ITALIAN: "Ιταλική",
      GOURMET: "Gourmet",
      SEAFOOD: "Θαλασσινά",
      GRILL: "Ψητά & grill",
      CAFE_BAR: "Café & bar",
      ASIAN: "Ασιατική",
      INTERNATIONAL: "Διεθνής",
      VEGETARIAN: "Vegetarian / vegan",
      OTHER: "Άλλο",
    },
  },
  photos: {
    label: "Φωτογραφία (προαιρετικό)",
    logoLabel: "Logo καταστήματος",
    logoHint: "Εμφανίζεται στο QR menu δίπλα στο όνομα. Τετράγωνο ή στρογγυλό PNG/JPG — ιδανικά 200×200 px.",
    logoSaveHint: "Μετά το upload, πάτα «Αποθήκευση ρυθμίσεων» για να εμφανιστεί στο menu.",
    uploadButton: "Ανέβασμα από κινητό/υπολογιστή",
    uploading: "Ανέβασμα...",
    uploadHint: "JPG ή PNG έως 5 MB — βελτιστοποιείται αυτόματα για το menu.",
    uploadFailed: "Αποτυχία ανεβάσματος.",
    urlPlaceholder: "ή επικόλλησε link φωτογραφίας",
    urlOptional: "ή επικόλλησε link φωτογραφίας",
    urlOnlyHint: "Χωρίς φωτό εμφανίζεται ως καθαρή γραμμή στο menu.",
    remove: "Αφαίρεση",
  },
  layout: {
    tagline: "Διαχείριση menu",
    welcome: "Καλώς ήρθες",
    subscriptionPrefix: "Συνδρομή",
  },
  nav: {
    overview: "Επισκόπηση",
    waiter: "Οθόνες",
    history: "Ιστορικό",
    qrShort: "QR",
    callsShort: "Οθόνες",
    proOnlyBadge: "Μόνο Pro",
  },
  pages: {
    menus: {
      title: "Κατάλογος",
      description:
        "Πρόσθεσε κατηγορίες και είδη — υποστηρίζονται πολλαπλές γλώσσες στο QR menu.",
    },
    import: {
      title: "Εισαγωγή από PDF",
      description:
        "Ανέβασε PDF menu — ελέγχεις τα αποτελέσματα πριν τα αποθηκεύσεις στον κατάλογο.",
      backToCatalog: "← Πίσω στον κατάλογο",
    },
    qr: {
      title: "QR Codes",
      descriptionBasic:
        "Ένα link και ένα QR για όλον τον κατάλογο — τύπωσέ το όπου θες.",
      descriptionPro:
        "Κατέβασε ή δες QR για κάθε θέση. Τα τραπέζια ρυθμίζονται από Ρυθμίσεις → Θέσεις.",
      description:
        "Κατέβασε ή δες QR για κάθε θέση. Τα τραπέζια ρυθμίζονται από Ρυθμίσεις → Θέσεις.",
      catalogTitle: "QR καταλόγου",
      catalogDesc:
        "Οι πελάτες σκανάρουν και βλέπουν τα πιάτα σου. Ένα QR για όλο το μαγαζί — χωρίς τραπέζια.",
      catalogLinkLabel: "Link καταλόγου",
      configureSpotsLink: "Ρύθμιση τραπεζιών →",
      configureSpotsEmpty: "Δεν έχεις ακόμα θέσεις. Ρύθμισέ τες από Ρυθμίσεις → Θέσεις.",
      needVenueTitle: "Χρειάζεσαι πρώτα κατάστημα",
      needVenueDesc: "Φτιάξε κατάστημα και πρόσθεσε είδη πριν βγάλεις QR.",
      emptyCatalogTitle: "Ο κατάλογος είναι άδειος",
      emptyCatalogBeforeLink: "Πρόσθεσε είδη στον",
      catalogLink: "κατάλογο",
      emptyCatalogAfterLink: "πριν μοιράσεις QR.",
      emptyCatalogAfterLinkCustomers: "πριν μοιράσεις QR στους πελάτες.",
      settingsTitle: "Ρυθμίσεις QR",
      settingsDesc:
        "Κάθε QR ανοίγει τον online κατάλογο. Βάλε αριθμό τραπεζιού ή δωματίου — έτσι ξέρεις από πού σε καλούν.",
      tableLabel: "Τραπέζι (προαιρετικό)",
      roomLabel: "Δωμάτιο (προαιρετικό)",
      defaultLangLabel: "Προεπιλεγμένη γλώσσα QR",
      generating: "Δημιουργία...",
      updateQr: "Ενημέρωση QR",
      downloadPng: "Κατέβασμα PNG",
      openCatalog: "Άνοιγμα καταλόγου",
      generatedSuccess: "Το QR δημιουργήθηκε! Κατέβασέ το ή εκτύπωσέ το.",
      spotsTitle: "Τραπέζια, δωμάτια & ξαπλώστρες",
      zonesDesc:
        "Άνοιξε κάθε χώρο για να δεις QR ανά τραπέζι — προβολή, κατέβασμα ή δοκιμή link.",
      spotsDesc:
        "Πρόσθεσε κάθε θέση μία φορά. Κάθε QR «δένει» τον αριθμό — ο σερβιτόρος βλέπει ακριβώς από πού καλούν.",
      spotTypeLabel: "Τύπος",
      bulkTitle: "Μαζική προσθήκη",
      bulkDesc:
        "Όσα τραπέζια, δωμάτια ή ξαπλώστρες χρειάζεσαι — χωρίς όριο πλάνου. Έως 200 θέσεις κάθε φορά (για περισσότερες, επανάλαβε με νέο εύρος). Προαιρετικό πρόθεμα για χώρους (π.χ. Αυλή-, Όροφος-).",
      prefixLabel: "Πρόθεμα (προαιρετικό)",
      fromLabel: "Από",
      toLabel: "Έως",
      bulkAdding: "Προσθήκη...",
      bulkAddAll: "Προσθήκη όλων",
      spotNameLabel: "Αριθμός / όνομα",
      spotPlaceholderRoom: "204 ή vip-1",
      spotPlaceholderSunbed: "A12 ή paralia-3",
      spotPlaceholderTable: "12 ή Αυλή-1",
      addSpot: "Προσθήκη",
      yourSpots: (count: number) => (count > 0 ? `Οι θέσεις σου (${count})` : "Οι θέσεις σου"),
      loadingSpots: "Φόρτωση...",
      emptySpots: "Δεν έχεις ακόμα θέσεις. Πρόσθεσε ανά χώρο (π.χ. Bar 1–10, Σαλα 1–20).",
      saveSpot: "Αποθήκευση",
      cancelEdit: "Άκυρο",
      editSpot: "Επεξεργασία",
      deleteSpotLabel: "Διαγραφή",
      deleteSpotConfirm: (name: string) =>
        `Διαγραφή της θέσης «${name}»;\n\nΑν έχεις ήδη τυπώσει QR, δεν θα λειτουργεί πλέον. Η ενέργεια δεν αναιρείται.`,
      renameQrWarning:
        "Αλλάζοντας το όνομα, αλλάζει και το URL του QR — ξανατύπωσε QR αν χρειάζεται.",
      invalidRange: "Βάλε έγκυρο εύρος από 1 έως 999 (π.χ. από 1 έως 120).",
      bulkLimit: "Μέγιστο 200 θέσεις ανά φορά. Για περισσότερες, κάνε δεύτερη προσθήκη (π.χ. 201–400).",
      invalidPrefix: (hint: string) => `Άκυρο πρόθεμα. ${hint}`,
      labelHint: "Μόνο γράμματα, αριθμοί, παύλα και κάτω παύλα (π.χ. 12, Αυλή-1).",
      previewSpot: "Προεπισκόπηση",
      showQr: "Προβολή QR",
      hideQr: "Κλείσιμο",
      loadingQr: "Φόρτωση QR…",
      spotTypes: {
        TABLE: "Τραπέζι",
        ROOM: "Δωμάτιο",
        SUNBED: "Ξαπλώστρα",
      } as Record<string, string>,
    },
    waiter: {
      title: "Οθόνες",
      description:
        "Live χάρτης θέσεων και κλήσεις πελάτη — ενημερώνεται αυτόματα. Τα links ρυθμίζονται από Ρυθμίσεις → Προσωπικό.",
      setupLink: "Ρυθμίσεις → Προσωπικό",
    },
    billing: {
      title: "Συνδρομή",
      description: "Διαχείριση συνδρομής MenuOS. Οι πληρωμές γίνονται με ασφάλεια online.",
    },
    history: {
      title: "Ιστορικό",
      description:
        "Παραδόσεις πάσου που ολοκληρώθηκαν — χρόνος από «έτοιμο» μέχρι «παρέδωσα», ανά θέση, τμήμα και σερβιτόρο.",
      daysLabel: "Περίοδος",
      days7: "7 ημέρες",
      days30: "30 ημέρες",
      days90: "90 ημέρες",
      filterSpot: "Θέση",
      filterStation: "Τμήμα",
      filterStaff: "Σερβιτόρος",
      filterAll: "Όλα",
      loading: "Φόρτωση...",
      empty: "Δεν υπάρχουν παραδόσεις με αυτά τα φίλτρα.",
      failed: "Δεν φορτώθηκε το ιστορικό. Δοκίμασε ξανά.",
      colSpot: "Θέση",
      colStation: "Τμήμα",
      colMessage: "Σχόλιο",
      colReady: "Έτοιμο",
      colDuration: "Διάρκεια",
      colStaff: "Σερβιτόρος",
      colDelivered: "Παρέδωσε",
    },
    settings: {
      title: "Ρυθμίσεις",
      description: "Πόστα, θέσεις, μηνύματα και προσωπικό — όλα από εδώ.",
      tabs: {
        general: "Λογαριασμός",
        staff: "Προσωπικό",
        posts: "Πόστα",
        venue: "Κατάστημα",
        messages: "Μηνύματα",
        tables: "Τραπέζια",
        spaces: "Χώροι",
      },
      postsTab: {
        title: "Πόστα",
        description:
          "Ορίστε ποιος κάνει τι — μάγειρας, σερβιτόρος, μπαρ, κ.λπ. Το όνομα εμφανίζεται στο προσωπικό, push και tablet.",
        hint: "Μέχρι 12 πόστα — π.χ. Κουζίνα, Bar, Services. Ο ρόλος καθορίζει tablet πάσου ή σερβιτόρο.",
        postNamePlaceholder: "π.χ. Κουζίνα, Bar, Services",
        postSpaceLabel: "Χώρος",
        postSpaceAll: "Όλοι οι χώροι",
        postTypeHint:
          "Κουζίνα/Μπαρ = tablet πάσου · Σερβιτόρος = κινητό · Λάντζα/Καθαριότητα/Γενικά = tablet μηνυμάτων.",
        waiterNameWarning:
          "Όνομα σερβιτόρου με ρόλο Κουζίνα/Μπαρ — άλλαξε ρόλο σε «Σερβιτόρος» ή βάλε όνομα πάστου.",
        linkedTitle: "Πού συνδέονται τα πόστα",
        linkedWaiterNote:
          "Σερβιτόρος δάπεδου = πόστο με ρόλο «Σερβιτόρος» εδώ (π.χ. Services Σάλα). Μετά το αντιστοιχείς στο tab Προσωπικό.",
        linkedTablet: (postName: string, stationName: string) =>
          `«${postName}» (${stationName}) → Μηνύματα + tablet στο Προσωπικό`,
        nextMessagesLink: "Μηνύματα →",
        nextStaffLink: "Προσωπικό →",
        saved: "Αποθηκεύτηκαν.",
        savedNextSteps:
          "Αποθηκεύτηκαν. Επόμενα: πρόσθεσε μηνύματα ανά πόστο και ανάθεσε εργαζόμενους στο Προσωπικό.",
        junkRemovedHint:
          "Αφαιρέθηκε πόστο με λάθος ρόλο — για σερβιτόρους διάλεξε ρόλο «Σερβιτόρος».",
        placeholderNameWarning:
          "Βάλε όνομα (π.χ. Κουζίνα) — το «Νέο πόστο» δεν εμφανίζεται στο Προσωπικό.",
        placeholderRemovedHint:
          "Αφαιρέθηκε πόστο χωρίς όνομα — μετονόμασέ το πριν την αποθήκευση ή διέγραψέ το.",
      },
      screensTab: {
        title: "Οθόνες tablet",
        description:
          "Links για tablet κουζίνας, μπαρ κ.λπ. — άνοιγμα χωρίς login. Το link στο Προσωπικό δείχνει εδώ.",
        hint: "Όνομα οθόνης = ίδιο με το πόστο για να δέσει σωστά (π.χ. «Grill»).\nΓια 2η κουζίνα: πρόσθεσε νέα οθόνη με όνομα του πόστου.",
        stationLabels: {
          kitchen: "Κουζίνα",
          bar: "Μπαρ",
          cold: "Κρύα",
          dessert: "Γλυκά",
        },
      },
      linksTab: {
        title: "Links προσωπικού ανά χώρο",
        description:
          "Κάθε χώρος έχει δικό του link και QR — στείλτε το στο προσωπικό (π.χ. σερβιτόροι Αυλής, σερβιτόροι Σαλας).",
        hint: "Σκανάροντας το QR ή ανοίγοντας το link, βλέπουν μόνο τον χώρο τους.\nΑν αλλάξετε κωδικό πρόσβασης, ενημερώστε όλα τα links/QR.",
        loading: "Φόρτωση χώρων…",
        empty: "Δεν έχεις χώρους ακόμα. Πρόσθεσέ τους στο tab «Χώροι».",
        spacesTabLink: "Πήγαινε στους Χώρους →",
        noStaffToken: "Δεν βρέθηκε link πρόσβασης για αυτό το κατάστημα.",
        spotCount: (n: number) => `${n} θέσεις`,
        openLink: "Άνοιγμα link",
        copyLink: "Αντιγραφή link",
        downloadQr: "Κατέβασμα QR",
        loadingQr: "QR…",
      },
      messagesTab: {
        title: "Μηνύματα",
        description:
          "Μία κάρτα ανά πόστο — πρόσθεσε μηνύματα και πάτα Αποθήκευση στο τέλος. (Πόστα → tab Πόστα)",
        hint: "",
        byPostTitle: "Μηνύματα ανά πόστο",
        byPostHint: "",
        selectPostLabel: "Διάλεξε πόστο",
        addMessage: "Προσθήκη",
        messageCount: (n: number) => (n === 1 ? "1 μήνυμα" : `${n} μηνύματα`),
        messagePlaceholder: "Γράψε το μήνυμά σου…",
        messageSaveHint:
          "Πάτα Αποθήκευση στο τέλος. Για να φανούν στο tablet, στο Προσωπικό διάλεξε το ίδιο πόστο — όχι «Σερβιτόρος».",
        passTabletStaffHint: (postName: string) =>
          `Tablet πάσου: στο Προσωπικό διάλεξε πόστο «${postName}» (όχι «Σερβιτόρος» — αυτός λαμβάνει ειδοποιήσεις στο κινητό).`,
        assignInStaffLink: "Προσωπικό →",
        noPostsHint: "Δεν έχεις ενεργά πόστα.",
        servicesPostTitle: "Σερβιτόρος — χάρτης θέσεων",
        servicesPostHint: "Τι βλέπει στον χάρτη (κλήση πελάτη, έτοιμο κουζίνας κ.λπ.) — όχι tablet πάσου.",
        passPostHint: "Πρόσθεσε τα μηνύματα που θέλεις για αυτό το πόστο — ένα-ένα.",
        messagesForPost: (postName: string) =>
          `Τα μηνύματα που στέλνει το πόστο «${postName}» από tablet (π.χ. μάγειρας, μπαρ).`,
        messagesListLabel: "Τα μηνύματα",
        previewLabel: "Προεπισκόπηση",
        previewEmpty: "Δεν έχεις προσθέσει μηνύματα ακόμα.",
        resetPostMessages: "Καθαρισμός μηνυμάτων",
        postColorLabel: "Χρώμα πόστου",
        addPost: "Νέο πόστο",
        addMapMessage: "Πρόσθεσε μήνυμα",
        addMapMessagePlaceholder: "Διάλεξε…",
        removeMessage: "Διαγραφή μηνύματος",
        managePostsLink: "Ρύθμιση πόστων →",
      },
      venueTab: {
        title: "Κατάστημα",
        description: "Όνομα, χρώματα και logo — αυτό βλέπει ο πελάτης στο QR menu.",
      },
      generalTab: {
        googleReview: {
          title: "Κριτικές Google",
          description:
            "Βάλε το link κριτικών από το Google Business Profile — εμφανίζεται στο τέλος του QR menu.",
          urlLabel: "Link Google (κριτικές)",
          urlPlaceholder: "https://g.page/r/... ή link από Google Maps",
          urlHint:
            "Google Business → Κριτικές → «Λήψη περισσότερων κριτικών» → αντιγραφή link.",
          save: "Αποθήκευση",
          saving: "Αποθήκευση…",
        },
      },
      tablesTab: {
        title: "Τραπέζια",
        description:
          "Διάλεξε χώρο, πες πόσα τραπέζια έχει και δημιούργησέ τα. Κάθε χώρος ξεχωριστά — άνοιξε για να δεις ή να διαγράψεις.",
        hint:
          "Ένας χώρος = ένα εύρος (π.χ. Αυλή 1–20).\nΜε 100+ τραπέζια, ο χώρος μένει κλειστός — άνοιξέ τον μόνο όταν χρειάζεσαι.",
        createTitle: "Νέος χώρος με τραπέζια",
        createDesc: "Διάλεξε τύπο χώρου, όνομα (αν χρειάζεται) και εύρος αριθμών.",
        createSpace: "Δημιουργία χώρου",
        creating: "Δημιουργία…",
        createPreview: (space: string, from: number, to: number, count: number) =>
          `Θα δημιουργηθούν ${count} θέσεις στον χώρο «${space}» (${from}–${to}).`,
        listTitle: "Οι χώροι σου",
        listDesc: "Πάτα έναν χώρο για να δεις τα τραπέζια. Διαγραφή χώρου = όλα τα τραπέζια του.",
        spotCount: (n: number) => `${n} τραπέζια`,
        addMoreTitle: "Πρόσθεσε κι άλλα σε αυτόν τον χώρο",
        addMore: "Προσθήκη",
        expandAll: "Άνοιγμα όλων",
        collapseAll: "Κλείσιμο όλων",
        loading: "Φόρτωση…",
        empty: "Δεν έχεις χώρους ακόμα.",
        emptyHint: "Χρησιμοποίησε τη φόρμα πάνω για τον πρώτο χώρο — π.χ. Σαλόνι 1–30.",
        emptyZone: "Κανένα τραπέζι σε αυτόν τον χώρο.",
        renameHint: "Για μετονομασία χώρου (πώς φαίνεται στον σερβιτόρο):",
        spacesTabLink: "Ρύθμιση χώρων →",
      },
      spacesTab: {
        title: "Χώροι",
        description:
          "Οι χώροι που βλέπει ο σερβιτόρος — Τραπέζια, Αυλή, Όροφος, Ξαπλώστρες, Δωμάτια.",
        hint: "Πρόσθεσε, μετονόμασε ή διέγραψε χώρους. Για μεμονωμένα τραπέζια/θέσεις, δες το tab «Τραπέζια».\nΤα QR ανά χώρο είναι στο τέλος — για link ανά άτομο, δες «Προσωπικό».",
        previewTitle: "Προεπισκόπηση",
        previewHint: "Έτσι εμφανίζονται στο «Διάλεξε χώρο» — ενημερώνεται live καθώς γράφεις.",
        empty: "Δεν έχεις χώρους ακόμα. Πάτα «Νέος χώρος» για να ξεκινήσεις.",
        spotCount: (n: number) => `${n} θέσεις`,
        addSpace: "Νέος χώρος",
        addSpaceTitle: "Προσθήκη χώρου",
        addSpaceDesc: "Δημιούργησε νέο χώρο με θέσεις — π.χ. Αυλή 1–10 ή απλά τραπέζια 1–20.",
        spaceKindLabel: "Τύπος",
        spaceKindPrefixed: "Χώρος με όνομα (π.χ. Αυλή-1)",
        spaceKindMain: "Απλά τραπέζια (1, 2, 3…)",
        spaceKindSunbed: "Ξαπλώστρες",
        spaceKindRoom: "Δωμάτια",
        spaceNameLabel: "Όνομα χώρου",
        spaceNameRequired: "Βάλε όνομα χώρου (π.χ. Αυλή, Bar).",
        fromLabel: "Από",
        toLabel: "Έως",
        createSpace: "Δημιουργία χώρου",
        creatingSpace: "Δημιουργία…",
        deleteSpace: "Διαγραφή χώρου",
        deleteSpaceConfirm: (name: string, count: number) =>
          `Διαγραφή χώρου «${name}» και ${count} θέσε${count === 1 ? "ης" : "ων"}; Δεν αναιρείται.`,
        spaceDeleted: (name: string) => `Ο χώρος «${name}» διαγράφηκε.`,
        spaceCreated: (name: string, count: number) =>
          `Δημιουργήθηκε ο χώρος «${name}» με ${count} θέσει${count === 1 ? "η" : "ς"}.`,
        tablesTabLink: "Επεξεργασία μεμονωμένων θέσεων →",
        invalidRange: "Έλεγξε τα νούμερα «Από» και «Έως».",
        zoneQrTitle: "QR & link ανά χώρο",
        zoneQrDescription:
          "Κάθε χώρος έχει δικό του QR — ανοίγοντάς το, βλέπουν μόνο αυτόν τον χώρο (π.χ. Σάλα, Αυλή).",
        zoneQrHint:
          "Για προσωπικό με όνομα και δικό του link, πήγαινε στο tab «Προσωπικό» — εκεί γίνεται και η αλλαγή κωδικού.",
        zoneQrLoading: "Φόρτωση…",
        zoneQrLoadingQr: "QR…",
        zoneQrNoToken: "Δεν βρέθηκε link πρόσβασης για αυτό το κατάστημα.",
        zoneQrOpenLink: "Άνοιγμα link",
        zoneQrCopyLink: "Αντιγραφή link",
        zoneQrDownload: "Κατέβασμα QR",
      },
      demoBadge: "Δείγμα — για δοκιμές UI",
      personnel: {
        title: "Προσωπικό",
        description:
          "Φτιάξε εργαζόμενο: όνομα, ρόλος, χώρος και πόστο. Πρώτα διάλεξε ρόλο — μετά εμφανίζονται τα σωστά πόστα.",
        addTitle: "Νέος εργαζόμενος",
        addStaff: "Προσθήκη",
        listTitle: "Εργαζόμενοι",
        editTitle: "Επεξεργασία",
        cancelEdit: "Άκυρο",
        formHint:
          "Σερβιτόρος = κινητό (κλήσεις, πάσο). Κουζίνα/Μπαρ = tablet (γρήγορα μηνύματα, πάσος). Το πόστο πρέπει να ταιριάζει με Ρυθμίσεις → Μηνύματα.",
        messagesScopeWaiter:
          "Σερβιτόρος δάπεδου — κλήσεις & πάσο στο κινητό (δεν στέλνει γρήγορα μηνύματα)",
        messagesScopeAll:
          "Όλα τα πόστα & χώροι — κλήσεις, πάσος και όλοι οι χώροι στο κινητό",
        messagesScopeTablet: "Tablet πάσου — στέλνει τα μηνύματα αυτού του πόστου",
        colSpaceAll: "Όλα",
        managePostsLink: "Ρύθμιση πόστων →",
        manageSpacesLink: "Ρύθμιση χώρων →",
        manageMessagesLink: "Ρύθμιση μηνυμάτων →",
        messagesPreviewEmpty: "Δεν έχεις ρυθμίσει μηνύματα για αυτό το πόστο.",
        noPosts: "Δεν έχεις ενεργά πόστα.",
        noSpaces: "Δεν έχεις χώρους ακόμα.",
        zoneRequired: "Επίλεξε χώρο — π.χ. Σάλα, Αυλή ή «Όλα».",
        saving: "Αποθήκευση...",
        colName: "Όνομα",
        colRole: "Ρόλος",
        colRoleRequired: "Ρόλος *",
        colSpace: "Χώρος",
        colPost: "Πόστο",
        colPostHint: "Μπλε = κινητό · πράσινο = tablet",
        colScreen: "Οθόνη",
        colSpaceRequired: "Χώρος *",
        colPostRequired: "Πόστο *",
        colScreenRequired: "Οθόνη *",
        jobRoleWaiter: "Σερβιτόρος",
        jobRolePass: "Κουζίνα / Μπαρ",
        jobRoleWaiterHint: "Κινητό — κλήσεις πελάτη & πάσος",
        jobRolePassHint: "Tablet — γρήγορα μηνύματα & πάσος",
        screenMobile: "Κινητό",
        screenKds: "Tablet πάσου",
        screenSupportTablet: "Tablet μηνυμάτων",
        screenMobileHint: "Κλήσεις πελάτη & πάσος στο κινητό",
        screenKdsHint: "Γρήγορα μηνύματα & πάσος στο tablet",
        screenSupportTabletHint: "Γρήγορα μηνύματα στο tablet (λάντζα, καθαριότητα κ.λπ.)",
        postsOnKdsScreenHint:
          "Bar, κουζίνα κ.λπ. από tab Πόστα → άλλαξε Οθόνη σε «KDS (tablet πάσου)».",
        postsOnMobileScreenHint:
          "Σερβιτόρος (Services…) → άλλαξε Οθόνη σε «Κινητό».",
        noKdsPosts: "Δεν έχεις πόστα κουζίνας/μπαρ — ρύθμισε πρώτα το tab «Πόστα».",
        noWaiterPosts:
          "Δεν έχεις πόστο σερβιτόρου — πρόσθεσε πόστο με ρόλο «Σερβιτόρος» στο tab «Πόστα» (ή διάλεξε «Όλα»).",
        selectSpacePlaceholder: "Επίλεξε χώρο",
        selectPostPlaceholder: "Επίλεξε πόστο",
        fieldsRequiredHint:
          "Όνομα, ρόλος, χώρος (σερβιτόρος) και πόστο είναι υποχρεωτικά. Τα πόστα φιλτράρονται από τον ρόλο.",
        colLink: "Link & QR",
        colLinkHint:
          "Σερβιτόρος: link ή QR για κινητό. Κουζίνα/Μπαρ: link ή QR για tablet — άνοιγμα χωρίς login.",
        listDeviceLegend:
          "Μπλε = κινητό · πράσινο = tablet (πάσου ή μηνυμάτων). Το ίδιο χρώμα έχει και το εικονίδιο στη στήλη «Πόστο».",
        colActions: "Ενέργειες",
        viewLink: "Προβολή",
        viewLinkTablet: "Άνοιγμα οθόνης",
        missingScreen: "Δεν υπάρχει link tablet — αποθήκευσε τα πόστα στο tab «Πόστα».",
        invalidAssignment: "Χωρίς έγκυρο πόστο — διάλεξε ξανά πόστο και χώρο.",
        invalidStaffBanner: (n: number) =>
          n === 1
            ? "1 άτομο χωρίς έγκυρο πόστο — επεξεργάσου τη γραμμή παρακάτω."
            : `${n} άτομα χωρίς έγκυρο πόστο — επεξεργάσου τις γραμμές παρακάτω.`,
        screenPostMismatch: "Το όνομα οθόνης δεν ταιριάζει με πόστο — βάλε ίδιο όνομα (π.χ. «Κουζίνα»).",
        tabletScreensTitle: "Οθόνες tablet",
        tabletScreensHint:
          "Links για KDS/Bar — άνοιγμα χωρίς login. Όνομα οθόνης = όνομα πόστου.",
        copyLink: "Αντιγραφή",
        copied: "Αντιγράφηκε!",
        qrLink: "QR",
        qrTitle: (name: string) => `QR — ${name}`,
        qrHintMobile: "Σκανάρισε από το κινητό — ανοίγει απευθείας το panel σερβιτόρου.",
        qrHintTablet: "Σκανάρισε στο tablet — ανοίγει η οθόνη πάσου χωρίς login.",
        downloadQr: "Κατέβασμα QR",
        qrLoading: "Φόρτωση QR…",
        qrFailed: "Αποτυχία.",
        qrNetworkError: "Σφάλμα δικτύου.",
        rotateLink: "Νέο link",
        rotateConfirm: (name: string) =>
          `Νέο link για «${name}»; Το παλιό θα σταματήσει να λειτουργεί.`,
        namePlaceholder: "π.χ. Μαρία Π.",
        rolePlaceholder: "Επίλεξε ρόλο",
        loading: "Φόρτωση...",
        empty: "Δεν έχεις προσθέσει προσωπικό ακόμα.",
        deleteConfirm: (name: string) =>
          `Διαγραφή του «${name}»;\n\nΤο προσωπικό link θα σταματήσει. Η ενέργεια δεν αναιρείται.`,
        deleteTitle: "Διαγραφή προσωπικού",
        edit: "Επεξεργασία",
        delete: "Διαγραφή",
        saveEdit: "Αποθήκευση",
        stationLabels: {
          services: "Σερβιτόρος",
          kitchen: "Κουζίνα",
          bar: "Μπαρ",
          cold: "Κρύα",
          dessert: "Γλυκά",
          all: "Όλα",
        },
      },
      kitchen: {
        title: "Κουζίνα",
        description: "Οθόνη για τον μάγειρα — στέλνει «έλα πάσο» στον σερβιτόρο.",
        screenLink: "Link οθόνης κουζίνας",
        screenHint: "Άνοιξε σε tablet στην κουζίνα — χωρίς login dashboard.",
        sampleTable: "Τραπέζι",
        sampleComment: "Σχόλιο (π.χ. ξέχασες τον πάγο)",
        sampleCommentPlaceholder: "ξέχασες τον πάγο",
        sampleSend: "Αποστολή",
        openScreen: "Άνοιγμα οθόνης",
        copyScreenLink: "Αντιγραφή link",
      },
      kitchenTab: {
        title: "Οθόνες κουζίνας",
        description:
          "Κάθε οθόνη ανοίγει σε tablet — χωρίς login. Ο μάγειρας πατά «Έτοιμο» και ειδοποιείται ο σερβιτόρος.",
        steps:
          "Άνοιξε την οθόνη στο tablet της κουζίνας\nΑντιγράψε το link ή πάτα «Άνοιγμα οθόνης»\nΓια 2η κουζίνα/χώρο: πρόσθεσε νέα οθόνη με όνομα (π.χ. Παραλία)",
      },
      bar: {
        title: "Μπαρ",
        description: "Οθόνη για το μπαρ — ειδοποίηση σερβιτόρου όταν είναι έτοιμο το ποτό.",
        screenLink: "Link οθόνης μπαρ",
        screenHint: "Γρήγορες ενέργειες για tablet στο μπαρ.",
        sampleSend: "Έτοιμο το ποτό",
        openScreen: "Άνοιγμα οθόνης",
        copyScreenLink: "Αντιγραφή link",
      },
      barTab: {
        title: "Οθόνες μπαρ & γλυκών",
        description:
          "Ίδια λογική με την κουζίνα — tablet στο μπαρ ή στο πάσο γλυκών, χωρίς login.",
        steps:
          "Άνοιξε την οθόνη στο tablet του μπαρ\nΓια 2ο μπαρ (π.χ. παραλία): πρόσθεσε νέα οθόνη\nΤα γλυκά μπορούν να έχουν ξεχωριστή οθόνη",
      },
      cold: {
        title: "Κρύα κουζίνα",
        description: "Σαλάτες και ορεκτικά κρύα — ξεχωριστή οθόνη αν τη χρησιμοποιείτε.",
        screenLink: "Link οθόνης κρύας",
        screenHint: "Tablet στην κρύα κουζίνα — χωρίς login dashboard.",
        openScreen: "Άνοιγμα οθόνης",
        copyScreenLink: "Αντιγραφή link",
      },
      dessert: {
        title: "Γλυκά",
        description: "Ειδοποίηση σερβιτόρου όταν είναι έτοιμο το επιδόρπιο.",
        screenLink: "Link οθόνης γλυκών",
        screenHint: "Tablet στο πάσο γλυκών ή δίπλα στο μπαρ.",
        openScreen: "Άνοιγμα οθόνης",
        copyScreenLink: "Αντιγραφή link",
      },
      rotateScreenButton: "Νέος κωδικός οθόνης",
      rotatingScreen: "Αλλαγή...",
      rotateScreenConfirm:
        "Να αλλάξει ο κωδικός; Το τρέχον link θα σταματήσει να λειτουργεί.",
      rotateScreenFailed: "Αποτυχία αλλαγής κωδικού οθόνης.",
      copyLinkFailed: "Δεν αντιγράφηκε το link — δοκίμασε χειροκίνητα.",
      multiScreenHint:
        "Μπορείς να έχεις πολλές οθόνες ανά τμήμα (π.χ. μπαρ παραλίας και μπαρ καταστήματος) — κάθε μία με δικό της link.",
      loadingScreens: "Φόρτωση οθονών…",
      screensEmpty: "Δεν υπάρχουν οθόνες ακόμα — πρόσθεσε μία παρακάτω.",
      showLink: "Δες link",
      hideLink: "Κρύψε link",
      allTablesZone: "Όλα τα τραπέζια / ξαπλώστρες / δωμάτια",
      addScreenFor: (dept: string) => `Νέα οθόνη — ${dept}`,
      addScreenTitle: "Προσθήκη οθόνης",
      addScreenHint: "Όνομα για να ξεχωρίζει (π.χ. Παραλία, Σαλόνι).",
      screenNameLabel: "Όνομα οθόνης",
      screenPostMismatch: "Το όνομα οθόνης δεν ταιριάζει με πόστο — βάλε ίδιο όνομα (π.χ. «Κουζίνα»).",
      screenNamePlaceholder: "π.χ. Παραλία",
      screenSpotPrefixLabel: "Χώρος (προαιρετικό)",
      screenSpotPrefixPlaceholder: "π.χ. Αυλή",
      screenSpotPrefixHint:
        "Κενό = όλα τα τραπέζια, ξαπλώστρες και δωμάτια. «Σαλόνι» = μόνο αριθμητικά (1, 2, 3…). Άλλο πρόθεμα = μόνο τραπέζια με αυτό το prefix (π.χ. Αυλή-1).",
      screenSpotPrefixHintShort:
        "Άδειο πεδίο = όλα. «Σαλόνι» = μόνο αριθμητικά τραπέζια. «Αυλή» = μόνο Αυλή-1, Αυλή-2…",
      screenSpotPrefixActive: (prefix: string) => `Μόνο τραπέζια: ${prefix}-*`,
      addScreenButton: "Προσθήκη",
      addingScreen: "Προσθήκη…",
      addScreenFailed: "Αποτυχία προσθήκης οθόνης.",
      deleteScreen: "Διαγραφή",
      deleteScreenTitle: "Διαγραφή οθόνης",
      deleteScreenConfirm: (name: string) =>
        `Διαγραφή της οθόνης «${name}»;\n\nΤο link θα σταματήσει να λειτουργεί. Η ενέργεια δεν αναιρείται.`,
      deleteScreenFailed: "Αποτυχία διαγραφής οθόνης.",
      renameScreen: "Μετονομασία",
      saveScreen: "Αποθήκευση",
      savingScreen: "Αποθήκευση…",
      cancelScreenEdit: "Άκυρο",
      renameScreenFailed: "Αποτυχία μετονομασίας.",
      screenNameTaken: "Υπάρχει ήδη οθόνη με αυτό το όνομα.",
      tables: {
        title: "Θέσεις",
        description:
          "Πρόσθεσε τραπέζια, δωμάτια και ξαπλώστρες. Εμφανίζονται στον χάρτη σερβιτόρου και στα QR.",
        zoneHint:
          "Κάθε χώρος έχει δικό του εύρος αριθμών. Π.χ. Bar 1–10 δημιουργεί Bar-1 … Bar-10 — ξεχωριστός χώρος στο panel σερβιτόρου.",
        spacesBulkTitle: "Προσθήκη ανά χώρο",
        spacesBulkDesc:
          "Μία γραμμή για κάθε χώρο. Βάλε όνομα και εύρος (από–έως) — όχι όλα μαζί σε ένα batch.",
        spaceNameLabel: "Χώρος",
        spaceNameRequired: "Βάλε όνομα χώρου (π.χ. Bar, Σαλα).",
        spacePreview: (space: string, from: number, to: number, count: number) =>
          `Θα δημιουργηθούν ${count} θέσεις: «${space}-${from}» … «${space}-${to}»`,
        addSpaceRow: "Άλλος χώρος",
        addSpaceTables: "Προσθήκη",
        gridPreview: "Τι σημαίνουν τα χρώματα",
        gridHint: "Τα χρώματα ενημερώνονται live στον χάρτη σερβιτόρου — δεν τα ρυθμίζεις εδώ.",
        legendAutoNote:
          "Ρύθμισε τα μηνύματα, τα τμήματα και τις ζώνες από την κάρτα «Λειτουργία καταστήματος» παρακάτω.",
        qrLink: "Λήψη QR codes →",
        yourVenueSpots: (name: string, count: number) => `${name} — ${count} θέσεις`,
      },
      operations: {
        title: "Λειτουργία καταστήματος",
        description:
          "Ποιο τμήμα χρησιμοποιείς, γρήγορα μηνύματα στις οθόνες, ετικέτες χάρτη και ονόματα ζωνών.",
        loading: "Φόρτωση ρυθμίσεων…",
        departmentsTitle: "Ενεργά τμήματα",
        departmentsHint:
          "Πρόσθεσε όσα πόστα χρειάζεσαι (π.χ. Grill, Κήπος, Παραλία). Το όνομα εμφανίζεται στον σερβιτόρο, push και οθόνες.",
        postActiveLabel: "Ενεργό",
        postNameLabel: "Όνομα πόστου",
        postSpaceLabel: "Χώρος",
        postSpaceAll: "Όλοι οι χώροι",
        postTypeLabel: "Ρόλος",
        postTypeHint: "Ο ρόλος καθορίζει κινητό σερβιτόρου ή tablet (πάσος / μηνύματα).",
        postActionsLabel: "Ενέργειες",
        addPost: "Νέο πόστο",
        removePost: "Αφαίρεση πόστου",
        removePostConfirm: (name: string) =>
          `Αφαίρεση πόστου «${name}»; Τα μηνύματά του θα χαθούν. Η ενέργεια δεν αναιρείται.`,
        postsMaxReached: "Μέχρι 12 πόστα.",
        quickChipsTitle: "Γρήγορα μηνύματα",
        quickChipsHint: "Κουμπιά γρήγορης επιλογής στις οθόνες κουζίνας/μπαρ (tablet).",
        chipPlaceholder: "Νέο μήνυμα…",
        resetDefaults: "Προεπιλογές",
        mapLabelsTitle: "Μηνύματα χάρτη θέσεων",
        mapLabelsHint: "Τι βλέπει ο σερβιτόρος πάνω σε κάθε τραπέζι/θέση.",
        zonesTitle: "Ονόματα χώρων",
        zonesHint:
          "Οι χώροι δημιουργούνται από τα ονόματα θέσεων (π.χ. Αυλή-1). Άλλαξε εδώ πώς εμφανίζονται.",
        zonesPreviewTitle: "Προεπισκόπηση",
        zonesPreviewHint: "Έτσι εμφανίζονται στο «Διάλεξε χώρο» του σερβιτόρου — ενημερώνεται live.",
        zonesSourceLabel: "Πηγή",
        zonesNameLabel: "Όνομα χώρου",
        zonesCountLabel: "Θέσεις",
        save: "Αποθήκευση",
        saving: "Αποθήκευση…",
        reload: "Επαναφόρτωση",
        reloadDiscardConfirm:
          "Έχεις μη αποθηκευμένες αλλαγές. Να τις πετάξω και να φορτώσω ξανά από τον server;",
        saved: "Αποθηκεύτηκαν.",
      },
      services: {
        title: "Υπηρεσίες",
        description: "Link σερβιτόρου, push ειδοποιήσεις και ρυθμίσεις ειδοποιήσεων — κλήσεις πελάτη, παραγγελίες και φωνή.",
        pushSectionTitle: "Push ειδοποιήσεις",
        pushHint:
          "Ενεργοποίησε push σε αυτή τη συσκευή (π.χ. tablet manager). Ισχύει για όλα τα καταστήματα της επιχείρησης — Chrome/Safari, όχι Messenger ή Instagram.",
        staffPushHint:
          "Κάθε σερβιτόρος ενεργοποιεί push στο δικό του κινητό — ανοίγει το προσωπικό link και πατά «Ενεργοποίηση».",
        notifications: {
          title: "Ειδοποιήσεις",
          customerOrder: "Ενεργοποίηση παραγγελίας από πελάτη",
          waiterCall: "Ενεργοποίηση κλήσης σερβιτόρου",
          voiceMessages: "Ενεργοποίηση φωνητικών μηνυμάτων",
          voiceHint:
            "Η φωνή ακούγεται στα ελληνικά — με push και σε παρασκήνιο (τσέπη). Πάτα μία φορά την οθόνη όταν είναι ανοιχτή για να ξεκλειδώσει ο ήχος.",
          yes: "Ναι",
          no: "Όχι",
          saving: "Αποθήκευση…",
          saved: "Αποθηκεύτηκαν.",
        },
        staffLinksHint: "Links σερβιτόρων: Ρυθμίσεις → Προσωπικό (ένα link ανά άτομο).",
        minutesAgo: (n: number) => `πριν ${n} λεπ.`,
        tableLabel: (n: string) => `Τραπέζι ${n}`,
        historyTitle: "Ιστορικό πάσου",
        historyHint: "Παραδόσεις που ολοκληρώθηκαν — χρόνος από «έτοιμο» μέχρι «παρέδωσα».",
        historyDaysLabel: "Περίοδος",
        historyDays7: "7 ημέρες",
        historyDays30: "30 ημέρες",
        historyDays90: "90 ημέρες",
        historyLoading: "Φόρτωση...",
        historyEmpty: "Δεν υπάρχουν παραδόσεις σε αυτή την περίοδο.",
        historyFailed: "Δεν φορτώθηκε το ιστορικό. Δοκίμασε ξανά.",
        historyColSpot: "Θέση",
        historyColStation: "Τμήμα",
        historyColMessage: "Σχόλιο",
        historyColReady: "Έτοιμο",
        historyColDuration: "Διάρκεια",
      },
      live360Guide: {
        title: "Ρύθμιση Live 360°",
        subtitle: "5 βήματα — μετά δοκίμασε από Οθόνες",
        progress: (done: number, total: number) => `${done}/${total} έτοιμα`,
        allDone: "Η ρύθμιση Live 360° ολοκληρώθηκε.",
        openScreens: "Άνοιγμα Οθονών →",
        invalidStaff: (n: number) =>
          n === 1
            ? "1 άτομο χωρίς έγκυρο πόστο — διόρθωσέ το στο Προσωπικό."
            : `${n} άτομα χωρίς έγκυρο πόστο — διόρθωσέ τα στο Προσωπικό.`,
        steps: {
          spaces: {
            label: "1. Χώροι & θέσεις",
            hint: "Τραπέζια, δωμάτια — Σάλα, Αυλή κ.λπ.",
          },
          posts: {
            label: "2. Πόστα",
            hint: "Κουζίνα, Bar — όχι ονόματα σερβιτόρων.",
          },
          messages: {
            label: "3. Μηνύματα",
            hint: "Chips ανά πόστο για tablet (π.χ. «Έλα πάσο»).",
          },
          screens: {
            label: "4. Οθόνες tablet",
            hint: "Ίδιο όνομα με το πόστο — links KDS/Bar.",
          },
          staff: {
            label: "5. Προσωπικό",
            hint: "Σερβιτόρος + χώρος ή πόστο tablet + link.",
          },
        },
      },
      nameLabel: "Όνομα",
      roleLabel: "Ρόλος",
      save: "Αποθήκευση ρυθμίσεων",
      saving: "Αποθήκευση...",
      appearanceTitle: "Εμφάνιση καταλόγου",
      appearanceDesc: "Logo, χρώματα και στοιχεία που βλέπουν οι πελάτες από το QR.",
      venueNameLabel: "Όνομα καταστήματος",
      taglineLabel: "Μικρή περιγραφή (προαιρετικό)",
      taglineHint: "Μία γραμμή για το QR — π.χ. «Με θέα στη θάλασσα». Ο τύπος κουζίνας επιλέγεται ξεχωριστά.",
      descriptionLabel: "Περιγραφή",
      primaryColor: "Κύριο χρώμα",
      secondaryColor: "Δευτερεύον",
      needVenueFirst: "Φτιάξε πρώτα κατάστημα για να ρυθμίσεις χρώματα και εμφάνιση.",
    },
    newVenue: {
      title: "Νέο κατάστημα",
      description: "Το εστιατόριο, bar ή ξενοδοχείο σου. Θα δημιουργηθεί αυτόματα ο πρώτος κατάλογος.",
      nameLabel: "Όνομα καταστήματος *",
      taglineLabel: "Μικρή περιγραφή (προαιρετικό)",
      taglineHint: "Π.χ. «Pool bar & restaurant στη Ρόδο» — όχι ο τύπος κουζίνας.",
      descriptionLabel: "Περιγραφή (προαιρετικό)",
      submit: "Δημιουργία καταστήματος",
      submitting: "Δημιουργία...",
    },
  },
  onboarding: {
    guideLabel: "Οδηγός εκκίνησης",
    guideIntro: "Ολοκλήρωσε 4 βήματα εδώ — ίδια ροή σε δοκιμή, Basic και Pro. Μετά ανοίγει όλο το panel.",
    navLockedHint: "Ολοκλήρωσε πρώτα τα βήματα εκκίνησης (Επισκόπηση)",
    lockBanner: (step: number, label: string) =>
      `Βήμα ${step}/4: ${label} — οι υπόλοιπες σελίδες κλειδώνονται μέχρι να τελειώσεις.`,
    backToGuide: "Πήγαινε στον οδηγό",
    retryFromStart: "Ξαναδοκιμή από την αρχή",
    retryConfirmTitle: "Νέα εκκίνηση;",
    retryConfirmDesc:
      "Θα διαγραφεί το κατάστημα και ο κατάλογος που έφτιαξες μέχρι τώρα. Θα ξεκινήσεις ξανά από βήμα 1.",
    retryConfirming: "Διαγραφή…",
    qrPageHint: "Κατέβασε ή δες τα QR εδώ. Όταν τελειώσεις, γύρνα στην Επισκόπηση για το τελευταίο βήμα.",
    stepTitle: (step: number) => `Βήμα ${step} από 4 — φτιάξε τον κατάλογο σου`,
    subtitle: "Σε λιγότερο από μία ώρα μπορείς να έχεις QR menu στα τραπέζια σου.",
    completed: (n: number) => `${n}/4 ολοκληρωμένα`,
    nextStep: "Επόμενο βήμα",
    backStep: "Προηγούμενο",
    stepOf: (current: number) => `Βήμα ${current} από 4`,
    stepHeading: (step: number, label: string) => `Βήμα ${step}: ${label}`,
    stepLabels: ["Κατάστημα", "Κατάλογος", "QR", "Έτοιμο"] as string[],
    stepStatusDone: "Ολοκληρώθηκε",
    stepStatusCurrent: "Τώρα εδώ",
    stepStatusPending: "Επόμενο",
    done: "Ολοκληρώθηκε",
    pending: "Σε αναμονή",
    previewIntro: "Δες πώς φαίνεται στους πελάτες:",
    openCatalog: "Άνοιγμα καταλόγου",
    steps: {
      venue: {
        title: "Άνοιξε το κατάστημά σου",
        desc: "Δώσε όνομα στο μαγαζί σου — εστιατόριο, bar ή ξενοδοχείο. Π.χ. «Marine Hotel» ή «Ταβέρνα του Γιώργου».",
        cta: "Άνοιξε κατάστημα",
      },
      menu: {
        title: "Φτιάξε τον κατάλογο",
        titleSeeded: "Ο κατάλογος σου είναι έτοιμος",
        descWithCategory: "Πρόσθεσε ή άλλαξε είδη, τιμές και φωτογραφίες. Μπορείς και εισαγωγή PDF (Pro).",
        descSeeded:
          "Σου βάλαμε δείγματα πιάτα για να ξεκινήσεις. Μπορείς να τα αλλάξεις αργότερα από τον Κατάλογο.",
        descWithoutCategory:
          "Φτιάξε κατηγορίες (Σαλάτες, Κυρίαρκα, Ποτά...) και βάλε τουλάχιστον ένα είδος με τιμή.",
        cta: "Μπες στον κατάλογο",
        ctaContinue: "Συνέχεια στα QR",
        acknowledging: "Λίγο ακόμα...",
        seedFailed: "Δεν αποθηκεύτηκε ο κατάλογος. Δοκίμασε ξανά ή στείλε μας μήνυμα.",
      },
      qr: {
        title: "Βγάλε QR codes",
        desc: "Κατέβασε ένα QR για όλον τον κατάλογο και τύπωσέ το όπου θες.",
        cta: "Δες τα QR codes",
        ctaContinue: "Συνέχεια",
        acknowledging: "Λίγο ακόμα...",
        failed: "Δεν αποθηκεύτηκε το βήμα. Δοκίμασε ξανά ή στείλε μας μήνυμα.",
      },
      done: {
        title: "Συγχαρητήρια!",
        desc: "Ο κατάλογος σου είναι online. Πάτα Εντάξει για να ανοίξει το panel.",
        summaryVenue: "Κατάστημα",
        summaryCuisine: "Κουζίνα",
        summaryDescription: "Περιγραφή",
        summaryCatalog: "Κατάλογος",
        summaryItems: (n: number) => `${n} ${n === 1 ? "είδος" : "είδη"}`,
        summaryMenus: (n: number) => `${n} ${n === 1 ? "κατάλογος" : "κατάλογοι"}`,
        summaryLink: "Link QR menu",
        summaryQr: "QR codes — έτοιμα για εκτύπωση",
        cta: "Εντάξει",
        confirming: "Λίγο ακόμα...",
        failed: "Δεν ολοκληρώθηκε η εκκίνηση. Δοκίμασε ξανά ή στείλε μας μήνυμα.",
      },
    },
  },
  overview: {
    titleFallback: "Επισκόπηση",
    heroEyebrow: "Επισκόπηση",
    metricsTitle: "Στατιστικά",
    addFirstVenue: "Πρόσθεσε το πρώτο",
    addToCatalog: "Πρόσθεσε στον κατάλογο",
    quickActions: "Γρήγορες ενέργειες",
    actionVenue: "Ρύθμισε το κατάστημά σου",
    actionCatalog: "Είδη, τιμές & κατηγορίες",
    actionQr: "QR για τραπέζια & δωμάτια",
    actionScreens: "Κλήσεις πελάτη & live πάσο",
    actionPreview: "Όπως το βλέπει ο πελάτης",
    actionHistory: "Ιστορικό παραδόσεων πάσου",
    actionBilling: "Πλάνο & συνδρομή",
    quickStartEmpty:
      "Ξεκίνα προσθέτοντας κατηγορίες και είδη — μετά βγάλε QR για τα τραπέζια σου.",
    quickStartReady: "Ο κατάλογος σου είναι online! Βγάλε QR ή δες τις κλήσεις από πελάτες.",
    catalogLiveStatus: "Online",
    callsWaiterSuffix: "σερβιτόρου",
    renewalUntil: "Ανανέωση έως",
    planField: "Πλάνο",
    catalogOne: "κατάλογος",
    catalogMany: "κατάλογοι",
    passToday: "Πάσο σήμερα",
    passTodayHint: "Ειδοποιήσεις από κουζίνα/μπαρ",
    passAvgDelivery: "Μέσος χρόνος παραλαβής",
    passAvgDeliveryHint: "Έτοιμο → παραδόθηκε, τελευταίες 7 ημέρες",
    passAvgNone: "—",
    passAvgMinutes: (n: number) => `${n} λεπ.`,
    planSummary: (plan: string, venueN: number, venueWord: string, menuN: number, menuWord: string, items: string) =>
      `Πλάνο: ${plan} · ${venueN} ${venueWord} · ${menuN} ${menuWord} · ${items}`,
  },
  menuEditor: {
    noVenueTitle: "Δεν έχεις ακόμα κατάστημα",
    noVenueDesc:
      "Πρώτα φτιάξε το κατάστημά σου (εστιατόριο, bar ή ξενοδοχείο) και μετά πρόσθεσε είδη στον κατάλογο.",
    onboardingReadOnlyBanner:
      "Ο κατάλογος είναι μόνο για προβολή μέχρι να ολοκληρώσεις την εκκίνηση — άλλαξέ τον μετά από την Επισκόπηση.",
    categoryNew: "Νέα κατηγορία",
    categoryHint: "Μόνο ελληνικά — EN / DE / FR δημιουργούνται αυτόματα για το QR menu",
    addCategory: "Προσθήκη κατηγορίας",
    addingCategory: "Προσθήκη...",
    categoryLabel: "Κατηγορία",
    renameCategory: "Μετονομασία κατηγορίας",
    deleteEmptyCategory: "Διαγραφή κενής κατηγορίας",
    deleteCategoryConfirm: "Διαγραφή της κατηγορίας;\n\nΕίσαι σίγουρος; Η ενέργεια δεν αναιρείται.",
    invalidPrice: "Βάλε έγκυρη τιμή (π.χ. 4.50).",
    categoryNameRequired: "Βάλε όνομα κατηγορίας.",
    loadingSubtitle: "Φόρτωση κατηγοριών και ειδών",
    syncCatalogHint: "Ίδια επιλογή και στην εισαγωγή PDF — τα είδη εμφανίζονται εδώ.",
    editPrice: "Αλλαγή τιμής",
    qrBadge: "Ετικέτα στο QR menu",
    active: "Ενεργό",
    inactive: "Ανενεργό",
    remove: "Αφαίρεση",
    saving: "Αποθήκευση...",
    emptyCategories: "Δεν υπάρχουν κατηγορίες. Πρόσθεσε την πρώτη παραπάνω για να ξεκινήσεις.",
    autoTranslateHint: "Μόνο ελληνικά — EN / DE / FR δημιουργούνται αυτόματα για το QR menu",
    qrExtrasTitle: "Επιλογές πελάτη",
    qrExtrasHint:
      "Ο πελάτης τις επιλέγει στο QR menu. Προαιρετικά βάλε extra χρέωση (π.χ. +€1,50).",
    qrExtrasCount: (n: number) => `${n} επιλογές QR`,
    noBadge: "Χωρίς ετικέτα",
    extraChargePlaceholder: "Extra χρέωση (προαιρετικό)",
    addExtraOption: "Προσθήκη επιλογής",
    cancel: "Ακύρωση",
    itemDescription: "Περιγραφή πιάτου",
    itemDescriptionHint:
      "Εμφανίζεται στην κάρτα QR (1–2 γραμμές). Αν μείνει κενό, η κάρτα δείχνει μόνο όνομα και τιμή — δεν χαλάει η διάταξη.",
    itemIngredients: "Συστατικά (προαιρετικό)",
    itemIngredientsPlaceholder: "π.χ. ντομάτα, αγγούρι, ελαιόλαδο, φέτα",
    dietaryTagsTitle: "Διατροφικές ετικέτες",
    dietaryTagsHint: "Εμφανίζονται ως μικρές ετικέτες κάτω από την περιγραφή στο QR menu.",
    allergenCodesTitle: "Αλλεργιογόνα",
    allergenCodesHint: "Επίλεξε όσα περιέχει το πιάτο — εμφανίζονται στο QR menu.",
  },
  flash: {
    close: "Κλείσιμο",
    genericError: "Κάτι πήγε στραβά.",
    success: "Επιτυχία!",
    codes: {
      subscription_inactive: "Η συνδρομή σου δεν είναι ενεργή. Αναβάθμισε για να συνεχίσεις.",
      trial_expired: "Η δοκιμαστική περίοδος έληξε.",
      unauthorized: "Συνδέσου ξανά.",
      forbidden: "Δεν έχεις δικαίωμα.",
      venue_limit: "Έφτασες το όριο καταστημάτων του πλάνου σου. Δες τα πλάνα στη Συνδρομή.",
      menu_limit: "Έφτασες το όριο καταλόγων του πλάνου σου. Δες τα πλάνα στη Συνδρομή.",
      item_limit: "Έφτασες το όριο ειδών του πλάνου σου. Δες τα πλάνα στη Συνδρομή.",
      not_found: "Δεν βρέθηκε.",
      enterprise_contact: "Επικοινώνησε μαζί μας για Enterprise τιμολόγηση.",
      stripe_not_configured: "Το σύστημα πληρωμών δεν είναι διαθέσιμο.",
      rate_limited: "Πολλές προσπάθειες. Δοκίμασε αργότερα.",
      bad_request: "Λάθος αίτημα.",
      invalid_input: "Μη έγκυρα στοιχεία.",
      password_mismatch: "Ο νέος κωδικός και η επιβεβαίωση δεν ταιριάζουν.",
      password_same: "Ο νέος κωδικός πρέπει να διαφέρει από τον τρέχοντα.",
      invalid_password: "Ο νέος κωδικός πρέπει να έχει τουλάχιστον 8 χαρακτήρες.",
      wrong_password: "Ο τρέχων κωδικός είναι λάθος.",
      slug_exists: "Το slug υπάρχει ήδη. Δοκίμασε άλλο όνομα.",
    } as Record<string, string>,
  },
  meta: {
    appSuffix: "MenuOS",
    overview: "Επισκόπηση",
    menus: "Κατάλογος",
    import: "Εισαγωγή από PDF",
    qr: "QR Codes",
    waiter: "Οθόνες",
    history: "Ιστορικό",
    billing: "Συνδρομή",
    settings: "Ρυθμίσεις",
    newVenue: "Νέο κατάστημα",
  },
  api: {
    badRequest: "Λάθος αίτημα.",
    invalidData: "Μη έγκυρα στοιχεία.",
    menuNotFound: "Ο κατάλογος δεν βρέθηκε.",
    venueNotFound: "Το κατάστημα δεν βρέθηκε.",
    categoryNotFound: "Η κατηγορία δεν βρέθηκε.",
    fillNameAndPrice: "Συμπλήρωσε όνομα και τιμή.",
    fillCategoryNameGr: "Συμπλήρωσε όνομα κατηγορίας (Ελληνικά).",
    invalidCategoryName: "Μη έγκυρο όνομα κατηγορίας.",
    categoryAdded: (name: string) => `Η κατηγορία «${name}» προστέθηκε.`,
    categoryRenamed: (name: string) => `Η κατηγορία μετονομάστηκε σε «${name}».`,
    categoryUpdated: "Η κατηγορία ενημερώθηκε.",
    categoryDeleted: "Η κατηγορία διαγράφηκε.",
    menuDeleted: "Ο κατάλογος διαγράφηκε.",
    allMenusDeleted: (stats: { menus: number; items: number }) =>
      stats.items > 0
        ? `Διαγράφηκαν ${stats.menus} κατάλογοι και ${stats.items} είδη. Έμεινε ένας κενός κατάλογος.`
        : `Διαγράφηκαν ${stats.menus} κατάλογοι. Έμεινε ένας κενός κατάλογος.`,
    venueSaved: "Οι ρυθμίσεις αποθηκεύτηκαν.",
    venueCreated: "Το κατάστημα δημιουργήθηκε! Πρόσθεσε τώρα κατηγορίες και είδη.",
    menuCreated: "Ο κατάλογος δημιουργήθηκε.",
    venueIdRequired: "Απαιτείται venueId.",
    invalidMenuData: "Μη έγκυρα στοιχεία καταλόγου.",
    slugExists: "Το slug υπάρχει ήδη. Δοκίμασε άλλο όνομα.",
    defaultMenuName: "Κύριος κατάλογος",
    spotAdded: "Η θέση προστέθηκε.",
    spotExists: "Η θέση υπάρχει ήδη.",
    spotsBulkAdded: (n: number) => `Προστέθηκαν ${n} θέσεις.`,
    import: {
      invalidDraft: "Έλεγξε κατηγορίες, ονόματα και τιμές πριν την εισαγωγή.",
      selectMenu: "Επίλεξε κατάλογο.",
      selectAtLeastOne: (one: string) => `Επίλεξε τουλάχιστον ένα ${one}.`,
      parseFound: (items: string, categories: number) =>
        `Βρέθηκαν ${items} σε ${categories} κατηγορίες. Έλεγξέ τα πριν την εισαγωγή.`,
      parseEmpty: (many: string) => `Δεν βρέθηκαν ${many} — δοκίμασε άλλο PDF ή πρόσθεσε χειροκίνητα.`,
      parseFailed: "Αποτυχία ανάγνωσης PDF. Δοκίμασε ξανά ή πρόσθεσε τον κατάλογο χειροκίνητα.",
      translateUnavailable: "Η μετάφραση AI δεν είναι διαθέσιμη ακόμα — συμπλήρωσε τα ελληνικά χειροκίνητα.",
      translateInvalidDraft: "Άκυρο προσχέδιο — ξανατρέξε την ανάλυση PDF.",
      translateNothingNeeded: "Δεν χρειάζεται μετάφραση — τα ονόματα είναι ήδη στα ελληνικά.",
      translateSuccess: (n: number) =>
        n === 1 ? "Μεταφράστηκε 1 όνομα στα ελληνικά." : `Μεταφράστηκαν ${n} ονόματα στα ελληνικά.`,
      translateFailed: "Η μετάφραση AI απέτυχε. Δοκίμασε ξανά ή συμπλήρωσε τα ελληνικά χειροκίνητα.",
      geminiQuotaExceeded: (used: number, limit: number) =>
        `Έφτασες το μηνιαίο όριο Gemini AI (${Math.round(used / 1000)}k / ${Math.round(limit / 1000)}k tokens). Δοκίμασε τον επόμενο μήνα ή επικοινώνησε μαζί μας.`,
      applySuccess: (items: string, categories: number) =>
        `Εισήχθησαν ${items} σε ${categories} κατηγορίες. Μπορείς να τα επεξεργαστείς (φωτο, τιμές) από τον κατάλογο.`,
    },
    pdf: {
      noFiles: "Επίλεξε τουλάχιστον ένα PDF.",
      tooMany: (max: number) => `Μέγιστο ${max} PDF ανά φορά.`,
      notPdf: (name: string) => `Το «${name}» δεν είναι PDF.`,
      tooLarge: (name: string) => `Το «${name}» είναι πολύ μεγάλο (max 10MB).`,
      readFailed: (name: string) =>
        `Αδυναμία ανάγνωσης «${name}». Το αρχείο μπορεί να είναι κλειδωμένο ή κατεστραμμένο.`,
      noText: (name: string, pageHint: string, ocrHint: string) =>
        `Το «${name}» δεν έδωσε αναγνωρίσιμο κείμενο${pageHint}.${ocrHint}`,
      ocrNoText: " Το OCR δεν βρήκε κείμενο — δοκίμασε άλλες σελίδες ή χειροκίνητη εισαγωγή.",
      ocrNotConfigured: " Για σαρωμένα PDF χρειάζεται ειδική ρύθμιση — δοκίμασε PDF με selectable κείμενο ή επικοινώνησε μαζί μας.",
      noPagesSelectedOcr:
        "Δεν βρέθηκε κείμενο στις επιλεγμένες σελίδες. Δοκίμασε «Προχωρημένα → Επιλογή σελίδων».",
      noPagesSelectedNoOcr:
        "Δεν βρέθηκε κείμενο στο PDF. Για σαρωμένα μενού δοκίμασε άλλο PDF ή επικοινώνησε μαζί μας.",
      pagesHint: (pages: number[]) => ` (σελίδες ${pages.join(", ")})`,
    },
  },
  subscriptionStatus: {
    TRIALING: "Δοκιμή",
    ACTIVE: "Ενεργή",
    PAST_DUE: "Καθυστέρηση πληρωμής",
    CANCELED: "Ακυρωμένη",
    trialActive: "Ενεργή δοκιμή",
    trialGrace: "Περίοδος παράτασης",
    trialExpired: "Ληγμένη",
    expiresOn: (date: string) => `Λήγει ${date}`,
    graceUntil: (date: string) => `Παράταση έως ${date}`,
    renewsOn: (date: string) => `Ανανέωση ${date}`,
    expiredOn: (date: string) => `Έληξε ${date}`,
  },
} as const;

export function planLabel(planId: string): string {
  return DASHBOARD_EL.planLabels[planId] ?? planId;
}

export function roleLabel(role: string): string {
  return DASHBOARD_EL.roleLabels[role] ?? role;
}
