/** English copy for the owner dashboard. */
export const DASHBOARD_EN = {
  venue: "Venue",
  venues: "Venues",
  menu: "Catalog",
  menus: "Catalogs",
  qrCodes: "QR codes",
  subscription: "Subscription",
  logout: "Log out",
  calls: "Calls",
  settings: "Settings",
  account: "Account",
  accountEmail: "Login email",
  changePassword: {
    title: "Change password",
    current: "Current password",
    new: "New password (min 8)",
    confirm: "Confirm new password",
    submit: "Save password",
    saving: "Saving…",
    success: "Password updated.",
  },
  addVenue: "Add venue",
  confirmDialog: {
    close: "Close",
    cancel: "Cancel",
    confirmDelete: "Delete",
    confirmContinue: "Continue",
  },
  editCatalog: "Edit catalog",
  livePreview: "Live preview",
  importPdf: "Import from PDF",
  importPdfButton: "PDF import",
  importPdfPro: "PDF import (Pro only)",
  loadingCatalog: "Loading catalog...",
  importWizard: {
    hint: "Upload a catalog PDF — digital + OCR. Review the report before importing.",
    hintWithGemini:
      "Upload a PDF — OCR, layout and translation with Gemini AI. Review before importing.",
    geminiBadge: "With Gemini AI",
    geminiPoweredSubtitle: "Layout, OCR and Greek names via Gemini AI",
    geminiProcessingDetail: "Gemini AI: layout, OCR & translation…",
    geminiStepDone: "Complete",
    analyzeButtonAi: "Analyze with Gemini AI",
    processingTitleGemini: "Analyzing with Gemini AI",
    processingTimerSeconds: (n: number) => `${n}s`,
    processingTimerMinutes: (m: number, s: number) => `${m}:${String(s).padStart(2, "0")}`,
    processingTimerHint: "Usually 30–90 sec · large PDFs up to 3 min",
    processingLongWaitHint:
      "Still working — large or scanned PDF. Please keep this page open.",
    processingActivity: {
      scan: [
        "Opening PDF…",
        "Scanning pages…",
        "Skipping covers & logos…",
        "Finding menu pages…",
      ],
      extract: [
        "Reading text…",
        "Detecting columns & prices…",
        "OCR on scanned pages…",
        "Checking catalog layout…",
      ],
      extractGemini: [
        "Gemini AI: reading layout…",
        "OCR & digital text…",
        "Finding dishes & prices…",
        "Checking page structure…",
      ],
      ai: [
        "Translating names to Greek…",
        "Checking Latin-only names…",
        "Gemini AI: categories & descriptions…",
        "Final translation pass…",
      ],
      parse: [
        "Grouping categories…",
        "Checking prices & currency…",
        "Checking duplicates…",
        "Building import draft…",
      ],
    } as Record<string, string[]>,
    processFlow: {
      scan: "Scan",
      analyze: "Analyze",
      report: "Report",
      review: "Review",
    },
    analyzeButton: "Analyze & preview",
    processingTitle: "Analyzing catalog PDF",
    processingTargetCatalog: (name: string) => `Import target: «${name}»`,
    processingTargetFull: (venue: string, catalog: string) =>
      `Import target: ${venue} · «${catalog}»`,
    pipeline: {
      scan: "Scanning PDF",
      extract: "Analyzing pages",
      extractWithGemini: "OCR & Gemini AI",
      ai: "Gemini AI",
      ocr: "Image OCR",
      parse: "Categories & items",
      done: "Done",
    },
    loadingScanFile: (file: string, page: number, total: number) =>
      `${file} — page ${page}/${total}`,
    loadingImport: "Importing to catalog...",
    loadingImportInto: (name: string) => `Importing into «${name}»…`,
    advancedTitle: "Advanced — page selection",
    advancedHint:
      "Covers/logos are skipped automatically. Change which pages are analyzed if something is missing.",
    pageKind: {
      digital: "Digital",
      scan: "OCR",
      cover: "Cover",
    },
    skipCoverFirst: "Cover / logo — skipped automatically",
    skipCoverLast: "Last page — likely back cover",
    skipLowText: "Little or no text",
    skipBanner: "First page — banner/logo",
    skipScan: "Image/scan — OCR",
    selectMenuPages: "Menu only",
    selectAll: "All",
    deselectAll: "None",
    reanalyze: "Re-analyze",
    visionRetrying: "AI analysis…",
    visionRetrySuccess: "AI analysis complete — review the results.",
    visionRetryNoImprovement:
      "AI analysis did not improve the result — review manually or try other pages.",
    visionRetryConfirm:
      "AI analysis will replace the draft (names, prices, selections). Continue?",
    translateRetrying: "Translating to Greek…",
    translateSuccess: (n: number) =>
      n === 1
        ? "Translated 1 name to Greek — review the results."
        : `Translated ${n} names to Greek — review the results.`,
    translateConfirm:
      "AI will translate English names to Greek (categories and items). Continue?",
    ocrUsed: (n: number) => (n === 1 ? "1 page via OCR" : `${n} pages via OCR`),
    badge: "PDF IMPORT",
    phaseUpload: "Upload PDF",
    phaseReview: "Report & review before import",
    needVenueTitle: "You need a venue first",
    selectCatalogAndPdf: "Select a catalog and at least one PDF.",
    activeCatalogTitle: "Import target",
    activeCatalogHint:
      "Same catalog as on the Catalogs page — everything you import from PDF goes here.",
    importTargetConfirm: (name: string) => `Items will be imported into «${name}».`,
    changeCatalogConfirm: (name: string) =>
      `Switch target to «${name}»?\n\nPDF items will be imported into this catalog — not the previous one.`,
    noMenuPagesScanDetail: "No menu pages found",
    noMenuPages:
      "No menu pages found. Open Advanced and select pages manually.",
    extractDetail: "Digital + OCR…",
    parseFailed: "Analysis failed. Try again or a smaller PDF.",
    previewPagesFirst: (btn: string) =>
      `Press «${btn}» first for page preview — or run analysis again.`,
    pageStats: (selected: number, digital: number, ocr: number, cover: number) =>
      `${selected} selected · ${digital} digital · ${ocr} OCR · ${cover} cover`,
    pageAlt: (page: number) => `Page ${page}`,
    pageNumber: (page: number, total: number) => `Pg. ${page}/${total}`,
    pdfFilesTitle: "PDF files (up to 10)",
    pdfFilesHint:
      "Digital PDF and scanned images (OCR). Covers/logos are skipped automatically.",
    dropzoneTitle: "Choose or drag PDF here",
    dropzoneHint: "Max 10MB per file",
    reviewSummary: (categories: number, itemsSelected: string) =>
      `${categories} categories · ${itemsSelected} selected`,
    reviewMeta: (files: number, withPrice: number, without: number) =>
      `From ${files} PDF · ${withPrice} with price · ${without} without price`,
    newAnalysis: "New analysis",
    afterImportHint:
      "After import, open the catalog to add photos, prices and availability.",
    importButton: (itemsSelected: string) => `Import ${itemsSelected}`,
    manualEditLink: "← Manual catalog editing",
    tableColItemGr: "Item (GR)",
    tableColEn: "EN",
    tableColPrice: "Price €",
    tableColNotes: "Notes",
    selectMinOneItem: (one: string) => `Select at least one ${one}.`,
    report: {
      title: "Analysis results",
      subtitle: "Review what we found in the PDF before it goes into your catalog",
      statCategories: "Categories",
      statCategoriesSub: (withItems: number, empty: number) =>
        `${withItems} with items · ${empty} empty`,
      statItems: "Items",
      statItemsSub: (selected: number) => `${selected} selected for import`,
      statPrices: "With price",
      statPricesSub: (without: number) =>
        without > 0 ? `${without} without price — fill them in` : "All have prices",
      statReady: "Ready?",
      statReadyYes: "Yes",
      statReadyNo: "Not yet",
      issuesTitle: "Issues & notes",
      issuesNone: "No major issues found — still check names and prices before importing.",
      ocrBadge: (n: number) => (n === 1 ? "1 OCR page" : `${n} OCR pages`),
      extractionPath: {
        digital: "Digital PDF",
        ocr: "OCR (scan)",
        hybrid: "Hybrid (digital + OCR)",
        vision: "Vision AI",
      },
      visionUsedBadge: (n: number) => (n === 1 ? "1 Vision AI page" : `${n} Vision AI pages`),
      visionHint:
        "This layout looks complex — review carefully or try «AI analysis» for better reading.",
      visionHintUnavailable:
        "This layout looks complex — review names and prices carefully before importing.",
      visionRetryButton: "AI analysis",
      visionRetrying: "Analyzing…",
      translateHint:
        "Names are in English — press «Translate to Greek» for automatic AI translation.",
      translateHintUnavailable:
        "Names appear to be in English — fill in Greek manually. Automatic AI translation is not enabled yet.",
      translateButton: "Translate to Greek",
      translateRetrying: "Translating…",
      nextStepsTitle: "What to do now",
      nextSteps: [
        "Uncheck categories or items you do not want imported.",
        "Fix names and prices in the fields — especially highlighted rows.",
        "When you are sure, press «Import to catalog».",
      ] as string[],
      issueNoItems: "No items found in the PDF.",
      issueNoItemsHint:
        "Try other pages in Advanced or another PDF. Scanned menus need OCR.",
      issueNoPrice: (n: number) =>
        n === 1 ? "1 item without price." : `${n} items without price.`,
      issueNoPriceHint: "Add a price or leave €0 — you can change it later in the catalog.",
      issueEmptyCategories: (n: number) =>
        n === 1 ? "1 empty category (no items)." : `${n} empty categories.`,
      issueEmptyCategoriesHint: "They will not be imported — hidden by default.",
      issueDuplicateCategories: (n: number) =>
        n === 1
          ? "1 category with possible duplicates."
          : `${n} categories with possible duplicates.`,
      issueItemWarnings: (n: number) =>
        n === 1 ? "1 item needs review." : `${n} items need review.`,
      issueItemWarningsHint: "See the Notes column — yellow price fields or short names.",
      issueNothingSelected: "No items selected.",
      issueNothingSelectedHint: "Check at least one item or category to import.",
      issueOcr: "The PDF is a scanned image — OCR was used.",
      issueOcrHint:
        "Names or prices may be missing or wrong. Review carefully before importing.",
    },
    editor: {
      toolbarTitle: "Edit draft",
      toolbarHint:
        "Each block is one category. If the PDF is in English, press «Translate to Greek» before importing.",
      searchPlaceholder: "Search item or category…",
      hideEmpty: "Hide empty categories",
      showIssuesOnly: "Issues only",
      selectAll: "Select all",
      deselectAll: "Deselect all",
      expandAll: "Expand all",
      collapseAll: "Collapse all",
      categoryLabel: "Category",
      categoryEnLabel: "Category in English (only if in the PDF)",
      uncategorizedHint:
        "These items were not matched to a section in the PDF. You can import them here and reorganize later in the catalog.",
      emptyCategory: "No items in this category",
      itemsCount: (selected: number, total: number) => `${selected}/${total} selected`,
      noResults: "No categories match your filters.",
      itemNameLabel: "Item name",
      itemNameEnLabel: "English name (only if in the PDF)",
      addEnglish: "+ Add English",
      priceLabel: "Price",
      issueBadge: "Review",
      includeCategory: "Include category in import",
      includeItem: "Include item in import",
    },
    importConfirmTitle: "Ready to import",
    importConfirmHint: (categories: number, items: string) =>
      `${categories} categories and ${items} will be added to your selected catalog.`,
  },
  previewCatalog: "Preview",
  newCatalogPlaceholder: "New catalog (e.g. Pool Bar)",
  addCatalog: "+ Catalog",
  deleteCatalog: "Delete catalog",
  deleteCatalogHasData: "You cannot delete a catalog that has categories or items.",
  deleteCatalogLast: "At least one catalog must remain for this venue.",
  deleteCatalogConfirm: (name: string) => ({
    variant: "destructive" as const,
    title: `Delete catalog «${name}»?`,
    note: "This cannot be undone.",
  }),
  deleteCatalogWithDataConfirm: (
    name: string,
    stats: { categories: number; items: number },
  ) => ({
    variant: "destructive" as const,
    eyebrow: "Warning",
    title: "Permanent deletion",
    description: `Catalog «${name}» will be deleted:`,
    bullets: [
      ...(stats.categories > 0
        ? [`${stats.categories} categor${stats.categories === 1 ? "y" : "ies"}`]
        : []),
      ...(stats.items > 0
        ? [`${stats.items} item${stats.items === 1 ? "" : "s"}`]
        : []),
    ],
    note: "We cannot restore them — this is permanent.",
  }),
  deleteAllCatalogs: "Delete all catalogs",
  deleteAllCatalogsConfirm: (stats: { menus: number; categories: number; items: number }) => ({
    variant: "destructive" as const,
    eyebrow: "Warning",
    title: "Permanent deletion",
    description: "All catalogs for this venue will be deleted:",
    bullets: [
      `${stats.menus} catalog${stats.menus === 1 ? "" : "s"}`,
      ...(stats.categories > 0
        ? [`${stats.categories} categor${stats.categories === 1 ? "y" : "ies"}`]
        : []),
      ...(stats.items > 0
        ? [`${stats.items} item${stats.items === 1 ? "" : "s"}`]
        : []),
    ],
    note: "We cannot restore them — this is permanent. You will get one empty catalog to start fresh.",
  }),
  roleLabels: {
    ADMIN: "Administrator",
    MANAGER: "Manager",
  } as Record<string, string>,
  planLabels: {
    TRIAL: "Free trial",
    BASIC: "Basic",
    PRO: "Pro",
    ENTERPRISE: "Enterprise",
  } as Record<string, string>,
  billing: {
    checkoutFailed: "Checkout could not start. Please try again.",
    cancelled: "Payment was cancelled. You were not charged.",
    confirming: "Confirming your payment...",
    confirmFailed: "Confirmation failed. If you were charged, email info@qrmenus.info.",
    activated: "Subscription activated. Thank you!",
    activatedDev: "Plan activated (dev mode).",
    inactiveTitle: "Active subscription required",
    inactiveGeneric:
      "Your subscription is not active. Choose a plan so customers can keep viewing your QR menu.",
    canceledInactive:
      "Your subscription was canceled. Choose a plan again — your catalog is saved.",
    staffNoCheckout: "Only an admin or manager can change the plan.",
    currentPlan: "Current plan",
    statusLabel: "Status",
    trialUntil: "Trial until",
    periodUntil: "Current period until",
    perMonth: "/month",
    currentPlanBtn: "Current plan",
    checkoutLoading: "Redirecting...",
    networkError: "Network error",
    enterpriseFallback: "Custom domain, white-label and priority support.",
    contactUs: "Contact us at",
    selectPlan: (name: string) => `Choose ${name}`,
    upgradeTo: (name: string) => `Upgrade to ${name}`,
    downgradeTo: (name: string) => `Downgrade to ${name}`,
    renewal: {
      title: "Automatic renewal",
      autoOn:
        "Your subscription renews automatically each month on the card you provided. Prefer to pay manually? You can turn this off — your current period stays active.",
      autoOff: (date: string) =>
        `Automatic renewal is off. Your current period ends ${date} — you will not be charged again unless you choose to pay.`,
      manualRenewHint:
        "After it ends you can pay again from this page. Your catalog stays saved.",
      stopButton: "Turn off automatic renewal",
      resumeButton: "Turn automatic renewal back on",
      stopConfirm:
        "Your subscription stays active until the end of the current period. After that there will be no automatic charge — you can pay again yourself from here.",
      saved: "Setting updated.",
      loading: "Saving…",
      networkError: "Network error",
    },
  },
  trial: {
    expired:
      "Your extension period has ended. Choose Basic or Pro — your catalog is saved and goes live again instantly.",
    endingSoon: (days: number) =>
      days === 1
        ? "Your free trial ends tomorrow. After that you get 7 extra days to choose a plan."
        : `Your free trial ends in ${days} days. Then you get 7 extra days — your menu stays online.`,
    bannerHealthy: (days: number, date: string) =>
      `Free trial — ${days} ${days === 1 ? "day" : "days"} left (until ${date})`,
    bannerMid: (days: number, date: string) =>
      `Trial in progress — ${days} ${days === 1 ? "day" : "days"} left (until ${date})`,
    bannerEnding: (days: number, date: string) =>
      `Trial ending soon — ${days} ${days === 1 ? "day" : "days"} (until ${date})`,
    bannerLastDay: "Your trial ends tomorrow — then 7 extra days to choose a plan",
    bannerGrace: (days: number, date: string) =>
      `Trial ended — ${days} ${days === 1 ? "day" : "days"} extension left (until ${date})`,
    bannerGraceLastDay: "Last day of your extension — choose a plan to keep your menu online",
    graceHint:
      "Your QR menu stays live. Choose Basic (€9.99) or Pro (€19.99) — your dishes are saved.",
    graceChoosePlan: "Choose a plan",
    graceUntil: (date: string) => `Extension until ${date}`,
    gracePromise: "After your trial ends we give you 7 extra days — your menu stays online.",
    setupHint: "1. Venue · 2. Catalog · 3. QR · 4. Done",
    choosePlan: "View plans",
    upgradeNow: "Upgrade now",
    welcomeBadge: "Trial started",
    welcomeTitle: "Welcome to MenuOS",
    welcomeEnds: (days: number, date: string) =>
      `You have ${days} days free trial — ends ${date}. No card required.`,
    welcomeEmailHint: "We sent you an email with next steps. You'll get a reminder before it ends.",
    limits: "Trial: 1 venue, 1 catalog, up to 50 items. Upgrade anytime.",
    limitsNear: (count: number) =>
      `You have ${count}/50 items on trial. Need more? View the plans.`,
    limitsNearCta: "View plans",
    endsOn: "Trial until",
  },
  planLimits: {
    seePlans: "See plans",
    catalogTrial:
      "The free trial includes 1 catalog per venue. For bar, pool, etc. see Basic or Pro.",
    catalogBasic: (max: number) => `The Basic plan allows up to ${max} catalogs per venue.`,
    catalogGeneric: (planName: string, max: number) =>
      `The ${planName} plan allows up to ${max} catalogs per venue.`,
    itemsTrial: "You've reached the 50-item trial limit. Upgrade for unlimited dishes.",
    itemsNearTrial: (count: number, max: number) =>
      `You have ${count}/${max} items on trial — you're close to the limit.`,
    itemsNearGeneric: (count: number, max: number) =>
      `You have ${count}/${max} items — you're close to your plan limit.`,
    itemsAtLimit: (max: number) => `You've reached your plan limit of ${max} items.`,
    venueTrial: "The free trial includes 1 venue. Upgrade for more locations.",
    venueAtLimit: (max: number) =>
      `Your plan allows up to ${max} ${max === 1 ? "venue" : "venues"}.`,
  },
  upgrade: {
    pdfImport: {
      title: "Bring your PDF into the catalog",
      lead:
        "On Pro you upload your printed menu — categories, items and prices fill in almost on their own. When the PDF is a scan or messy layout, Gemini AI steps in. You review everything before it goes live.",
      geminiBadge: "Gemini AI",
      steps: [
        "Upload a PDF — printed or digital",
        "Gemini AI for scans and tricky pages",
        "Edit and save — nothing goes live without your OK",
      ],
      cta: "Upgrade to Pro",
    },
    live360: {
      title: "Live 360° — kitchen, bar and waiters in sync",
      lead:
        "QR calls, live screens and order history run on Pro. They are not included on trial or Basic.",
      steps: [
        "Waiters see calls as they happen",
        "Kitchen and bar on Pass screens",
        "History so you know what happened each shift",
      ],
      cta: "Upgrade to Pro",
    },
  },
  proFeature: {
    live360: {
      title: "Live 360° — Pro only",
      description:
        "Waiter screens, delivery history and QR calls work on the Pro plan. Upgrade to coordinate kitchen, bar and waiters live.",
      staffDescription:
        "Live 360° (screens and calls) is available on Pro only. Ask your account admin to upgrade.",
      proBadge: "Pro only",
      upgrade: "Upgrade to Pro",
      back: "Back to overview",
    },
  },
  welcome:
    "Welcome to MenuOS! Follow the guide below: set up your venue, add items to the catalog, then generate QR codes for your tables.",
  venueCreated:
    "Venue created! Now add categories and items — or import from PDF if you have Pro.",
  catalogEntry: {
    label: "Items",
    one: "item",
    many: "items",
    count: (n: number) => `${n} ${n === 1 ? "item" : "items"}`,
    add: "Add item",
    new: "New item",
    save: "Save item",
    deleteConfirm: "Delete this item?\n\nAre you sure? This cannot be undone.",
    editTitle: "Edit item",
    deleteTitle: "Delete item",
    empty: "No items yet — add the first one.",
    categoryHasEntries:
      "You cannot delete a category that has items. Delete all items first.",
    categoryDeleteHint: "Delete all items in this category first",
    notFound: "Item not found.",
    invalidData: "Invalid item data.",
    deactivated: "Item deactivated.",
    updated: "Item updated.",
    deleted: "Item deleted.",
    added: (name: string) => `Item «${name}» added to the catalog.`,
  },
  waiter: {
    copied: "Copied!",
    newItems: "New items",
    needVenueFirst: "Create a venue first to receive calls from customers.",
    managerViewBadge: "View: entire venue",
    managerZoneViewBadge: (zone: string) => `View: ${zone}`,
    staffViewBadge: (name: string, zone: string | null, stations: string) =>
      zone ? `View: ${name} · ${zone} · ${stations}` : `View: ${name} · ${stations}`,
    assignedZoneHeading: "Your space",
    assignedZoneHint: "",
    zoneFilterAll: "All spaces",
    zonePickHeading: "Pick a space",
    zoneSpotCount: (n: number) => (n === 1 ? "1 spot" : `${n} spots`),
    zoneActiveCount: (n: number) => (n === 1 ? "1 active" : `${n} active`),
    zoneMessageCount: (n: number) => (n === 1 ? "1 message" : `${n} messages`),
    zonePendingBreakdown: (parts: string[]) =>
      parts.length > 0 ? `Waiting by space: ${parts.join(" · ")}` : "",
    whereToGoHeading: (n: number) =>
      n === 1 ? "1 message — go here:" : `${n} messages — go here:`,
    otherVenuePendingHint: (parts: string[]) =>
      parts.length > 0
        ? `Messages are at another venue: ${parts.join(" · ")}. Switch venue using the field above.`
        : "",
    otherVenuePendingPart: (name: string, n: number) => `${name} (${n})`,
    unmappedZoneLabel: (n: number) => (n === 1 ? "Other (1)" : `Other (${n})`),
    unmappedActiveHint: (n: number) =>
      n === 1
        ? "1 call/message with no clear zone — open «All areas» or check the table number."
        : `${n} calls/messages with no clear zone — open «All areas» or check table numbers.`,
    emptyZoneView: "No spots or activity in this space right now.",
    pendingCount: (n: number) => `${n} pending`,
    activeCount: (n: number) => (n === 1 ? "1 active" : `${n} active`),
    refreshHint: "Refreshes every 5 sec.",
    shiftLock: {
      lockButton: "Keep screen on",
      unlockButton: "Unlock",
      unlockButtonShort: "Off",
      promptTitle: "Shift mode",
      promptHint:
        "Tap to keep the screen and this panel active — sounds and calls work more reliably. Unlock when you are done.",
      lockedTitle: "Screen on",
      lockedHint: "Ready for calls.",
      fullscreenOn: "Full screen",
      unsupported: "Open from a home-screen icon (not a plain browser tab) for best results.",
    },
    staffSetup: {
      readinessLabel: "Ready for kitchen alerts",
      installedLabel: "Home screen",
      pushLabel: "Notifications",
      voiceLabel: "Voice",
      voiceOff: "Off",
      installButton: "Add to Home",
      pushButton: "Notifications",
      testButton: "Test sound",
      testPlaying: "Playing...",
      iosInstallTitle: "Add to Home Screen",
      iosStep1: "Tap the Share button (bottom centre).",
      iosStep2: "Choose “Add to Home Screen”.",
      iosStep3: "Open from the icon — it opens this waiter page, not the marketing homepage.",
      iosClose: "Got it",
      inAppWarning: "Open in Chrome or Safari — not from Messenger or Instagram.",
      pushDenied: "Notifications were blocked — change it in your phone settings.",
      pushUnsupported:
        "This browser does not support notifications. Use Chrome (Android) or Safari (iPhone).",
      allReady: "All set — you will hear kitchen pass alerts.",
      compactReadyLabel: "Ready",
      doneButton: "Done — start",
      testAriaLabel: "Test sound",
    },
    loadFailed: "Could not load calls. Refresh the page or open the link from the dashboard again.",
    sessionExpired: "Session expired — open the waiter link from the dashboard again.",
    emptyTitle: "No active calls",
    emptyDesc:
      "When a customer places an order, calls the waiter or requests the bill from the QR menu, it will appear here.",
    emptySpotsActiveHint:
      "No spots configured — active calls appear below. Set up tables/rooms in Settings → Spots.",
    unmappedSpotBadge: "Unconfigured",
    goButton: "Accept",
    completeButton: "Done",
    orderTotal: "Total",
    callStatus: {
      PENDING: "Pending",
      ACKNOWLEDGED: "In progress",
      COMPLETED: "Completed",
      CANCELED: "Canceled",
    },
    callType: {
      WAITER: "Waiter call",
      BILL: "Bill",
      ORDER: "Order",
    },
    passSection: "Department pass",
    passEmpty: "No active pass notifications.",
    passCount: (n: number) => `${n} pass`,
    passNewMessage: "New message",
    passPickedUp: "OK",
    passDelivered: "Done",
    passStatus: {
      READY: "Ready",
      PICKED_UP: "In progress",
      DELIVERED: "Done",
    },
    passStation: {
      kitchen: "Kitchen",
      bar: "Bar",
      cold: "Cold",
      dessert: "Dessert",
    },
    passReadyLabel: {
      kitchen: "Ready — kitchen",
      bar: "Ready — bar",
      cold: "Ready — cold",
      dessert: "Ready — dessert",
    },
    tableGridTitle: "Spot map",
    tableGridLegendHint: "Status is shown on each card.",
    tableGridLegendAutoNote: "Labels update automatically — no setup needed.",
    tableStateLabels: {
      idle: "Quiet",
      guest_call: "Guest call",
      kitchen_ready: "Kitchen ready",
      cold_ready: "Cold ready",
      bar_ready: "Bar ready",
      both: "Multiple",
    },
  },
  push: {
    title: "Notifications on this device",
    checking: "Checking notifications...",
    description:
      "Get notified when a waiter call or order arrives — even if the page is closed.",
    subscribed: "Notifications are enabled on this device.",
    denied: "Notifications were blocked by the browser. Change it in your phone settings.",
    enable: "Enable",
    disable: "Disable",
    enableSuccess: "Success — notifications are enabled on this device.",
    enableFailed: "Failed. Try again or open the link in Chrome/Safari.",
    unsupported:
      "This browser (e.g. Messenger, Instagram, WhatsApp) does not support push notifications. Open the link in Chrome (Android) or Safari (iPhone).",
    disabledServer: "Push notifications are not configured on the server — contact support.",
    inAppBrowser:
      "It looks like you opened the link inside Messenger or another app. For push: tap ⋮ → Open in Chrome or send the link to yourself and open it there.",
    iosHint:
      "iPhone: Open in Safari (not Messenger). Tap Enable → Allow notifications. For best results: Add to Home Screen.",
    androidHint:
      "Android: Open in Chrome (not Messenger). Tap Enable and allow notifications when prompted.",
    pageOpenHint: "With the page open you see calls live — no push needed.",
    compactInApp: "Open in Chrome/Safari — not from Messenger.",
    compactPrompt: "Push for sound when the screen is off or locked.",
    compactSubscribed: "Push on",
    iosBrowserUnsupported:
      "iPhone: Open in Safari → Add to Home Screen. Push and voice work there. Chrome on iPhone does not support push.",
    managerHint:
      "You'll receive push for calls and pass from all venues in your organization on this device.",
  },
  cuisineType: {
    label: "Cuisine type",
    hint: "Customers see this on the QR menu — e.g. Mediterranean, Gourmet, Italian.",
    unsetOption: "Choose cuisine type…",
    options: {
      MEDITERRANEAN: "Mediterranean",
      GREEK: "Greek",
      ITALIAN: "Italian",
      GOURMET: "Gourmet",
      SEAFOOD: "Seafood",
      GRILL: "Grill",
      CAFE_BAR: "Café & bar",
      ASIAN: "Asian",
      INTERNATIONAL: "International",
      VEGETARIAN: "Vegetarian / vegan",
      OTHER: "Other",
    },
  },
  photos: {
    label: "Photo (optional)",
    logoLabel: "Venue logo",
    logoHint: "Shown on the QR menu next to the name. Square or round PNG/JPG — ideally 200×200 px.",
    logoSaveHint: "After upload, tap Save settings for it to appear on the menu.",
    uploadButton: "Upload from phone/computer",
    uploading: "Uploading...",
    uploadHint: "JPG or PNG up to 5 MB — optimized automatically for the menu.",
    uploadFailed: "Upload failed.",
    urlPlaceholder: "or paste photo URL",
    urlOptional: "or paste photo URL",
    urlOnlyHint: "Without a photo it appears as a clean row on the menu.",
    remove: "Remove",
  },
  layout: {
    tagline: "Menu management",
    welcome: "Welcome",
    subscriptionPrefix: "Subscription",
  },
  nav: {
    overview: "Overview",
    waiter: "Screens",
    history: "History",
    qrShort: "QR",
    callsShort: "Screens",
    proOnlyBadge: "Pro only",
  },
  pages: {
    menus: {
      title: "Catalog",
      description: "Add categories and items — multiple languages are supported on the QR menu.",
    },
    import: {
      title: "Import from PDF",
      description:
        "Upload a PDF menu — review results before saving to the catalog.",
      backToCatalog: "← Back to catalog",
    },
    qr: {
      title: "QR Codes",
      descriptionBasic:
        "One link and one QR for your whole catalog — print it anywhere you like.",
      descriptionPro:
        "Download or preview QR for each spot. Configure spots in Settings → Spots.",
      description:
        "Download or preview QR for each spot. Configure spots in Settings → Spots.",
      catalogTitle: "Catalog QR",
      catalogDesc:
        "Customers scan and see your menu. One QR for the whole venue — no tables required.",
      catalogLinkLabel: "Catalog link",
      configureSpotsLink: "Configure tables →",
      configureSpotsEmpty: "No spots yet. Set them up in Settings → Spots.",
      needVenueTitle: "You need a venue first",
      needVenueDesc: "Create a venue and add items before generating QR codes.",
      emptyCatalogTitle: "Catalog is empty",
      emptyCatalogBeforeLink: "Add items to the",
      catalogLink: "catalog",
      emptyCatalogAfterLink: "before sharing QR codes.",
      emptyCatalogAfterLinkCustomers: "before sharing QR codes with customers.",
      settingsTitle: "QR settings",
      settingsDesc:
        "Each QR opens the online catalog. Add a table or room number — so you know where calls come from.",
      tableLabel: "Table (optional)",
      roomLabel: "Room (optional)",
      defaultLangLabel: "Default QR language",
      generating: "Generating...",
      updateQr: "Update QR",
      downloadPng: "Download PNG",
      openCatalog: "Open catalog",
      generatedSuccess: "QR created! Download or print it.",
      spotsTitle: "Tables, rooms & sunbeds",
      zonesDesc:
        "Expand each space to see QR per table — view, download or test the link.",
      spotsDesc:
        "Add each spot once. Each QR binds the number — the waiter sees exactly where calls come from.",
      spotTypeLabel: "Type",
      bulkTitle: "Bulk add",
      bulkDesc:
        "Add as many tables, rooms or sunbeds as you need — no plan limit. Up to 200 spots at a time (repeat with a new range for more). Optional prefix for zones (e.g. Patio-, Floor-).",
      prefixLabel: "Prefix (optional)",
      fromLabel: "From",
      toLabel: "To",
      bulkAdding: "Adding...",
      bulkAddAll: "Add all",
      spotNameLabel: "Number / name",
      spotPlaceholderRoom: "204 or vip-1",
      spotPlaceholderSunbed: "A12 or beach-3",
      spotPlaceholderTable: "12 or patio-1",
      addSpot: "Add",
      yourSpots: (count: number) => (count > 0 ? `Your spots (${count})` : "Your spots"),
      loadingSpots: "Loading...",
      emptySpots: "No spots yet. Add per space (e.g. Bar 1–10, Hall 1–20).",
      saveSpot: "Save",
      cancelEdit: "Cancel",
      editSpot: "Edit",
      deleteSpotLabel: "Delete",
      deleteSpotConfirm: (name: string) =>
        `Delete spot «${name}»?\n\nIf you already printed the QR, it will stop working. This cannot be undone.`,
      renameQrWarning: "Renaming changes the QR URL — reprint the QR if needed.",
      invalidRange: "Enter a valid range from 1 to 999 (e.g. from 1 to 120).",
      bulkLimit: "Maximum 200 spots at a time. For more, run a second batch (e.g. 201–400).",
      invalidPrefix: (hint: string) => `Invalid prefix. ${hint}`,
      labelHint: "Letters, numbers, hyphen and underscore only (e.g. 12, patio-1).",
      previewSpot: "Preview",
      showQr: "Show QR",
      hideQr: "Hide",
      loadingQr: "Loading QR…",
      spotTypes: {
        TABLE: "Table",
        ROOM: "Room",
        SUNBED: "Sunbed",
      } as Record<string, string>,
    },
    waiter: {
      title: "Screens",
      description:
        "Live spot map and guest calls — updates automatically. Staff links are set in Settings → Staff.",
      setupLink: "Settings → Staff",
    },
    billing: {
      title: "Subscription",
      description: "Manage your MenuOS subscription. Payments are processed securely online.",
    },
    history: {
      title: "History",
      description:
        "Completed pass deliveries — time from ready to delivered, filterable by spot, department and waiter.",
      daysLabel: "Period",
      days7: "7 days",
      days30: "30 days",
      days90: "90 days",
      filterSpot: "Spot",
      filterStation: "Department",
      filterStaff: "Waiter",
      filterAll: "All",
      loading: "Loading...",
      empty: "No deliveries match these filters.",
      failed: "Could not load history. Try again.",
      colSpot: "Spot",
      colStation: "Department",
      colMessage: "Comment",
      colReady: "Ready",
      colDuration: "Duration",
      colStaff: "Waiter",
      colDelivered: "Delivered",
    },
    settings: {
      title: "Settings",
      description: "Posts, spots, messages and staff — all in one place.",
      tabs: {
        general: "Account",
        staff: "Staff",
        posts: "Posts",
        venue: "Venue",
        messages: "Messages",
        tables: "Tables",
        spaces: "Spaces",
      },
      postsTab: {
        title: "Posts",
        description:
          "Define who does what — cook, waiter, bar, etc. The name appears on staff links, push and tablets.",
        hint: "Up to 12 posts — e.g. Kitchen, Bar, Services. Role sets pass tablet vs waiter.",
        postNamePlaceholder: "e.g. Kitchen, Bar, Services",
        postSpaceLabel: "Space",
        postSpaceAll: "All spaces",
        postTypeHint:
          "Kitchen/Bar = pass tablet · Waiter = phone · Dishwash/Cleaning/General = messages tablet.",
        waiterNameWarning:
          "Waiter-like name with Kitchen/Bar role — switch role to Waiter or rename the post.",
        linkedTitle: "Where posts connect",
        linkedWaiterNote:
          "Floor waiters = post with role Waiter here (e.g. Dining room). Then assign staff in the Staff tab.",
        linkedTablet: (postName: string, stationName: string) =>
          `«${postName}» (${stationName}) → Messages + tablet in Staff`,
        nextMessagesLink: "Messages →",
        nextStaffLink: "Staff →",
        saved: "Saved.",
        savedNextSteps:
          "Saved. Next: add messages per post and assign employees in Staff.",
        junkRemovedHint:
          "Removed a post with wrong role — for waiters choose role Waiter.",
        placeholderNameWarning:
          "Enter a name (e.g. Kitchen) — «New post» does not appear in Staff.",
        placeholderRemovedHint:
          "Removed an unnamed post — rename it before saving or delete the row.",
      },
      screensTab: {
        title: "Tablet screens",
        description:
          "Links for kitchen/bar tablets — opens without login. Staff tab links point here.",
        hint: "Screen name should match the post name (e.g. «Grill»).\nFor a second kitchen line: add a screen named like the post.",
        stationLabels: {
          kitchen: "Kitchen",
          bar: "Bar",
          cold: "Cold",
          dessert: "Dessert",
        },
      },
      linksTab: {
        title: "Staff links per space",
        description:
          "Each space has its own link and QR — send to staff (e.g. patio waiters, hall waiters).",
        hint: "Scanning the QR or opening the link shows only their space.\nIf you rotate the access code, update all links/QR codes.",
        loading: "Loading spaces…",
        empty: "No spaces yet. Add them in the «Spaces» tab.",
        spacesTabLink: "Go to Spaces →",
        noStaffToken: "No access link found for this venue.",
        spotCount: (n: number) => `${n} spots`,
        openLink: "Open link",
        copyLink: "Copy link",
        downloadQr: "Download QR",
        loadingQr: "QR…",
      },
      messagesTab: {
        title: "Messages",
        description:
          "One card per post — add messages, then Save at the bottom. (Posts → Posts tab first)",
        hint: "",
        byPostTitle: "Messages by post",
        byPostHint: "",
        selectPostLabel: "Choose post",
        addMessage: "Add",
        messageCount: (n: number) => (n === 1 ? "1 message" : `${n} messages`),
        messagePlaceholder: "Type your message…",
        messageSaveHint:
          "Press Save at the bottom. To show on the tablet, assign the same post in Staff — not «Waiter».",
        passTabletStaffHint: (postName: string) =>
          `Pass tablet: in Staff, assign post «${postName}» (not «Waiter» — they receive alerts on phone).`,
        assignInStaffLink: "Staff →",
        noPostsHint: "You have no active posts.",
        servicesPostTitle: "Waiter — spot map",
        servicesPostHint: "Map labels (guest call, kitchen ready, etc.) — not a pass tablet.",
        passPostHint: "Add the messages you want for this post — one at a time.",
        messagesForPost: (postName: string) =>
          `Messages the «${postName}» post can send from tablet (e.g. cook, bar).`,
        messagesListLabel: "Messages",
        previewLabel: "Preview",
        previewEmpty: "No messages added yet.",
        resetPostMessages: "Clear messages",
        postColorLabel: "Post colour",
        addPost: "New post",
        addMapMessage: "Add message",
        addMapMessagePlaceholder: "Choose…",
        removeMessage: "Remove message",
        managePostsLink: "Manage posts →",
      },
      venueTab: {
        title: "Venue",
        description: "Name, colours and logo — what guests see on the QR menu.",
      },
      generalTab: {
        googleReview: {
          title: "Google Reviews",
          description:
            "Paste your Google Business review link — it appears at the end of the QR menu.",
          urlLabel: "Google review link",
          urlPlaceholder: "https://g.page/r/... or link from Google Maps",
          urlHint:
            "Google Business → Reviews → “Get more reviews” → copy the link.",
          save: "Save",
          saving: "Saving…",
        },
      },
      tablesTab: {
        title: "Tables",
        description:
          "Pick a space, say how many tables it has, and create them. Each space is separate — expand to view or delete.",
        hint:
          "One space = one number range (e.g. Patio 1–20).\nWith 100+ tables, spaces stay collapsed — expand only when you need them.",
        createTitle: "New space with tables",
        createDesc: "Choose space type, name (if needed) and number range.",
        createSpace: "Create space",
        creating: "Creating…",
        createPreview: (space: string, from: number, to: number, count: number) =>
          `${count} spots will be created in «${space}» (${from}–${to}).`,
        listTitle: "Your spaces",
        listDesc: "Tap a space to see its tables. Deleting a space removes all its tables.",
        spotCount: (n: number) => `${n} tables`,
        addMoreTitle: "Add more to this space",
        addMore: "Add",
        expandAll: "Expand all",
        collapseAll: "Collapse all",
        loading: "Loading…",
        empty: "No spaces yet.",
        emptyHint: "Use the form above for your first space — e.g. Hall 1–30.",
        emptyZone: "No tables in this space.",
        renameHint: "To rename how a space appears to waiters:",
        spacesTabLink: "Manage spaces →",
      },
      spacesTab: {
        title: "Spaces",
        description:
          "Spaces the waiter sees — Tables, Patio, Floor, Sunbeds, Rooms.",
        hint: "Add, rename or delete spaces. For individual tables/spots, use the «Tables» tab.\nZone QR codes are at the bottom — for per-person links, use «Staff».",
        previewTitle: "Preview",
        previewHint: "This is how they appear in the waiter «Pick a space» panel.",
        empty: "No spaces yet. Tap «New space» to get started.",
        spotCount: (n: number) => `${n} spots`,
        addSpace: "New space",
        addSpaceTitle: "Add space",
        addSpaceDesc: "Create a space with spots — e.g. Patio 1–10 or plain tables 1–20.",
        spaceKindLabel: "Type",
        spaceKindPrefixed: "Named space (e.g. Patio-1)",
        spaceKindMain: "Plain tables (1, 2, 3…)",
        spaceKindSunbed: "Sunbeds",
        spaceKindRoom: "Rooms",
        spaceNameLabel: "Space name",
        spaceNameRequired: "Enter a space name (e.g. Patio, Bar).",
        fromLabel: "From",
        toLabel: "To",
        createSpace: "Create space",
        creatingSpace: "Creating…",
        deleteSpace: "Delete space",
        deleteSpaceConfirm: (name: string, count: number) =>
          `Delete space «${name}» and ${count} spot${count === 1 ? "" : "s"}? This cannot be undone.`,
        spaceDeleted: (name: string) => `Space «${name}» deleted.`,
        spaceCreated: (name: string, count: number) =>
          `Created space «${name}» with ${count} spot${count === 1 ? "" : "s"}.`,
        tablesTabLink: "Edit individual spots →",
        invalidRange: "Check the From and To numbers.",
        zoneQrTitle: "QR & link per space",
        zoneQrDescription:
          "Each space has its own QR — scanning it shows only that space (e.g. Main hall, Patio).",
        zoneQrHint:
          "For named staff with their own link, go to «Staff» — that is also where you rotate access codes.",
        zoneQrLoading: "Loading…",
        zoneQrLoadingQr: "QR…",
        zoneQrNoToken: "No access link found for this venue.",
        zoneQrOpenLink: "Open link",
        zoneQrCopyLink: "Copy link",
        zoneQrDownload: "Download QR",
      },
      demoBadge: "Sample — UI preview",
      personnel: {
        title: "Staff",
        description:
          "Add an employee: name, role, space and post. Pick role first — then the right posts appear.",
        addTitle: "New employee",
        addStaff: "Add",
        listTitle: "Staff members",
        editTitle: "Edit",
        cancelEdit: "Cancel",
        formHint:
          "Waiter = phone (calls, pass). Kitchen/Bar = tablet (quick messages, pass). Post must match Settings → Messages.",
        messagesScopeWaiter:
          "Floor waiter — calls & pass alerts on phone (does not send quick messages)",
        messagesScopeAll:
          "All posts & spaces — calls, pass alerts and every space on phone",
        messagesScopeTablet: "Pass tablet — sends this post's quick messages",
        colSpaceAll: "All",
        managePostsLink: "Manage posts →",
        manageSpacesLink: "Manage spaces →",
        manageMessagesLink: "Manage messages →",
        messagesPreviewEmpty: "No messages configured for this post yet.",
        noPosts: "No active posts.",
        noSpaces: "No spaces yet.",
        zoneRequired: "Pick a space — e.g. dining room, terrace, or All.",
        saving: "Saving...",
        colName: "Name",
        colRole: "Role",
        colRoleRequired: "Role *",
        colSpace: "Space",
        colPost: "Post",
        colPostHint: "Blue = mobile · teal = tablet",
        colScreen: "Screen",
        colSpaceRequired: "Space *",
        colPostRequired: "Post *",
        colScreenRequired: "Screen *",
        jobRoleWaiter: "Waiter",
        jobRolePass: "Kitchen / Bar",
        jobRoleWaiterHint: "Mobile — guest calls & pass",
        jobRolePassHint: "Tablet — quick messages & pass",
        screenMobile: "Mobile",
        screenKds: "Pass tablet",
        screenSupportTablet: "Messages tablet",
        screenMobileHint: "Guest calls & pass alerts on phone",
        screenKdsHint: "Quick messages & pass alerts on tablet",
        screenSupportTabletHint: "Quick messages on tablet (dishwash, cleaning, etc.)",
        postsOnKdsScreenHint:
          "Bar, kitchen, etc. from Posts tab → switch Screen to «KDS (pass tablet)».",
        postsOnMobileScreenHint:
          "Waiter (Services…) → switch Screen to «Mobile».",
        noKdsPosts: "No kitchen/bar posts yet — set them up in the Posts tab first.",
        noWaiterPosts:
          "No waiter post yet — add a post with role Waiter in the Posts tab (or pick All — everywhere).",
        selectSpacePlaceholder: "Choose space",
        selectPostPlaceholder: "Choose post",
        fieldsRequiredHint:
          "Name, role, space (waiter) and post are required. Posts are filtered by role.",
        colLink: "Link & QR",
        colLinkHint:
          "Waiter: phone link or QR. Kitchen/Bar: tablet link or QR — opens without login.",
        listDeviceLegend:
          "Blue = mobile · teal = tablet (pass or messages). The post column icon uses the same colors.",
        colActions: "Actions",
        viewLink: "Preview",
        viewLinkTablet: "Open screen",
        missingScreen: "No tablet link yet — save your posts in the Posts tab.",
        invalidAssignment: "No valid post — reassign post and space.",
        invalidStaffBanner: (n: number) =>
          n === 1
            ? "1 staff member has no valid post — edit the row below."
            : `${n} staff members have no valid post — edit the rows below.`,
        screenPostMismatch: "Screen name does not match a post — use the same name (e.g. «Kitchen»).",
        tabletScreensTitle: "Tablet screens",
        tabletScreensHint:
          "Links for KDS/Bar — opens without login. Screen name = post name.",
        copyLink: "Copy",
        copied: "Copied!",
        qrLink: "QR",
        qrTitle: (name: string) => `QR — ${name}`,
        qrHintMobile: "Scan on their phone — opens the waiter panel directly.",
        qrHintTablet: "Scan on the tablet — opens the pass screen without login.",
        downloadQr: "Download QR",
        qrLoading: "Loading QR…",
        qrFailed: "Failed.",
        qrNetworkError: "Network error.",
        rotateLink: "New link",
        rotateConfirm: (name: string) =>
          `New link for “${name}”? The old one will stop working.`,
        namePlaceholder: "e.g. Maria P.",
        rolePlaceholder: "Choose role",
        loading: "Loading...",
        empty: "No staff added yet.",
        deleteConfirm: (name: string) =>
          `Delete “${name}”?\n\nTheir personal link will stop working. This cannot be undone.`,
        deleteTitle: "Delete staff member",
        edit: "Edit",
        delete: "Delete",
        saveEdit: "Save",
        stationLabels: {
          services: "Services",
          kitchen: "Kitchen",
          bar: "Bar",
          cold: "Cold",
          dessert: "Dessert",
          all: "All",
        },
      },
      kitchen: {
        title: "Kitchen",
        description: "Chef screen — sends “pass ready” to waiters.",
        screenLink: "Kitchen screen link",
        screenHint: "Open on a kitchen tablet — no dashboard login.",
        sampleTable: "Table",
        sampleComment: "Comment (e.g. you forgot the ice)",
        sampleCommentPlaceholder: "you forgot the ice",
        sampleSend: "Send",
        openScreen: "Open screen",
        copyScreenLink: "Copy link",
      },
      kitchenTab: {
        title: "Kitchen screens",
        description:
          "Each screen opens on a tablet — no login. The chef taps “Ready” and waiters get notified.",
        steps:
          "Open the screen on the kitchen tablet\nCopy the link or tap “Open screen”\nFor a second kitchen/zone: add a new screen (e.g. Beach)",
      },
      bar: {
        title: "Bar",
        description: "Bar screen — notify waiters when drinks are ready.",
        screenLink: "Bar screen link",
        screenHint: "Quick actions for a bar tablet.",
        sampleSend: "Drink ready",
        openScreen: "Open screen",
        copyScreenLink: "Copy link",
      },
      barTab: {
        title: "Bar & dessert screens",
        description: "Same flow as kitchen — tablet at the bar or dessert pass, no login.",
        steps:
          "Open the screen on the bar tablet\nFor a second bar (e.g. beach): add a new screen\nDesserts can have their own screen",
      },
      cold: {
        title: "Cold kitchen",
        description: "Salads and cold starters — separate screen if you use one.",
        screenLink: "Cold kitchen screen link",
        screenHint: "Tablet at cold prep — no dashboard login.",
        openScreen: "Open screen",
        copyScreenLink: "Copy link",
      },
      dessert: {
        title: "Dessert",
        description: "Notify waiters when dessert is ready.",
        screenLink: "Dessert screen link",
        screenHint: "Tablet at dessert pass or near the bar.",
        openScreen: "Open screen",
        copyScreenLink: "Copy link",
      },
      rotateScreenButton: "New screen code",
      rotatingScreen: "Rotating...",
      rotateScreenConfirm: "Rotate the screen code? The current link will stop working.",
      rotateScreenFailed: "Could not rotate screen code.",
      copyLinkFailed: "Could not copy the link — try selecting it manually.",
      multiScreenHint:
        "You can add multiple screens per department (e.g. beach bar and main bar) — each with its own link.",
      loadingScreens: "Loading screens…",
      screensEmpty: "No screens yet — add one below.",
      showLink: "Show link",
      hideLink: "Hide link",
      allTablesZone: "All tables / sunbeds / rooms",
      addScreenFor: (dept: string) => `New screen — ${dept}`,
      addScreenTitle: "Add screen",
      addScreenHint: "A name to tell them apart (e.g. Beach, Main room).",
      screenNameLabel: "Screen name",
      screenPostMismatch: "Screen name does not match a post — use the same name (e.g. «Kitchen»).",
      screenNamePlaceholder: "e.g. Beach",
      screenSpotPrefixLabel: "Space (optional)",
      screenSpotPrefixPlaceholder: "e.g. Beach",
      screenSpotPrefixHint:
        "Empty = all tables, sunbeds and rooms. «Σαλόνι» = numeric tables only (1, 2, 3…). Any other prefix = only matching tables (e.g. Beach-1). Sunbeds/rooms need an empty prefix.",
      screenSpotPrefixHintShort:
        "Empty = all spots. «Σαλόνι» = numeric tables only. «Beach» = Beach-1, Beach-2… only",
      screenSpotPrefixActive: (prefix: string) => `Tables only: ${prefix}-*`,
      addScreenButton: "Add",
      addingScreen: "Adding…",
      addScreenFailed: "Could not add screen.",
      deleteScreen: "Delete",
      deleteScreenTitle: "Delete screen",
      deleteScreenConfirm: (name: string) =>
        `Delete screen «${name}»?\n\nIts link will stop working. This cannot be undone.`,
      deleteScreenFailed: "Could not delete screen.",
      renameScreen: "Rename",
      saveScreen: "Save",
      savingScreen: "Saving…",
      cancelScreenEdit: "Cancel",
      renameScreenFailed: "Could not rename screen.",
      screenNameTaken: "A screen with this name already exists.",
      tables: {
        title: "Spots",
        description:
          "Add tables, rooms and sunbeds. They appear on the waiter map and in QR codes.",
        zoneHint:
          "Each space has its own number range. E.g. Bar 1–10 creates Bar-1 … Bar-10 — a separate space on the waiter panel.",
        spacesBulkTitle: "Add per space",
        spacesBulkDesc:
          "One row per space. Enter a name and range (from–to) — not one big batch for the whole venue.",
        spaceNameLabel: "Space",
        spaceNameRequired: "Enter a space name (e.g. Bar, Hall).",
        spacePreview: (space: string, from: number, to: number, count: number) =>
          `Will create ${count} spots: «${space}-${from}» … «${space}-${to}»`,
        addSpaceRow: "Another space",
        addSpaceTables: "Add",
        gridPreview: "What the colors mean",
        gridHint: "Colors update live on the waiter map — you do not configure them here.",
        legendAutoNote:
          "Configure labels, departments and zones in the «Venue operations» card below.",
        qrLink: "Download QR codes →",
        yourVenueSpots: (name: string, count: number) => `${name} — ${count} spots`,
      },
      operations: {
        title: "Venue operations",
        description:
          "Which departments you use, quick messages on station screens, map labels and zone names.",
        loading: "Loading settings…",
        departmentsTitle: "Active departments",
        departmentsHint:
          "Add as many posts as you need (e.g. Grill, Garden, Beach). The name appears on waiter panel, push and station screens.",
        postActiveLabel: "Active",
        postNameLabel: "Post name",
        postSpaceLabel: "Space",
        postSpaceAll: "All spaces",
        postTypeLabel: "Role",
        postTypeHint: "Role sets waiter phone vs tablet (pass / messages).",
        postActionsLabel: "Actions",
        addPost: "New post",
        removePost: "Remove post",
        removePostConfirm: (name: string) =>
          `Remove post «${name}»? Its messages will be lost. This cannot be undone.`,
        postsMaxReached: "Up to 12 posts.",
        quickChipsTitle: "Quick messages",
        quickChipsHint: "One-tap buttons on kitchen/bar tablets.",
        chipPlaceholder: "New message…",
        resetDefaults: "Reset defaults",
        mapLabelsTitle: "Spot map labels",
        mapLabelsHint: "What waiters see on each table/spot tile.",
        zonesTitle: "Space names",
        zonesHint:
          "Spaces come from spot names (e.g. Patio-1). Customize how they appear here.",
        zonesPreviewTitle: "Preview",
        zonesPreviewHint: "This is how they appear in the waiter «Pick a space» panel — updates live.",
        zonesSourceLabel: "Source",
        zonesNameLabel: "Space name",
        zonesCountLabel: "Spots",
        save: "Save",
        saving: "Saving…",
        reload: "Reload",
        reloadDiscardConfirm:
          "You have unsaved changes. Discard them and reload from the server?",
        saved: "Saved.",
      },
      services: {
        title: "Services",
        description: "Waiter link, push alerts and notification settings — guest calls, orders and voice.",
        pushSectionTitle: "Push notifications",
        pushHint:
          "Enable push on this device (e.g. manager tablet). Applies to all venues in your organization — use Chrome/Safari, not Messenger or Instagram.",
        staffPushHint:
          "Each waiter enables push on their own phone — open their personal link and tap Enable.",
        notifications: {
          title: "Notifications",
          customerOrder: "Customer order activation",
          waiterCall: "Waiter call activation",
          voiceMessages: "Voice message activation",
          voiceHint:
            "Voice plays in Greek — with push, even in the background. Tap the screen once when open to unlock sound.",
          yes: "Yes",
          no: "No",
          saving: "Saving…",
          saved: "Saved.",
        },
        staffLinksHint: "Waiter links: Settings → Staff (one link per staff member).",
        minutesAgo: (n: number) => `${n} min ago`,
        tableLabel: (n: string) => `Table ${n}`,
        historyTitle: "Pass history",
        historyHint: "Completed deliveries — time from “ready” to “delivered”.",
        historyDaysLabel: "Period",
        historyDays7: "7 days",
        historyDays30: "30 days",
        historyDays90: "90 days",
        historyLoading: "Loading...",
        historyEmpty: "No deliveries in this period.",
        historyFailed: "Could not load history. Try again.",
        historyColSpot: "Spot",
        historyColStation: "Department",
        historyColMessage: "Comment",
        historyColReady: "Ready",
        historyColDuration: "Duration",
      },
      live360Guide: {
        title: "Live 360° setup",
        subtitle: "5 steps — then test from Screens",
        progress: (done: number, total: number) => `${done}/${total} done`,
        allDone: "Live 360° setup is complete.",
        openScreens: "Open Screens →",
        invalidStaff: (n: number) =>
          n === 1
            ? "1 staff member has no valid post — fix in Staff tab."
            : `${n} staff members have no valid post — fix in Staff tab.`,
        steps: {
          spaces: {
            label: "1. Spaces & spots",
            hint: "Tables, rooms — hall, patio, etc.",
          },
          posts: {
            label: "2. Posts",
            hint: "Kitchen, Bar — not waiter names.",
          },
          messages: {
            label: "3. Messages",
            hint: "Quick chips per post for tablets.",
          },
          screens: {
            label: "4. Tablet screens",
            hint: "Same name as the post — KDS/Bar links.",
          },
          staff: {
            label: "5. Staff",
            hint: "Waiter + zone or tablet post + link.",
          },
        },
      },
      nameLabel: "Name",
      roleLabel: "Role",
      save: "Save settings",
      saving: "Saving...",
      appearanceTitle: "Catalog appearance",
      appearanceDesc: "Logo, colors and details customers see on the QR menu.",
      venueNameLabel: "Venue name",
      taglineLabel: "Short tagline (optional)",
      taglineHint: "One line for the QR menu — e.g. “Sea view terrace”. Pick cuisine type separately.",
      descriptionLabel: "Description",
      primaryColor: "Primary color",
      secondaryColor: "Secondary",
      needVenueFirst: "Create a venue first to configure colors and appearance.",
    },
    newVenue: {
      title: "New venue",
      description: "Your restaurant, bar or hotel. The first catalog will be created automatically.",
      nameLabel: "Venue name *",
      taglineLabel: "Short tagline (optional)",
      taglineHint: "E.g. “Pool bar & restaurant in Rhodes” — not the cuisine type.",
      descriptionLabel: "Description (optional)",
      submit: "Create venue",
      submitting: "Creating...",
    },
  },
  onboarding: {
    guideLabel: "Getting started",
    guideIntro: "Complete 4 steps here — same flow on trial, Basic and Pro. Then the full panel unlocks.",
    navLockedHint: "Complete the getting-started steps first (Overview)",
    lockBanner: (step: number, label: string) =>
      `Step ${step}/4: ${label} — other pages stay locked until you finish.`,
    backToGuide: "Go to guide",
    retryFromStart: "Start over",
    retryConfirmTitle: "Start from scratch?",
    retryConfirmDesc:
      "Your venue and catalog created so far will be deleted. You will begin again at step 1.",
    retryConfirming: "Deleting…",
    qrPageHint: "Download or preview your QR codes here. When you're done, return to Overview for the final step.",
    stepTitle: (step: number) => `Step ${step} of 4 — build your catalog`,
    subtitle: "In under an hour you can have a QR menu on your tables.",
    completed: (n: number) => `${n}/4 complete`,
    nextStep: "Next step",
    backStep: "Previous",
    stepOf: (current: number) => `Step ${current} of 4`,
    stepHeading: (step: number, label: string) => `Step ${step}: ${label}`,
    stepLabels: ["Venue", "Catalog", "QR", "Done"] as string[],
    stepStatusDone: "Completed",
    stepStatusCurrent: "Current step",
    stepStatusPending: "Next",
    done: "Completed",
    pending: "Pending",
    previewIntro: "See how it looks to customers:",
    openCatalog: "Open catalog",
    steps: {
      venue: {
        title: "Open your venue",
        desc: "Name your business — restaurant, bar or hotel. E.g. «Marine Hotel» or «George's Taverna».",
        cta: "Open venue",
      },
      menu: {
        title: "Build your catalog",
        titleSeeded: "Your catalog is ready",
        descWithCategory: "Add or edit items, prices and photos. PDF import available on Pro.",
        descSeeded:
          "We added sample dishes to get you started. You can edit them later from the Catalog page.",
        descWithoutCategory:
          "Create categories (Salads, Mains, Drinks...) and add at least one item with a price.",
        cta: "Go to catalog",
        ctaContinue: "Continue to QR",
        acknowledging: "One moment...",
        seedFailed: "Could not save the catalog. Try again or contact us.",
      },
      qr: {
        title: "Get QR codes",
        desc: "Download one QR for your whole catalog and print it wherever you like.",
        cta: "View QR codes",
        ctaContinue: "Continue",
        acknowledging: "One moment...",
        failed: "Could not save this step. Try again or contact us.",
      },
      done: {
        title: "Congratulations!",
        desc: "Your catalog is online. Press OK to open the full panel.",
        summaryVenue: "Venue",
        summaryCuisine: "Cuisine",
        summaryDescription: "Description",
        summaryCatalog: "Catalog",
        summaryItems: (n: number) => `${n} ${n === 1 ? "item" : "items"}`,
        summaryMenus: (n: number) => `${n} ${n === 1 ? "menu" : "menus"}`,
        summaryLink: "QR menu link",
        summaryQr: "QR codes — ready to print",
        cta: "OK",
        confirming: "One moment...",
        failed: "Could not finish setup. Try again or contact us.",
      },
    },
  },
  overview: {
    titleFallback: "Overview",
    heroEyebrow: "Overview",
    metricsTitle: "Metrics",
    addFirstVenue: "Add your first",
    addToCatalog: "Add to catalog",
    quickActions: "Quick actions",
    actionVenue: "Set up your venue",
    actionCatalog: "Items, prices & categories",
    actionQr: "QR for tables & rooms",
    actionScreens: "Guest calls & live pass",
    actionPreview: "See the guest view",
    actionHistory: "Pass delivery history",
    actionBilling: "Plan & subscription",
    quickStartEmpty: "Start by adding categories and items — then generate QR codes for your tables.",
    quickStartReady: "Your catalog is online! Generate QR codes or view customer calls.",
    catalogLiveStatus: "Online",
    callsWaiterSuffix: "waiter",
    renewalUntil: "Renews until",
    planField: "Plan",
    catalogOne: "catalog",
    catalogMany: "catalogs",
    passToday: "Pass alerts today",
    passTodayHint: "From kitchen / bar screens",
    passAvgDelivery: "Avg pickup time",
    passAvgDeliveryHint: "Ready → delivered, last 7 days",
    passAvgNone: "—",
    passAvgMinutes: (n: number) => `${n} min`,
    planSummary: (plan: string, venueN: number, venueWord: string, menuN: number, menuWord: string, items: string) =>
      `Plan: ${plan} · ${venueN} ${venueWord} · ${menuN} ${menuWord} · ${items}`,
  },
  menuEditor: {
    noVenueTitle: "You don't have a venue yet",
    noVenueDesc:
      "Create your venue (restaurant, bar or hotel) first, then add items to the catalog.",
    onboardingReadOnlyBanner:
      "The catalog is view-only until you finish setup — edit it later from Overview.",
    categoryNew: "New category",
    categoryHint: "Greek only — EN / DE / FR are auto-generated for the QR menu",
    addCategory: "Add category",
    addingCategory: "Adding...",
    categoryLabel: "Category",
    renameCategory: "Rename category",
    deleteEmptyCategory: "Delete empty category",
    deleteCategoryConfirm: "Delete this category?\n\nAre you sure? This cannot be undone.",
    invalidPrice: "Enter a valid price (e.g. 4.50).",
    categoryNameRequired: "Enter a category name.",
    loadingSubtitle: "Loading categories and items",
    syncCatalogHint: "Same selection as PDF import — items appear here.",
    editPrice: "Change price",
    qrBadge: "Badge on QR menu",
    active: "Active",
    inactive: "Inactive",
    remove: "Remove",
    saving: "Saving...",
    emptyCategories: "No categories yet. Add the first one above to get started.",
    autoTranslateHint: "Greek only — EN / DE / FR are auto-generated for the QR menu",
    qrExtrasTitle: "Customer options",
    qrExtrasHint:
      "Customers choose these on the QR menu. Optionally add an extra charge (e.g. +€1.50).",
    qrExtrasCount: (n: number) => `${n} QR options`,
    noBadge: "No badge",
    extraChargePlaceholder: "Extra charge (optional)",
    addExtraOption: "Add option",
    cancel: "Cancel",
    itemDescription: "Dish description",
    itemDescriptionHint:
      "Shown on the QR card (1–2 lines). Leave empty to show name and price only — the layout stays clean.",
    itemIngredients: "Ingredients (optional)",
    itemIngredientsPlaceholder: "e.g. tomato, cucumber, olive oil, feta",
    dietaryTagsTitle: "Dietary labels",
    dietaryTagsHint: "Shown as small tags below the description on the QR menu.",
    allergenCodesTitle: "Allergens",
    allergenCodesHint: "Select all that apply — shown on the QR menu.",
  },
  flash: {
    close: "Close",
    genericError: "Something went wrong.",
    success: "Success!",
    codes: {
      subscription_inactive: "Your subscription is not active. Upgrade to continue.",
      trial_expired: "Your trial period has ended.",
      unauthorized: "Please sign in again.",
      forbidden: "You don't have permission.",
      venue_limit: "You've reached your plan's venue limit. See plans on Subscription.",
      menu_limit: "You've reached your plan's catalog limit. See plans on Subscription.",
      item_limit: "You've reached your plan's item limit. See plans on Subscription.",
      not_found: "Not found.",
      enterprise_contact: "Contact us for Enterprise pricing.",
      stripe_not_configured: "Payments are not available.",
      rate_limited: "Too many attempts. Try again later.",
      bad_request: "Invalid request.",
      invalid_input: "Invalid data.",
      password_mismatch: "New password and confirmation do not match.",
      password_same: "New password must differ from the current one.",
      invalid_password: "New password must be at least 8 characters.",
      wrong_password: "Current password is incorrect.",
      slug_exists: "This URL slug already exists. Try another venue name.",
    } as Record<string, string>,
  },
  meta: {
    appSuffix: "MenuOS",
    overview: "Overview",
    menus: "Catalog",
    import: "Import from PDF",
    qr: "QR Codes",
    waiter: "Screens",
    history: "History",
    billing: "Subscription",
    settings: "Settings",
    newVenue: "New venue",
  },
  api: {
    badRequest: "Invalid request.",
    invalidData: "Invalid data.",
    menuNotFound: "Catalog not found.",
    venueNotFound: "Venue not found.",
    categoryNotFound: "Category not found.",
    fillNameAndPrice: "Enter name and price.",
    fillCategoryNameGr: "Enter category name (Greek).",
    invalidCategoryName: "Invalid category name.",
    categoryAdded: (name: string) => `Category «${name}» added.`,
    categoryRenamed: (name: string) => `Category renamed to «${name}».`,
    categoryUpdated: "Category updated.",
    categoryDeleted: "Category deleted.",
    menuDeleted: "Catalog deleted.",
    allMenusDeleted: (stats: { menus: number; items: number }) =>
      stats.items > 0
        ? `Deleted ${stats.menus} catalogs and ${stats.items} items. One empty catalog remains.`
        : `Deleted ${stats.menus} catalogs. One empty catalog remains.`,
    venueSaved: "Settings saved.",
    venueCreated: "Venue created! Now add categories and items.",
    menuCreated: "Catalog created.",
    venueIdRequired: "Venue ID is required.",
    invalidMenuData: "Invalid catalog data.",
    slugExists: "This URL slug already exists. Try another venue name.",
    defaultMenuName: "Main catalog",
    spotAdded: "Spot added.",
    spotExists: "Spot already exists.",
    spotsBulkAdded: (n: number) => `Added ${n} spots.`,
    import: {
      invalidDraft: "Check categories, names and prices before importing.",
      selectMenu: "Select a catalog.",
      selectAtLeastOne: (one: string) => `Select at least one ${one}.`,
      parseFound: (items: string, categories: number) =>
        `Found ${items} in ${categories} categories. Review before importing.`,
      parseEmpty: (many: string) => `No ${many} found — try another PDF or add manually.`,
      parseFailed: "Could not read PDF. Try again or add the catalog manually.",
      translateUnavailable: "AI translation is not available yet — fill in Greek manually.",
      translateInvalidDraft: "Invalid draft — run PDF analysis again.",
      translateNothingNeeded: "No translation needed — names are already in Greek.",
      translateSuccess: (n: number) =>
        n === 1 ? "Translated 1 name to Greek." : `Translated ${n} names to Greek.`,
      translateFailed: "AI translation failed. Try again or fill in Greek manually.",
      geminiQuotaExceeded: (used: number, limit: number) =>
        `You reached the monthly Gemini AI limit (${Math.round(used / 1000)}k / ${Math.round(limit / 1000)}k tokens). Try again next month or contact us.`,
      applySuccess: (items: string, categories: number) =>
        `Imported ${items} into ${categories} categories. Edit photos and prices in the catalog.`,
    },
    pdf: {
      noFiles: "Select at least one PDF.",
      tooMany: (max: number) => `Maximum ${max} PDFs at a time.`,
      notPdf: (name: string) => `«${name}» is not a PDF.`,
      tooLarge: (name: string) => `«${name}» is too large (max 10MB).`,
      readFailed: (name: string) =>
        `Could not read «${name}». The file may be locked or corrupted.`,
      noText: (name: string, pageHint: string, ocrHint: string) =>
        `«${name}» did not yield recognizable text${pageHint}.${ocrHint}`,
      ocrNoText: " OCR found no text — try other pages or manual entry.",
      ocrNotConfigured: " Scanned PDFs need extra setup — try a PDF with selectable text or contact support.",
      noPagesSelectedOcr:
        "No text on selected pages. Try Advanced → page selection.",
      noPagesSelectedNoOcr:
        "No text found in the PDF. For scanned menus try another PDF or contact support.",
      pagesHint: (pages: number[]) => ` (pages ${pages.join(", ")})`,
    },
  },
  subscriptionStatus: {
    TRIALING: "Trial",
    ACTIVE: "Active",
    PAST_DUE: "Payment overdue",
    CANCELED: "Canceled",
    trialActive: "Active trial",
    trialGrace: "Extension period",
    trialExpired: "Expired",
    expiresOn: (date: string) => `Expires ${date}`,
    graceUntil: (date: string) => `Extension until ${date}`,
    renewsOn: (date: string) => `Renews ${date}`,
    endsOnNoRenewal: (date: string) => `Ends ${date} — no auto-renewal`,
    expiredOn: (date: string) => `Expired ${date}`,
  },
} as const;
