/** Παραδείγματα για κενά πεδία φορμών (placeholder). */
export const FORM_PLACEHOLDERS = {
  personName: "π.χ. Γιάννης Παπαδόπουλος",
  businessName: "π.χ. Marine Hotel",
  email: "π.χ. owner@example.gr",
  passwordNew: "Τουλάχιστον 8 χαρακτήρες",
  passwordCurrent: "Ο τρέχων κωδικός σου",
  otp: "123456",
  venueName: "π.χ. Hellas Taverna",
  venueDescription: "π.χ. Pool bar & restaurant στη Ρόδο",
  storeDescription: "π.χ. Με θέα στο λιμάνι",
  categoryGr: "π.χ. Κυρίως πιάτα",
  categoryEn: "e.g. Main courses",
  categoryDe: "z.B. Hauptgerichte",
  categoryFr: "p.ex. Plats principaux",
  itemNameGr: "π.χ. Χωριάτικη σαλάτα",
  itemNameEn: "e.g. Greek salad",
  itemNameDe: "z.B. Griechischer Salat",
  itemNameFr: "p.ex. Salade grecque",
  itemPrice: "π.χ. 8,50",
  itemDescription: "π.χ. Ντομάτα, αγγούρι, φέτα",
  extraOption: "π.χ. Χωρίς αλάτι",
  extraPrice: "1,50",
  phone: "π.χ. 210 1234567",
  mobile: "π.χ. 694 1234567",
  vat: "123456789",
  city: "π.χ. Ρόδος",
  internalNotes: "Σημειώσεις ops…",
  searchOrganizations: "Όνομα, email, slug…",
  supervisorUsername: "π.χ. ops.maria",
  supervisorName: "π.χ. Μαρία Κ.",
  planDisplayName: "π.χ. Pro",
  planPriceMonthly: "π.χ. 19,99",
  planDescription: "π.χ. Για μεγάλα εστιατόρια",
  planFeatures: "π.χ. Απεριόριστα πιάτα\nπ.χ. Εισαγωγή PDF",
  planCta: "π.χ. Ξεκίνα δωρεάν",
  planBadge: "π.χ. Δημοφιλές",
  trialDays: "7",
  planSortOrder: "0",
  maxVenues: "π.χ. 3",
  spotBulkFrom: "1",
  spotBulkTo: "20",
  spotSpaceName: "π.χ. Bar, Σαλα",
  qrTable: "12",
  qrRoom: "204",
  importCategory: "π.χ. Σαλάτες",
  importItemGr: "π.χ. Χωριάτικη",
  importItemEn: "Greek salad",
  importItemPrice: "8,50",
} as const;
