export const PAGES_EN = {
  common: {
    localeSwitchFailed: "Could not switch language. Please try again.",
    designedFor: "Built for",
    industries: ["Hotels", "Restaurants", "Beach bars", "Cafés", "Room service"],
    servicesLink: "View all services →",
    howItWorksLink: "Workflow details →",
    learnMore: "Learn more",
    startFreeTrial: "Start free {trialDaysAdj} trial",
    createAccount: "Create account",
  },
  services: {
    heroTitle: "Our services",
    sectionTitle: "What's included",
    cta: {
      title: "Want to see it live?",
      description: "Create a free account, set up your first venue and test the QR with your team — in under an hour.",
      primary: "Start free {trialDaysAdj} trial",
      secondary: "How it works",
    },
    items: [
      {
        title: "Digital menu with QR code",
        description: "Guests scan and see categories, photos, prices, descriptions and allergens — no app install.",
        bullets: ["Instant browser open", "QR per table or room", "Premium mobile layout"],
      },
      {
        title: "Management dashboard",
        description: "Add items, change prices and availability from one panel — no technical skills needed.",
        bullets: ["Simple admin forms", "Multiple venues", "Live updates"],
      },
      {
        title: "Multiple menus per venue",
        description: "Breakfast, restaurant, pool bar, room service, spa — each area with its own catalogue.",
        bullets: ["Ideal for hotels", "Branding per menu", "Easy categories"],
      },
      {
        title: "Multiple QR languages",
        description: "Guests choose their language on the QR menu — one tap.",
        bullets: ["Multiple QR languages", "Great for tourism", "Allergens & ingredients"],
      },
      {
        title: "Call waiter",
        description: "Guests call staff from the menu. Table or room from the QR link.",
        bullets: ["Less delay", "Better service", "Rate limit for safety"],
      },
      {
        title: "MenuOS Live · 360°",
        description:
          "Live alerts for waiters, kitchen and bar — connected to the same QR menu. No POS.",
        bullets: ["Push to mobile", "Ready dish & drink", "Staff link, no login"],
      },
      {
        title: "Print-ready QR codes",
        description: "Download QR for tables, rooms, bar or pool. Optional table= / room= in links.",
        bullets: ["High-res export", "Branded look", "Quick placement"],
      },
      {
        title: "Branding & colours",
        description: "Match colours and logo to your venue identity.",
        bullets: ["Premium look", "Venue consistency", "Quality impression"],
      },
      {
        title: "Security & privacy",
        description: "Each business has isolated data. Modern security standards.",
        bullets: ["Multi-tenant isolation", "GDPR-ready", "No shared data"],
      },
    ],
  },
  howItWorks: {
    heroTitle: "How it works",
    eyebrow: "The process",
    sectionTitle: "From sign-up to live menu",
    sectionDesc: "Seven simple steps. No install, no reprints — set up from the dashboard.",
    ctaButton: "Start now — free {trialDays}",
    cta: {
      title: "Want a demo first?",
      description: "Call 210 700 0925 or email info@qrmenus.info — we'll walk you through live.",
      primary: "Contact",
      secondary: "All services",
    },
    steps: [
      {
        title: "Sign up & trial",
        body: "Create an account with email, business name and OTP. {trialDays} free — no credit card.",
        detail: "After sign-up you're in the dashboard on trial plan.",
      },
      {
        title: "Create venue & menu",
        body: "Add venue, menu and categories. Each dish has price, description and optional photo.",
        detail: "Example: Salads → Greek salad €12, allergens, photo.",
      },
      {
        title: "Languages & details",
        body: "Fill Greek (required) and optionally EN / DE / FR. Guests switch language on the QR menu.",
        detail: "Allergens, ingredients and availability — all online.",
      },
      {
        title: "QR codes on tables",
        body: "Download QR codes from the dashboard and place on tables, rooms or bar.",
        detail: "Links like ?table=12 help staff know where the guest is.",
      },
      {
        title: "MenuOS Live · 360°",
        body: "Send links to waiters and kitchen/bar screens. Push alerts with table number — no login.",
        detail: "Guest calls, ready dishes: all connected around the same QR.",
      },
      {
        title: "Guest experience",
        body: "Guest scans, browses menu, switches language and calls waiter — all in browser.",
        detail: "No app, no login for visitors.",
      },
      {
        title: "Updates & subscription",
        body: "Price changes appear instantly. After trial choose Basic or Pro — or Enterprise.",
        detail: "Billing via Stripe, transparent pricing.",
      },
    ],
  },
  qrMenu: {
    heroTitle: "QR menu for restaurants & hotels",
    sectionTitle: "Why QR menu instead of printed?",
    sectionDesc:
      "Printed menus cost money, lag behind and don't follow your business. Digital menu is live, beautiful and under your control.",
    useCasesEyebrow: "Use cases",
    useCasesTitle: "Where MenuOS fits",
    useCasesDesc: "From small taverna to hotel — same simplicity, premium result.",
    useCases: [
      "Restaurants & tavernas in tourist areas",
      "Hotels with pool bar, breakfast and room service",
      "Beach bars & all-day cafés",
      "Catering & events with QR per area",
    ],
    faqTitle: "FAQ",
    faqDesc: "What restaurateurs and hoteliers ask most.",
    faq: [
      { q: "What is a QR menu?", a: "A digital menu that opens when the guest scans a QR code. No app needed." },
      { q: "Does it fit hotels?", a: "Yes — pool bar, breakfast, room service. Separate menu per area." },
      { q: "How many languages?", a: "Multiple languages on the QR menu — one tap to switch." },
      { q: "Can I change prices quickly?", a: "Yes. From the dashboard — changes appear instantly." },
      {
        q: "What is MenuOS Live · 360°?",
        a: "Live alerts for waiters, kitchen and bar — connected to the same QR menu. No guest app.",
      },
    ],
    cta: {
      title: "Ready for a premium QR menu?",
      description: "Build your first menu today. {trialDays} free, no credit card.",
      primary: "Create account",
      secondary: "View pricing",
    },
    benefits: [
      {
        title: "Instant updates",
        description: "Change price or dish and it shows immediately — no reprint.",
        bullets: ["Less paper cost", "No outdated menus", "Seasonal menus in minutes"],
      },
      {
        title: "Tourists & bilingual",
        description: "Guests read the menu in their language — ideal for islands and cities.",
        bullets: ["Multiple languages", "Better experience", "For tourists"],
      },
      {
        title: "Visual menu",
        description: "Dish photos, descriptions and allergens — premium on mobile.",
        bullets: ["Higher average order", "Upsell with images", "Professional branding"],
      },
      {
        title: "No app",
        description: "QR and browser only. Guest downloads nothing.",
        bullets: ["Instant access", "iOS & Android", "No App Store"],
      },
    ],
  },
  about: {
    heroTitle: "About us",
    paragraphs: [
      "MenuOS is a Greek digital QR menu platform with Live 360° coordination for your team. Our goal: every restaurant, hotel or bar offers a modern mobile menu — without building their own app.",
      "We know Greek hospitality: seasonality, tourists, multiple QR languages, fast price changes.",
      "We don't sell hardware. We give you an online service: build menu, print QR, guests scan.",
    ],
    valuesTitle: "Our values",
    valuesDesc: "What guides every feature and every support conversation.",
    missionTitle: "Our mission",
    missionBody:
      "Digital menu should be as easy as changing a price — but more beautiful and guest-friendly.",
    missionNote: "Support in Greece — phone, email, personal contact.",
    trialButton: "{trialDaysAdj} trial",
    cta: {
      title: "Let's build your menu",
      description: "{trialDays} free. No credit card.",
      primary: "Create account",
      secondary: "Services",
    },
  },
  pricing: {
    heroTitle: "Simple, transparent pricing",
    enterpriseBadge: "Enterprise",
    enterpriseTitle: "Custom for chains",
    enterpriseDesc: "White-label, custom domain, multiple venues, priority support — contact for a quote.",
    enterpriseCta: "Request quote",
    faqTitle: "Pricing questions",
    faqDesc: "What you need to know before you start.",
    trustItems: [
      "Free {trialDaysAdj} trial — no card",
      "Monthly billing, cancel anytime",
      "Support in Greek",
      "Secure Stripe payments",
    ],
    demoCta: "View live demo menu",
    cta: {
      title: "Start free today",
      description: "{trialDaysAdj} trial. No credit card.",
      primary: "Create account",
      secondary: "Ask us",
    },
    plans: [
      {
        name: "Trial",
        price: "€0",
        period: " / {trialDays}",
        description: "Try the platform before choosing a plan.",
        features: [
          "1 venue",
          "1 catalog",
          "50 items",
          "Catalog QR code",
          "Multiple languages",
          "No card required",
        ],
        cta: "Sign up",
      },
      {
        name: "Basic",
        price: "€9.99",
        period: "/month",
        description: "Ideal for restaurant, café or single venue.",
        features: [
          "1 venue",
          "5 catalogs",
          "Unlimited items",
          "Catalog QR code",
          "Multiple languages",
          "Always online — renews monthly",
        ],
        cta: "Start Basic",
        badge: "Popular",
        highlighted: true,
      },
      {
        name: "Pro",
        price: "€19.99",
        period: "/month",
        description: "For hotels and businesses with multiple areas.",
        features: ["3 venues", "Unlimited menus", "Live 360°", "Call waiter", "Multiple languages", "PDF import · Gemini AI", "Priority support"],
        cta: "Start Pro",
      },
    ],
  },
  contact: {
    heroTitle: "Contact",
    heroSubtitle: "Questions, trial or custom plan. We reply personally — not a bot.",
    badge: "Support",
    cards: [
      { title: "Phone", description: "For quick info, demo or appointment:" },
      { title: "Email", description: "General questions, Enterprise, technical support:" },
      { title: "Facebook", description: "News, tips and updates:", label: "MenuOS Greece" },
      { title: "WhatsApp", description: "Quick message — great for small businesses:", label: "Send message" },
    ],
    newCustomerTitle: "New customer?",
    newCustomerBody: "Free sign-up is fastest — {trialDays} without card. Create a venue and test QR.",
    enterpriseTitle: "Enterprise & chains",
    enterpriseBody: "Multiple locations, white-label, custom domain — contact for a tailored quote.",
    enterpriseBullets: ["Custom plans & SLA", "Onboarding help", "Billing from dashboard"],
    infoTitle: "MenuOS — menuos.gr",
    infoDesc: "For businesses in Greece and abroad.",
    cta: {
      title: "Prefer to talk?",
      primary: "Call now",
      secondary: "Send email",
    },
  },
  home: {
    trialCardTitle: "Start without risk",
    trialCardBody: "Create a venue, add items and test QR with your team before choosing a plan.",
    trialBadge: "{trialDaysAdj} trial",
  },
  auth: {
    errors: {
      bad_request: "Invalid request.",
      invalid_input: "Invalid details.",
      invalid_email: "Invalid email.",
      rate_limited: "Too many attempts. Try again later.",
      invalid_credentials: "Wrong email or password.",
      email_taken: "This email is already registered.",
      otp_missing: "No code found. Send a new code to your email.",
      otp_expired: "Code expired. Send a new code to your email.",
      otp_locked: "Too many wrong attempts. Send a new code.",
      otp_invalid: "Wrong code. Check your email.",
      cooldown: "Wait {s}s before resending the code.",
      mail_failed: "Could not send email. Try again shortly.",
      duplicate: "This email or organization already exists.",
      server_error: "Server issue. Try again shortly or email info@qrmenus.info.",
    },
    login: {
      title: "Welcome back",
      subtitle: "Sign in to your dashboard for menus, QR codes and billing.",
      password: "Password",
      submit: "Log in",
      submitting: "Signing in...",
      failed: "Sign in failed.",
      noAccount: "Don't have an account?",
      freeTrial: "Free trial {days}",
    },
    register: {
      title: "Create account",
      nameLabel: "Your name",
      businessLabel: "Business name",
      otpLabel: "Code from email (6 digits)",
      passwordLabel: "Password",
      hasAccount: "Already have an account?",
      loginLink: "Log in",
      sendOtp: "Send code",
      resendOtp: "Resend code",
      sendingOtp: "Sending...",
      resendIn: "Again in {s}s",
      otpSent: "Code sent — check spam too.",
      otpSentSuccess: "We sent a code to your email. Valid for {minutes} minutes.",
      otpExpiresIn: "Expires in {t}.",
      creating: "Creating...",
      submitCreate: "Create account",
      submitCheckout: "Continue to payment",
      subtitleTrial:
        "Free trial {days} — no card. We'll email you a verification code (valid 30 minutes).",
      subtitleBasic: "Create an account and continue to secure Basic payment (Stripe). Card required.",
      subtitlePro: "Create an account and continue to secure Pro payment (Stripe). Card required.",
      emailRequired: "Enter your email first.",
      otpRequired: "Send and confirm the email code first.",
      otpExpired: "Code expired. Send a new code to your email.",
      sendOtpFailed: "Failed to send code.",
      registerFailed: "Registration failed.",
      networkError: "Connection error. Check your internet and try again.",
      serverError: "Server issue. Try again shortly or email info@qrmenus.info.",
      otpSeconds: "{s} sec",
      otpMinutes: "{m} min",
      otpMinutesSeconds: "{m}:{s}",
    },
  },
} as const;
